### ISSUE TITLE
Styling kontrollieren und reparieren

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#116]
Im Moment scheinen deine ganzen Stylinganpassunge nicht zu funktionieren. Seit dem Umzug der Seite werden auch die Schriften nicht mehr korrekt geladen.
 * [ ] Schriften und Größen üerprüfen
 * [x] zweispaltige Formulare wieder lauffähig machen
 * [ ] Bild bei den sonstigen Systemen weg https://zen-reiki.de/system/

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/50451513-cc2d9700-0934-11e9-905b-07481ade1997.png)

Im Moment gibt es massive Stylingprobleme aud der alten Seite zen-reiki.de.
Kannst du zeitnah mal schauen? Ich vermute, dass durch die neuen Updates dein Styling nochmal kompiliert werden muss.

https://zen-reiki.de/kontaktformular/

Ebenso Styling Forum
![grafik](https://user-images.githubusercontent.com/6114076/50451600-570e9180-0935-11e9-8c80-a6e0a7e59b19.png)

**Comment by springers54** [comment]
Bei mir lies sich das Problem durch Löschen vom Cache wieder reparieren´, bei Dani ist es nach wie vor.

**Comment by springers54** [comment]
@joergsteinhauer Kannst du bitte nochmal schauen? Die Formulare sind zerschossen und das Forum. Es fällt erst auf, wenn man den Browsercache löscht. Vorher ging es bei mir, nach dem Löschen der Browser-Daten nicht mehr. Weder auf PC, noch auf IPAD

**Comment by joergsteinhauer** [comment]
Schaue ich. Scheint wieder das gleiche Problem zu sein, wie schon ma vor einer Weile - damals war ein Plugin-Update das Problem, glaube ich... wird diesmal evtl. das gleiche sein? Oder hat jemand mal das CSS aus versehen angepasst?

**Comment by springers54** [comment]
Das css hat keiner angefasst.
Updates gab es einige, die laufen automatisch.

Vielleicht kompilierst du das css nochmal?
Da das Kontaktformular nicht mehr zweispaltig ist und das Forum zerschossen ist, denke ich nicht, dass ein Plugin die Ursache ist.

**Comment by joergsteinhauer** [comment]
Ok, dann waren das die Updates... vermutlich. 

Ja, mache ich. Ich kam gestern ja nicht auf den FTP. Zuerst vergleiche ich aber mal die CSS, muss ja verstehen und nachvollziehen wo das Problem liegt.

**Comment by joergsteinhauer** [comment]
Habe die `main-style.css` verglichen - die waren tatsächlich unterschiedlich, warum auch immer.
Vorsichtshalber habe ich einen Backup der genannten Datei erstellt.

Und dann eben meine lokale CSS auf den FTP hochgeladen, scheint wieder alles ok zu sein.

Allerdings habe ich mein lokales CSS ncith neu kompiliert (war an sich auch nicht nötig), da ich seit kurzem neuen Rechner habe und hier LESS noch nicht installiert habe - will ich auch vermeiden, weil das damals ziemliches Rumgewurstel war... Ich hoffe ich muss im alten System nichts weiter gestalten.
Im neuen System haben wir übrigens SCSS statt LESS.

**Comment by springers54** [comment]
prima, zumindest auf Laptop und IPAD geht es nach dem Löschen der Browser-Daten wieder.
