### ISSUE TITLE
Welche Plugins brauchen wir auf der neuen Seite?

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#120]
Unverzichtbar aus meiner Sicht sind:
**Admin Menu Editor Pro
Asgaros Forum
BackupGuard Pro**
Better Search Replace Pro kann eventuell weg
**Contact Form 7**
**Flamingo
Wordfence Security
WP Fastest Cache Premium
WP Media folder
Yoast SEO Premium**

**Comment by springers54** [comment]
Ich habe eine Reihe von Plugins auf der neuen Seite installiert, die wir im alten System haben und die notwenig sind. Genau hier würde ich auch weitermachen wollen und mich daran machen, die Inhalte aus der alten Datenbank in die neue Datenbank zu übernehmen.
Dann sehen wir das Verfahren, ob es überhaupt funktionieren kann. 

Ich schlage folgende Schritte vor:
1. User-Tabelle und Meta-User-Tabelle #124 
2. Kontaktforumulare
3. Bilder und Bilderordner

**Comment by joergsteinhauer** [comment]
Ok. Mich würde interessieren, was welcher Plugin genau macht und ob man das ohne Plugins umsetzen kann.

Ich sehe schon jetzt bei folgenden Plugins Potenziall es ohne Plugins zu machen bzw. hinterfrage die Nützlichkeit der Plugins:
- Bilder und Bilderordner: reicht nicht die default WP Ordnerstruktur? Media-Bereich ist doch relativ gut aufgestellt. 
- WP Media folder: ist es das hier? https://www.joomunited.com/wordpress-products/wp-media-folder - finde es überflüssig, zumindest komme ich persönlich imemr gut zurecht mit dem WP eigenen Media-Bereich. Werden denn so oft und so viele Fotos hochgeladen, sodass man so heftig für Ordnung sorgen muss? 
- BackupGuard Pro: Backups sind wichtig, aber diese lassen sich auch händisch relativ gut durchführen. Zumal das nicht so oft passiert - ein mal im Quartal reicht meist aus. DB exportieren aus PHP My Admin und dann evtl. das ganze Projekt über FTP runterladen. 
- Wordfence Security: ist das unbedingt notwendig? ich habe mich kurz dazu belesen: https://fastwp.de/security-plugins-wordpress-wordfence-security/, scheitn nicht wirklich ein Gewinn zu sein. Ich habe keine Ahnugn, welche Daten auf der ZR Seite gespeichert und verarbeitet werden. Generell aber ist man mehr sicher, je weniger Plugins man installiert.
- Yoast SEO Premium: ist die ZR Seite so schlecht aufgestellt, dass man hier extra SEO betreiben muss? Ich halte nicht viel von solchen Plugins - WP hauseigene Mittel reichen meist aus für normale SEO Ergebnisse, ich hatte nie Probleme mit SEO. Habe aber nun wenig Überblick darüber, wie wichtig SEO in diesem Fall ist. Habt ihr eine Fanbase, die sich selbst ohne Google-Suche entwickel oder kommen die meisten neuen Besucher wirklich über die Suche?
- WP Fastest Cache Premium: würde ich zumindest während der Entwicklung deaktivieren. Ist erst wichtig, wenn die Seite final ist und an Enduser ausgeliefert wird

**Comment by springers54** [comment]
Ich denke, die Nützlichkeit zu hinterfragen und darüber zu diskutieren, bleibt immer eine Standpunktfrage und ich möchte hierfür weder deine noch meine kostbare Zeit vergeuden. Nur ganz kurz nochmal; ohne hier jetzt wieder eine Diskussion anzufangen. Die Plugins, die ich jetzt benutze, sind Ergebnis eines ziemlich langen Selektionsprozesses und viel Ausprobierei. Da ich für viele Dinge bezahle, würde ich das nicht tun, wenn mich der Nutzen nicht überzeugen würde.

- Mediafolder fand ich übersichtlich, zumal damit auch Galerien sehr einfach erstellt werden können. Wesentlich übersichtlicher als die Bordmittel

- BackupGuard hat mir schon ein paarmal den Hals gerettet. Klar, kann man das händisch machen, aber einmal die Woche automatisch ist einfach praktisch, zumal es auch noch auf die Dropbox geladen wird.  Hierüber könnte man diskutieren, wenn das System stabil läuft.

- Wordfense halte ich für ebenfalls sinnvoll gegen Hackerangriffe. Es reduziert die Zahl der Versuche,, zeigt Spamer, sperrt aus, überwacht den Code. Wir haben Nutzerdaten von mehr als 9000 Leuten, das bin ich denen irgendwie schuldig, ein Minimum an Sicherheit zu bieten.

- Yoast halte ich für sehr sinnvoll. Die Mehrzahl unser Besucher kommt über Google, Yoast ist eine große Hilfe, die Seite richtig aufzubereiten für die Suchergebnisse
![grafik](https://user-images.githubusercontent.com/6114076/44702084-e5f7c400-aa91-11e8-8be4-322228cff7ec.png)
70% unserer Nutzer sind neue Nutzer

- Fastest Cache kann für die Entwicklung deaktiviert werden. Das ist richtig.

**Comment by joergsteinhauer** [comment]
Ok, ich wollte erstmal wissen, ob das alles Sinn macht. Aber so wie du es beschreibst, macht es auch Sinn. Die Details waren mir ja nicht bekannt.

Ich gehe an die Sache mit Plugins immer mit Bedacht ran, vor allem was die Performance angeht. Als Vergleich haben wir ja jetzt die aktuelle ZR Seite und reiki-lernen.de - zweitere ist um Welten schneller und fühlt sich leichter an. Vielen, was die aktuelle Seite abbremst, ist auf das unschöne Theme zurück zu führen. Aber eben auch Plugins spielen große Rolle. 
Zur Zeit ist die neue Seite ja noch schnell genug. Aber spätestens wenn man merkt, dass die Seite unangenehm langsam wird, muss man überlegen hier und da Plugins zu deaktivieren. Aber sehen wir eben dann, wenns soweit ist. 
Wichtig wäre evtl. immer mal wieder zu schauen, ob die Seite in die Knie geht.

**Comment by springers54** [comment]
gut, so machen wir das. Alternativ kann man auch Plugins nur aktivieren, wenn man sie nutzt, wie das SEO-Zeug.
Wir haben mit dem Umzug der schlechten Seite zu AllInk schon sehr viel gewonnen an Performance. Das war definitiv ein guter Tipp von dir. Die Server dort sind wesentlich schneller und alles funktioniert gut. Ich bin sehr zufrieden, dass wir das gemacht haben. Und unter einem Server verschiedene Accounts zu haben und eigenständige Installationen zum Testen erleichtert uns die Arbeit auch.

Im Moment probiere ich gerade, das Forum umzuziehen, so dass wir das hier testen und stylen können und auch wissen, wie es im Ernstfall funktioniert. Das mache ich alles auf der Energieshop-Seite und wenn ich das Verfahren sicher verstehe, dann würde ich es auf dem reiki-lernen-Server machen.
