### ISSUE TITLE
Die neue Homepage ohne Cherry

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#122]
Du schreibst:
welchen Stand hast du das letzte mal denn gesehen? Der aktuelle Stand ist so, dass das grundlegende Layout an sich fast finalisiert ist. Es fehlen aber noch eine Sachen, die dann im content Bereich auftauchen.
Da wollte ich dich bitten, ein paar Beispiel-Seiten anzulegen mit "echtem" Inhalt - also analog zu jetziger ZR Seite. Am besten wäre ein paar Unterseiten, die alle möglichen Elemente enthalten.

Ich sehe:
![grafik](https://user-images.githubusercontent.com/6114076/44506371-72774080-a6a6-11e8-9c8b-7caf7a849d97.png)

Sehe ich komplett etwas Falsches? 
Also ich dachte, dass die eigentliche Homepage erst einmal so aussieht wie die alte, das war ja das Ziel.
Ich sehen auch noch keine Verwaltungsmöglichkeiten, weder für das Team noch für die anderen Rubriken auf der Seite.

Das Team ist ja ein eigender Baustein, der es immer wieder erlaubt, neue Mitglieder aufzunehmen und der auch jetzt schon auf mehreren Seiten verwendet wird.

Ist dann wirklich die Zielstellung, dass ich alles komplett nochmal neu erstellen muss? Ist es nicht möglich, alte Seiten zu übernehmen und dann nur zu bearbeiten, dass das Cherry-Kram rauskommt, falls welches verwendet wurde?

Im Moment ist mir hier noch sehr viel unklar.
Wo sehe ich den aktuellen Stand?

**Comment by springers54** [comment]
wie wäre es, wenn wir die Datenbank aus zen-reiki.de exportieren und hier importieren? Dann haben wir zumindest alle Seiten, Nutzer, Forum usw. Und dann sehen wir genau, was ohne Cherry noch funktioniert und was nicht?

**Comment by joergsteinhauer** [comment]
Du siehst ales korrekt. Die "neue" Seite sieht ja auch wie die "alte". Zumindest die Haupt-Elemente, wie ich bereits sagte.

Dabei geht es NUR um das Template - ohne jeglichen Extra-Zeug, was über Cherry-Template kam, z.b. sowas wie Verwaltungsmöglichkeiten und andere eigene Bausteine.
Übrigens muss ich mich erst selber mit diesen "Bausteinen" beschäftigen, ich habe mit sowas noch nie als Entwickler zu tun und habs sowas selber nur genutzt, aber nicht implementiert/entwickelt. 

Vlt. war das bis jetzt nicht klar - aber als ich sagte, wir gestalten das Theme neu - meinte ich wirklich nur das Theme, so wie es in einer "nackten" WP Installation gliefert wird - ohne jeglichen Extra-Zeug (wie schon oben erwähnt).

Der erste Schritt ist: Entwickeln und gestalten eines Themes. 
Nächster Schritt: Einsetzen von Extra-Plugins / Bausteinen etc. Sowas wie "Verwaltungsmöglichkeiten" sind nicht Bestandteil eines Themes.

Cherry-Kram steckt zu tief im Template - wir sollten Cherry einfach vergessen, das bringt nix. 
Wenn wir Seiten übernehmen, dann eben auf der Datenbank-Ebene. Ich sage aber gleich, dass DB manchmal tricky sind - vor allem beim import/export. Da sollte man sich da schon etwas auskennen - ich tue das nicht wirklich. Wenn du oder jemand anders das übernehmen kann - gern. Könnt ihr gern probieren, wir schauen dann einfach was passiert. Mein neues Theme geht ja nicht verloren. Ich kann mir aber gut vorstellen, dass das ganze System kracht, weil in der alten DB Sachen drin sind, die auf Cherry-Sachen verweisen und wenn das neue Theme diese "Sachen" nicht bereit stellt, könnte es krachen.

Ich bin eher ein Theme-Entwickler/Designer, hab aber meine Grenzen was die WP-Core-Sachen angeht.

**Comment by springers54** [comment]
Hm. Dann haben wir unterschiedliche Vorstellungen. Das Theme, was ich verwende, hat eine Reihe von eigenen Post-Typen, dazu gehören Slider, Team, Service, Meinungen, FAQ, ...
Diese machen wichtige Inhaltsbausteine aus, ohne die sich die Seite nicht bauen lässt.
Ich wollte nicht auf diese Elemente verzichten, sondern auf das darunter liegende Cherry.
Ob nun jeder Spieleffekt am Enge geht, ist mir nicht so wichtig, aber die Startseiten sollte danach schon so aussehen, wie vorher und auch die Möglichkeiten, die Posttypen einzeln zu bedienen, also z,B, einen neuen Lehrer anzulegen im Team, der sich automatisch in dem Teamblock unterschiedlicher Seiten einblendet.
Das Exportieren der aktuellen Datenbank und das Importieren in die Testumgebung würde ich leisten können, da musste ich mich ja schon durchfitzen, als ich den Umzug gemacht habe. Was dann am Ende geht, weiß ich natürlich auch nicht. In den Seiten steckt ja an vielen Stellen Cherry-Code drin.

**Comment by joergsteinhauer** [comment]
Super, dann haben wir jetzt erstmal einen gemeinsamen Wissens-Stand.

Verstehe, die Post-Typen sind ja auch wichtig, keine Frage. Werde ich aber erst angehen, wenn das Theme an sich final ist. Oder eben gleichzeitig. Nur habe ich mich damit noch nie beschäftigt, muss mich also erstmal selber reinlesen und hoffe, dass ich da effektiv was machen kann. Am besten wir machen das dann in extra Issues.

**Comment by springers54** [comment]
Zum ersten Teil Team haben ich eine eigene Issue geschrieben. #123 
Die eigentliche Startseite besteht ja aus einer Reihe von Bausteinen und wenn wir die nicht haben und diese auch ohne das Cherry funktionieren, dann kommen wir nicht wirklich weiter.

Ich habe probiert, nur die Datenbank auf unseren Testserver zu übernehmen, das funktioniert leider überhaupt nicht. Man kann zwar das Wordpress einer Seite kopieren mit der Datenbank, aber die Datenbank nicht alleine.

Das ist natürlich ziemlich ägerlich, denn wir können nicht alles neu anlegen, schon gar nicht 9000 Nutzer.
Also wird nur bleiben, ein Plugin zu installieren, das dann auch Datenbanktabellen erstellt und dann die Daten einer einzelenen Tabelle zu importieren. Das können wir mal am Kontaktformular und dem Forum austesten, ob das geht und wie man dabei vorgehen muss.

**Comment by joergsteinhauer** [comment]
Richtig - du ahnst es schon und das habe ich im Issue #123 bereits beschrieben - vieles wurde mittels Cherry-Framework umgesetzt. Davon wollen wir uns ja entfernen, weils einfach Schrott ist. Allerdings müssen wir die Features jetzt nachbauen.

Ich sagte ja auch, dass es nicht einfach ist mit DB. Und meien Empfehlung ist es weiterhin, hier einen Menschen ranzulassen, der sich damit auskennt - also mit Datenbanken UND mit Wordpress. Ihm soll dann auch kalr sein, was wir am Ende wollen. 
Neu anlegen ist natürlich quatsch - viel mehr muss man die DB Einträge gekonnt kopieren. Entweder Tabelle für Tabelle oder anders, wie auch immer - ich kenne mich nur oberflächlich mit DB's aus - aber der Grundaufbau ist klar - es ist an sich wie eine Excel Tabelle mit Zelle, Zeilen und Spalten. Und diese müssen dann entsprechend in der neuen DB zu der aten identisch sein. Oder wenn die neue DB anders strukturiert ist, müssen die Spalten korrekt kopiert werden. Da ändert sich meist die Reihenfolge etc. Und sowas geht halt mit MySQL Befehlen. Hier kann ich aber nicht wirklich helfen.

**Comment by springers54** [comment]
ich habe hier ein bisschen was geschafft, die alten Nutzer sind da und ich weiß auch, wie ich zum Zeitpunkt x den Stand der Tabellen der Nutzer übertragen kann.
Gleiches gilt für das Forum. Wenn wir umziehen, müssen die Tabellen noch einmal übertragen werden, aber das sollte auch gehen.
