### ISSUE TITLE
Team als Teil der Seite

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#123]
- Für die neue Seite brauchen wir bestimmte Bausteine, einer davon ist das Team. Damit erstellt man neue Lehrer, die dann in allen Blöcken, wo das Team verwendet wird, gezeigt werden und man keine Wartungsarbeit auf meheren Seiten hat.
- Dabei handelt es sich um nichts anderes als Beiträge, allerdings des Typs `Team`.
- Der Menüeintrag im Admin-Menü lässt sich relativ einfach über das Plugin **Admin Menu Editor** https://de.wordpress.org/plugins/admin-menu-editor/ einfügen. Ähnlich sind wahrscheinlich auch andere non-default Wordpress Menüs umgesetzt
- schwierig wird es dann, diese Team-Beiträge mittels eines Shortcodes auf andere Seiten einzubinden. Auf der aktuellen ZR-Seite ist das ganze über den Cherry-Framework umgesetzt:
  - hier https://zen-reiki.de/wp-admin/admin.php?page=cherry-plugin-page sieht man alle Extra Sachen, die Cherry-Framework mitbringt, u.a. die Shortcodes: https://www.templatemonster.com/help/quick-start-guide/wordpress-themes/master/index_en.html#dynamic_shortcodes Genau das ist das Schwierige: ich muss erstmal schauen, wie ich eigene Beitrags-Typen erstellen kann usw. Da muss man dann schon im Theme auf PHP Ebene rumhaken.

Letztendlich wird ja folgendes Gebraucht: eine Möglichkeit, zentral neue Seiten/Beträge zu erstellen, die wiederum mit Inhalt versehen und die ganzen Seiten/Beträge dann als eine in sich geschlossene Einheit/Liste/Element auf anderen Seiten anzuzeigen.
Ich schätze, dass sich so ein Feature auch über andere(s) Plugin(s) umsetzten lässt - allerdings wollen wir ja nicht für jedes Feature Plugins verwenden - weil diese das ganze System einfach nur langsam machen (das sieht man auf der aktuellen ZR Seite) - sondern versuchen, die Features mit "Hausmitteln" umzusetzen.

So funktioniert das ganze auf der aktuelln ZR Seite:
![grafik](https://user-images.githubusercontent.com/6114076/44630253-ce69ef80-a95a-11e8-9366-09521b95145d.png)

https://zen-reiki.de/wp-admin/edit.php?post_type=team

Die Einbindung mittels Shortcode in der Seite ist dann so:
`[posts_grid type="team" columns="14" rows="1" order_by="date" order="DESC" thumb_width="170" thumb_height="127" meta="no" excerpt_count="0" link="yes" link_text="mehr..." custom_class="list_custom list_has_6_columns list_is_align_center"]`

**Comment by joergsteinhauer** [comment]
Nach einer umfangreichen Recherche zu dem ganzen "Wordpress-Bausteine" Thema habe ich deine initiale Beschreibung angepasst. Ich schätze, der ganze Ausmaß war auch dir nicht bekannt. Wie gesagt, vieles, was nicht zu der Standard-WP-Installation gehört, wurde auf der aktuellen ZR-Seite mittels Cherry-Framework gelöst. Dies gilt es jetzt nachzubauen oder alternativen zu finden.

**Comment by joergsteinhauer** [comment]
Nach weiterer Recherche würde sich dieser Plugin für das ganze Feature eignen:
https://de.wordpress.org/plugins/tlp-team/

Ich habe es installiert und ausprobiert:
http://reiki-lernen.de/seite-2/

Sieht für mich gut aus. Abgesehen vom fehlenden Styling passt der FRest ganz gut. Im Admin gibt es einen entsprechenden Menüeintrag, man kann die Lehrer einfach anlegen - ähnlich wie auf der aktuellen ZR-Seite - und auch gleich alle Infos eintragen. Am Ende hat man einen Shortcode, den man auf beliebigen Seiten einfügen kann. Die Liste besteht dann ebenfalls aus einzelnen Elementen (=Lehrer).

Der einzige Wermutstropfen - man müsste alle Lehrer auf der neuen Seite manuell neu eintragen.

Wäre das ein Kompromis?

**Comment by springers54** [comment]
ich weiß nicht, ob das wirklich der richtige Weg ist, jetzt keine individuellen Posttypen mehr zu nutzen, sondern für jedes ein Plugin zu nehmen. Jedes Plugin macht die Seite ebenso langsamer und undurchschaubarer, sehr viele beeinflussen sich gegenseitig.
Wäre es nicht der richtige Weg, sich den Aufbau der individuellen Post-Seiten im alten System anzuschauen und dann zu gucken, ob man das nachbauen kann? Selbst, wenn am Ende nicht jeder Cherry-Effekt möglich ist?

**Comment by joergsteinhauer** [comment]
Der Weg über Plugin wäre zumindest schnell und großen Aufwand. Ich bin generell auch gegen Plugins. 
Aber das ganze "händisch" umzusetzen wird schwierig sein - zumindest für mich. Und es wird länger dauern. 
Ich kann mich ab jetzt schlau machen, wie man sowas angehen könnte. Aber ich bin kein WP Entwickler, sondern Gestalter. Und unser Problem hier betrifft eher die Entwicklung.

**Comment by joergsteinhauer** [comment]
So, nach ein paar Std. Recherche und Entwicklung habe ich es ohne Plugins geschafft - es gibt nun einen Punkt "Lehrer" im Admin Menü, heir kann man Lehrer anlegen. Und dann mit dem Shortcode `[post-type-teacher]` auf jeder beliebigen Seite anzeigen. die Liste sieht man bereits hier (noch ungestylt): http://reiki-lernen.de/seite-2/

Ich denke, das ist genau das, was gebraucht wird. Die Namen für Admin Menü und shortcode kann ich noch anpassen.

**Comment by springers54** [comment]
Super, schaue ich mir an.

**Comment by joergsteinhauer** [comment]
Passt das so grundsätzlich? Also die Handhabung im Admin? Wenn ja, würde ich Styling fortsetzen.

**Comment by springers54** [comment]
ich habe mir das noch nicht anschauen können. War die letzte Zeit mit den Enkeln beschäftigt und habe nebenbei den Datenimport geklärt, was nicht ganz einfach war.
Im nächsten Schritt sollten wir erst mal probieren, die Medien umzuziehen, dann haben wir die Bilder, die wir brauchen.
@Dani2909 : probier doch bitte mal, deine alte Lehrerseite auf das neue Portal zu kopieren.

**Comment by springers54** [comment]
@joergsteinhauer : kannst du eventeull den Posttyp einfach team nennen? Dann könnte ich einen Import aus der alten Seite versuchen.

**Comment by joergsteinhauer** [comment]
Klar. Sonst andere Wünsche? Würde dann auch restliche Bezeicher analog von `teacher` zu `team` umbenennen.

**Comment by springers54** [comment]
es gibt einige spezielle Posttypen auf der Seite, Aber lass uns erst mal damit probieren, ob wir dann erfolgreich sind.

**Comment by springers54** [comment]
wenn ich im Moment schaue, heißt dei Posttype Lehrer, auf der alten Seite aber team
https://zen-reiki.de/wp-admin/edit.php?post_type=team
![grafik](https://user-images.githubusercontent.com/6114076/45028970-516c0380-b047-11e8-9b46-857badc9b8f8.png)


Ich nehme an, wenn die niicht 1:1 gleich sind, hat man keine Chance beim Import
Bei dir steht
http://reiki-lernen.de/wp-admin/edit.php?post_type=lehrer
![grafik](https://user-images.githubusercontent.com/6114076/45028837-ddc9f680-b046-11e8-8555-2aaabd4773d4.png)

**Comment by springers54** [comment]
Warte bitte erst einmal. Ich habe auf dem Testserver eine genze Menge importiert bekommen und würde das, wenn ich etwas Zeit habe, auch auf dem Entwicklungsserver machen.
![grafik](https://user-images.githubusercontent.com/6114076/45030043-e58b9a00-b04a-11e8-83fa-a0983a7d7383.png)
Dann sehen wir sehr gut, was alles nicht funktioniert, weil wir kein Cherry dahinter haben und können schrittweise arbeiten.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/45030554-8cbd0100-b04c-11e8-9a7a-20f3f9d80de7.png)
Also das Team kann er so niicht importieren, leider

**Comment by springers54** [comment]
Hier ist ein Link, wie man eine benutzerdefinierten Beitragstyp erstellt:
https://www.templatemonster.com/help/de/wordpress-create-custom-post-type.html

oder:
https://pressengers.de/tipps/wordpress-anpassen-custom-post-types-erstellen/

Es reicht wahrscheinlich nicht die Bezeichung in der Tabelle, sondern es muss ordentlich im Theme eingebunden sein.

**Comment by joergsteinhauer** [comment]
Ich habe den Posttype zu `team` umbenannt. Die benutzerdefinierten Beitragstypen hatte ich ja bereits erstellt gehabt, ist schon alles da. Schaue mal bitte ob das so passt. Auch Styling der Team-Listen habe ich angepasst.

**Comment by springers54** [comment]
super, großer Erfolg. Das hast du gut gemacht. Ich konnte die Seiten importieren und nun können wir mit den Feinarbeiten weitermachen.

**Comment by springers54** [comment]
Der Slug von Team sollte Lehrer heißen, da wir diesen Begriff ja auch in den Links nutzen. Ich weiß nicht,, wo das eingestellt wird.
Als nächstes wäre die Liste der Lehrer zu stylen, dort werden noch nicht alle angezeigt, Bilder fehlen auch noch.

**Comment by joergsteinhauer** [comment]
Habe soeben probiert den slug fix anzupassen, aber es hat nicht zum Erfolg geführt. Muss es mir genauer anschauen... ist alles auch für mich Neuland und muss mich aufwendig reinlesen.

**Comment by joergsteinhauer** [comment]
Kam per Mail von Sylvia:

> Slug ändern Link umbenennen
> 12.11.2016
> /usr/share/wordpress/wp-content/themes/theme54991/includes
> Datei theme-init.php
> Slug team-view in lehrer geändert
> Slug in my_Post_type_testi geändert in meinungen

**Comment by joergsteinhauer** [comment]
> Als nächstes wäre die Liste der Lehrer zu stylen, dort werden noch nicht alle angezeigt, Bilder fehlen auch noch.

Die Bilder in der Liste erscheinen dann, wenn man bei jedem Lehrer das "Beitragsbild" einstellt:
![grafik](https://user-images.githubusercontent.com/1843754/45293757-5a524e80-b4f9-11e8-8826-8a299e70284e.png)

Ich weiß, das ist jetzt anders als auf der alten Seite, aber so ist es zumindest bei der jetzigen Implementierung vorgesehen. Ich habe bereits versucht, es anders (wie auf der alten Seite) zu lösen, habes es aber nicht hingekriegt. Ist mir dann doch zu hoch.

Wie auch schon oft gesagt, die alte ZR Seite ist ziemlich komplex udn wir müssen nicht zwingend alle Details genau so umsetzen. Zum einen leidet die Performance, zum anderen versuche ich zumindest im neuen Theme alle Features auf einfachste Art und Weise umzusetzen.

Ich denke, es ist kein großer Aufwand, bei allen Lehrern die Beitragsbilder einzustellen. Außerdem sind die Beitragsbilder, soviel ich weiß, auch positiv für SEO.

**Comment by joergsteinhauer** [comment]
Jetzt ist auch das Beitragsbild in der Admin-Übersicht zu sehen

**Comment by joergsteinhauer** [comment]
Habe noch mal im alten ZR Theme nachgeschaut und versucht nachzuvollziehen, wie das dort funktioniert: so wie ich es verstanden habe, wird da als Lehrer-Bild (was sowohl in der Liste auftaucht als auch in der Admin-Übersicht) entweder das Beitragsbild genommen oder (wenns kein gibt) wird im ganzen Post nach Bildern gesucht und das erste Bild als Referenz genommen.
Kann man schon so machen, aber ist eher unsicher - wenn man versehentlich ein komisches Bild im Post ganz oben einfügt, erscheitn das dann an entsprechenden Stellen. 
Besser finde ich es, ganz klar und deutlich über das Beitragsbild zu regeln - wie jetzt im neuen Theme.

**Comment by springers54** [comment]
Ich habe überhaupt kein Problem damit. Im alten System hatte ich genau das Problem, wenn ich Beitragsbilder eingesetzt habe, dann waren das auch die Bilder, die am Anfang des Beitrags eingefügt waren und ich hatte keine Chance mehr, etwas zu formatieren oder Größen anzupassen.
Das scheint jetzt nicht der Fall zu sein. http://reiki-lernen.de/team/sylvia-springer/ Hier ist ein ganz anderes Bild als das Beitragsbild.

Wir brauchen also eine Regelung, wo das Beitragsbild verwendet wird und wie. Denn das Problem taucht auf vielen Seiten auf, bei Meinungen, bei Büchern und Beiträgen.

Eine einfache Regel könnte sein, dass das Beitragsbild immer dann im Beitrag eingefügt wird, wenn kein anderes Bild dort steht.
Das andere Problem mit den Referenzen ist mir auch schon auf die Füße gefallen, weil ich mal auf meine Seite ein Kontaktforumular hochgeladen habe und das dann als Vorschaubild gezeigt wurde. Und ich habe es nicht wieder wegbekommen.

Die Änderung der paar Lehrerseiten ist kein Problem. Generell müssen wir bei jeder Funktion der alten Seite überlegen, ob sie notwendig und sinnvoll ist und wie groß eine Änderung der Funktionalität für die bereits exisitierenden Seiten ist. Im Sinne einer Verbesserung sollten wir diesen Änderungsaufwand nicht scheuen.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/45496097-f5a32800-b774-11e8-95e0-fc7cfa27b416.png)

- [ ] Die Links kommen aber noch nicht richtig, diese müssten nur wieder Lehrer heiße und nicht team

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/45496507-e53f7d00-b775-11e8-8cae-e0b535c783ba.png)
 * [x] nächstes Problem sind zu lange Namen und damit Umbrechen. Früher stand da nur mehr... Das ist auch nicht so hilfreich. Vielleicht nehmen wir aber hier nur die Vornamen, oder wir können es selbst festlegen, wie der Name dargestellt wird, falls er zu lang ist?
 * [x] bitte es so einstellen, dass beim Klick auf das Bild das Bild in Großauflösung gezeigt wird, so wie es jetzt auch ist. Und beim Klick auf den Namen die Lehrerseite kommt.
 * [x] es fehlen Lehrer, mehr als 10 werden nicht angezeigt. Wir hatten zuvor 6 pro Zeile. es fehlt der Typ Ganzseite #132

**Comment by joergsteinhauer** [comment]
Die Boxen für Namen sind nun alle gleich groß und es werden max. zwei Zeilen dargestellt. Falls mehr Zeichen drin sind, werden diese abgeschnitten. Der Name wird aber ja weiterhin in voller länge als Title-Attribut angezeigt.

**Comment by joergsteinhauer** [comment]
Es wurden nur 10 Lehrer angezeigt, weil in WP Einstellungen die max. Anzahl an Blogeinträgen auf 10 gesetzt war:
![grafik](https://user-images.githubusercontent.com/1843754/45779904-9e152880-bc5c-11e8-9343-bf1b7b4f06da.png)

Anscheinend greift diese Einschränkung auch auf die Custom Page Types, die sind wohl auch vom Urtyp "(Blog)Eintrag". Habe es auf 20 hoch gesetzt.

**Comment by springers54** [comment]
Ich habe die Homepage auf das Ganzseitenformat gebracht. Dabei zeigt sich, dass sich die Bilder weiter vergrößern. Eigentlich auch zu groß sind. Es sollten schon jeweils 6 Lehrer in einer Zeile dargestellt werden.
![grafik](https://user-images.githubusercontent.com/6114076/45918910-da7b9b00-be8d-11e8-8061-50e25dfb99ce.png)

**Comment by joergsteinhauer** [comment]
Ja, die Lehrer liste war noch nicht für die Ganzseitenbreite optimiert, mache ich.

**Comment by springers54** [comment]
* [x] Bitte auch auf die Verlinkung achten. Beim Klick auf das Bild sollte das Bild in einer Vorschaubox erscheinen
 * [x] Beim Klick auf den Namen des Lehrers sollte die Lehrerseite erscheinen.
 * [x] Du hast die Schriften verkleinert, damit der Name hinpasst gegenüber der alten Seite, Ist das wirklich der Weg? Vielleicht bleiben wir nur beim Vornamen und machen dann die Schriften wieder etwas größer?

**Comment by joergsteinhauer** [comment]
Habe jetzt sehr lange rumgedoktort... Mir ist ein Problem aufgefallen: da ich in der Liste auf die "Beitragsbilder" zugreife, habe ich immer nur das eine festgelegte Bild Zugriff. Und das ist meist ein relativ groß aufgelöstes Bild (z.b. 800x600). Nun werden diese großen Bilder als Vorschauen dargestellt. Problem: die Bilder sind zu überdimensioniert, man lädt quasi große Bilder, wobei an dieser Stelle auch kleinere ausreichen würden. Aber ich habe ja nur das eine Bild... d.h. es werden an sich zu viele unnötige Daten geladen, das ist vor allem auf mobilen Geräten kritisch. 
Aber ich habe noch keine Lösung dafür gefunden, bleibt erstmal so.
 
Link auf Bild/Unterseite entsprechend mit Lightbox war kein Problem.
Auch Schriftgröße habe ich überall gleich groß gemacht, die Namen passen z.z. noch gut rein. Ich kann leider nicht nur den Vornamen nehmen, da ich nur auf die Seiten-Titel  zugreifen kann. Und dort steht ja der komplette Name. Es kann halt nun vorkommen, dass zu lange Namen nicht komplett reinpassen (je nach Bildschirmbreite). Die Namen werden dann einfach abgeschnitten.

**Comment by joergsteinhauer** [comment]
Soweit ich überblicken kann, ist heir nur noch eine Sache offen: die "slug" für die Lehrerseiten. Ich war schon mal dran, habs noch nicht hinbekommen. Scheint ein größeres Problem zu sein. Ich würde gern erstmal andere Sachen, die einfacher sind, umsetzen.

**Comment by springers54** [comment]
Wäre es einfacher, den Post-Typ einfach Lehrer zu nennn und nicht Team? Hat man dann das Slug-Problem gelöst? Ansonsten zurückstellen, denn es heißt für mich nur, bei neuen Lehrern den Link manuell zu bearbeiten. Das sollte kein Problem sein.
 * [ ] offen ist für mich das Problem mit der Bildgröße. Welche Bildgröße sollen wir einbauen? Wie ist es mit den kleinen Bildern auf der Startseite? Wenn du da bereits die großen Bilder lädst, dann haben wir wirklich ein Problem, weil uns das um die Ohren fliegt. Dann brauchen wir eine andere Lösung.

Mit dem Umbenennen ging der Import nicht, jetzt fällt es mir wieder ein. Dann lassen wir es lieber so, ich denke, der Slug ist eher unwichtig, da können wir uns mit beschäfitigen, wenn die anderen Dinge gelöst sind.

**Comment by joergsteinhauer** [comment]
Slug Problem: Habe nochmal probiert, ich kriegs nicht hin. Müsste mich Std. mit der ganzen Materie auseinandersetzen, das ist hier nicht so gut. Da sind meine PHP Kentnisse nicht so ausgereift, das wird. evtl. am Ende doch nichts. 
Es sei denn, du schaltest hier den Arun mit ein?
An sonsten: ändere dann doch lieber alle Links auf "Team".

-----------------

Das Problem mit der Bidlergröße gehe ich später an, es ist ja z.z. nicht kaputt, es werden halt relativ große Bilder geladen.
Beste Lösugn wäre: man hat mehrere Versionen eines Bildes. So is es z.b. der Fall, wenn man das Bild über Mediathek hochlädt - WP generiert dann ja mehrere Versionen (klein, mittel, große etc). hier müsste ich irgendwie die Bilder anzapfen und für meine Zwecke verwenden müssen. Das ist die große Aufgabe. Ähnlich wurde das im alten theme gelöst, wobei dort eben das erste Bild im Artikel genommen wurde. Vlt. doch keine schlechte Idee.

Zur Zeit mache ich es ja anders - über das Beitragsbild und das ist imemr nur ein Bild. Suboptimal.

Ich vermute, dass ich mit diesem Problem länger beschäftigt sein werde. 
Meine Empfehlung: entweder wir lassen es erstmal so wie es ist und verwenden gut komprimierte Bilder, die ausreichend groß für Zoom-Bild sind und nicht zu groß für die keinen Vorschauen. Ich könnte hier die Bilde auch selber komprimieren und ggf. eine keine Anleitung schreiben, wie man die Bilder zukünftig selber optimieren kann.
ODER: du schaltest Arun oder einen anderen erfahrenen WP Entwickler ein, der das ganze nochmal optimiert.

**Comment by springers54** [comment]
* [ ] Problem Bildgröße Homepage Lehrerbilder
wir laden doch immer automatisch mehrere Versionen eines Bildes, wenn wir ein Bild über die Mediatheik hochladen. Schlag mir einen Weg vor, der funktioniert. Wir können das erste Bild auf der Seite als Vorschaubild nehmen, aber dann eben auf der Homepage auch in einer kleineren Auflösung laden und die Verlinkung so wählen, dass als Light-Box-Bild ein größeres Bild angezeigt wird.

Warum muss ich die Links auf Team ändern? Der Slug ist doch nur etwas Internes und wird dann verwendet, wenn ich einen neuen Lehrer anlege? Dort würde der Link dann mit team vorgeschlagen, ließe sich doch aber auch auf Lehrer ändern? Bei den Links würde ich gern dabei bleiben, weil die inzwischen eingeprägt sind und auch im Google-Index vorhanden.

**Comment by joergsteinhauer** [comment]
Nochmal:

1. Lehrerbilder: wir reden vom Selben. 
Ja, es werden authomatisch mehrere Versionen eines bilder generiert, wenn man ein bild in die Mediathek hochlädt. 
Ja, ein miglicher Weg wäre, das erste Bild des Artikels zu nehmen. Allerdings werde ich hier mehr Zeit für die Entwicklung brauchen. Daher meine Frage: kann heir nicht ein erfahrener WP Entwickler aushelfen?

2. Slug:
Ich zitiere jetzt deine Aussage:
`Ansonsten zurückstellen, denn es heißt für mich nur, bei neuen Lehrern den Link manuell zu bearbeiten. Das sollte kein Problem sein.`
Ich dachte hier, wir können das Problem lösen, in dem wir alles so lassen, wie es z.z. ist und du änderst ein paar Links?

**Comment by joergsteinhauer** [comment]
Eine mögliche Variante beim Problem der Lehrerbilder könnte, wie Sylvia bereits im https://github.com/springers54/reiki/issues/147#issuecomment-428069204 beschrieben hat, folgende sein:

Die kleinen Vorschau-Bilder werden mehr oder weniger statisch im Template/shortcode verbaut. wäre zumindest fürs erste eine Lösung, bevor ich oder jemand anders an eine komplett dynamische Lösung ran macht.

**Comment by springers54** [comment]
Hier nochmal einige Dinge, die uns aufgefallen sind:
https://www.i-talk24.net/msg/63cd908
 * [ ] Abstände auf der Homeseite und Zwischenräume

Ich mache dazu eine neue Issue auf, was das Scrollen von Wir sind anders angeht. #169
