### ISSUE TITLE
FAQ als eigenständiger Posttyp

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#128]
bitte hierfür auch einen erstellen und mit in die Verwaltung aufnehmen:
![grafik](https://user-images.githubusercontent.com/6114076/45103358-05e15480-b130-11e8-89ae-71955cd5c045.png)

**Comment by joergsteinhauer** [comment]
Sollte ereldgit worden sein.

**Comment by springers54** [comment]
ok, importieren konnte ich den auch, aber wie ruft man den auf? Bitte entweder einheitliches Schema verwenden oder hier in den Issues schreiben, sonst können wir nichts testen. Also analog zum Team ging es schon mal nicht.
![grafik](https://user-images.githubusercontent.com/6114076/45535658-8c1c2b80-b7ff-11e8-805c-ff56d9e1664c.png)

**Comment by springers54** [comment]
* [ ] Styling bitte anpassen, dass es der alten Seite entspricht. https://zen-reiki.de/faqs/
 * [ ] Wir zeigen im alten Portal generell die H1-Überschrift, also den Seitentitel nicht an. Dadurch ist das Styling ruhiger.
![grafik](https://user-images.githubusercontent.com/6114076/45535899-3300c780-b800-11e8-91a6-df9d45138819.png)

in der jetzigen Gestaltung zerbricht die H1 den Halt des Bildes an die obere Seitenleiste
![grafik](https://user-images.githubusercontent.com/6114076/45535981-64799300-b800-11e8-9fa1-1aa7546bb0cd.png)

**Comment by joergsteinhauer** [comment]
Jetzt funktioniert es wie bei den Teams, entsprechend über Shortcode `[post-type-faq]`.

Ich habe geschaut, wie das ganze im alten Theme umgesetzt war und bin der Meinung, dass ich im neuen Theme einiges einsparen konnte. Im alten Theme funktionierte das ganze nicht über einen Posttype/Shortcode, sondern über eine eigene Custom-Page (ähnlich wie "Fullpage") - was zwar an sich ok ist, aber zuviel Overhead darstellt. So ist im alten Theme das ganze dann noch hintenrum mit dem Motopress-Content-Editor Plugin verbunden, was zumindest für diesen Zweck völlig übertrieben ist.

Styling ist nun etwas anders, als au fder alten Seite - wäre das OK? Das Aussehen ist schlicht und einfach an bereits bestehende globale Text-Stylings gebunden:
- Titel sind groß und als solche erkennbar (h2 - was auch hierarchisch korrekt ist), nicht orange (warum ist das auf der alten Seite überhaupt orange? Ist doch kein Link! Man verwechselt die Titel mit einem Link, total verwirrend.)
- Abstände sind etwas großzügiger
- es gibt keine "F?" und "A" - zum einen ist die Aufteilung durch klare Formatierung klar genug und zum anderen: "weniger ist mehr". Es ist übrigens eines der wichtigsten gestalterischen Grundsätze - nicht zu viele unterschiedliche Schriftschnitte/arte/größen verwenden - auf der alten Seite gibts einfach zu viele unterschiedlich gestylte Texte - da sieht man wieder wie schlecht es umgesetzt ist.
- was macht dieses "Mehr lesen" Button da? Das ist hart im Artikel eingefügt und dann noch rechtsbündig? Sieht nicht gut aus. Warum nur bei diesem Artikel? Reicht da nicht ein einfacher Link?

Zu H1: 
Wenn die H1 auf allen Seiten nicht sichtbar sein soll, kann ich es so mit CSS machen. Finde es aber grundsätzlich falsch. Man sollte solche wichtigen Sachen nicht verstecken. Warum? User will doch wissen wo er gerade ist! Wenn das einzige Problem ist, dass der Titel oben mit der Sidebar nicht bündig abschließt, kann man es doch anders lösen - da stellt man die H1 über den Content und Sidebar o.ä. Und: haben enn alle Seiten ein Bild ganz oben?

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/45732488-db39d600-bbdc-11e8-8d66-2d3f5f5e5997.png)
So richtig toll finde ich es noch nicht. Ich kann deiner Argumentation teilweise folgen, aber das FAQ oben macht keinen Sinn, da das Bild es viel besser ausdrückt. Die H2 ist logisch richtig, empfinde ich aber als viel zu groß für die Fragen.


>     * was macht dieses "Mehr lesen" Button da? Das ist hart im Artikel eingefügt und dann noch rechtsbündig? Sieht nicht gut aus. Warum nur bei diesem Artikel? Reicht da nicht ein einfacher Link?

Ich fand das schön. Button sollen generell techtsbündig sein, bitte überall so umsetzen. Den Mehr Lesen Button gibt es auf vielen Seiten.

Auf das F und A kann ich verzichten.
Die H1 brauchen wir auf der Homepage audh nciht, weil da oben die Slider sind. diese schleißen an den Bildrand des Banners an.
Ich fand sie auf allen Themenseiten falsch, wo wir oben ein Bild haben.
![grafik](https://user-images.githubusercontent.com/6114076/45732646-919dbb00-bbdd-11e8-96e8-0faf01a227d2.png)
Siehe hier, sieht total blöd aus
 
![grafik](https://user-images.githubusercontent.com/6114076/45732702-cdd11b80-bbdd-11e8-8239-35411ed78177.png)
hier haut das nicht mal im Ansatz hin, denn es müsste eigentlich so aussehen
![grafik](https://user-images.githubusercontent.com/6114076/45732724-e93c2680-bbdd-11e8-9ede-c9a2e80a9f6e.png)

Aber dazu später, sind wieder eigenständige Probleme.

 * [x] Also generell keine H1 vor einem Bannerbild der Seite anzeigen.
 * [x] Buttons generell rechtsbündig

**Comment by joergsteinhauer** [comment]
Zu H1: es ist nicht möglich, nur mit CSS die H1 nur dann auszublenden, wenn diese VOR einem Bild steht. Das würde nur mit Overhead gehen.
Aleerdings habe ich geschaut, wie es im alten Theme umgesetzt wurde - da wurde die H1 einfach komplett auf allen Seiten per CSS ausgeblendet - das gleiche habe ich jetzt auch im neuen Theme gemacht. 
Sollte so ok sein und funktionieren. Falls doch irgendwo Probleme entstehen, bitte Bescheid geben, da muss ich es anders lösen.

**Comment by joergsteinhauer** [comment]
Buttons:
Welche Buttons, die orangenen? Also wirklich alle Buttons, in akllen Formularen etc?
Ich habe ein paar Seiten durchgeklickt, fand aber nur ein paar in Formularen. 
Bitte erstmal auflisten (mit URL's) wo die Buttons überall auftauchen, dann kann ich eine Logik dazu entwickeln.

Auf der FAQ Seite ist z.b. dieser eine "Mehr lesen" button mit inline-CSS rechtsbündig ausgerichtet.
Das ist an sich ziemlich blöd, denn inline CSS setzt mein globales CSS außer Kraft. Das kann man zwar so machen, aber dann muss man sich dessen bewusst sein und wissen, welche Auswirkung es hat.
Also falls ich eine globale CSS Regel für das rechtsbündige Ausrichten der Buttons erstelle, sollte das inline CSS vorsichtshalber entfert werden. Leider sehe ich hier und da inline CSS - das sollten wir nach und nach ausmerzen und CSS nur über globale CSS-files verwenden.

**Comment by springers54** [comment]
Wir haben im Moment nur die Kontaktformulare. Mehr Lesen-Button gibt es auf den verschiedenen Seiten, auch auf meiner Lehrerseite. https://reiki-lernen.de/team/sylvia-springer/, mit Mein-Reiki-Weg.
Dies sind eigentlich Links auf andere Seiten die auf diese Weise hervorgehoben wurden. Vielelicht kann man das auch anders stylen?

Generell wurden die Mehr LesenButton auf den Themenseiten genommen.
![grafik](https://user-images.githubusercontent.com/6114076/45893415-70022680-bdcb-11e8-809b-b05857ce714e.png)

Das Problem haben wir noch nicht mal im Ansatz im Griff, da wir im neuen System noch nicht mit Kurfassungen arbeiten können, sondern einfach die kompletten Beiträge anzeigen. Dies muss in einer eigenen Issue angegangen werden.

**Comment by joergsteinhauer** [comment]
Ich nehme an es geht um folgende Seite zb.? https://reiki-lernen.de/category/coaching/
Bitte immer URLs angeben.

Ja, scheint noch nicht zu gehen, gehen wir im extra Issue an.
@springers54 bitte entsprechend ein neues Issue anlegen und dieses hier ggf. schließen, wenn hier keiner weiteren Punkte offen sind.

**Comment by springers54** [comment]
https://reiki-lernen.de/wp-admin/term.php?taxonomy=category&tag_ID=76&post_type=post

https://zen-reiki.de/wp-admin/term.php?taxonomy=category&tag_ID=76&post_type=post

Die Links zu den Kategorien sehen gleich aus, trotzdem heißt es auf der alten Seite im Link Themen
https://zen-reiki.de/themen/coaching/
und auf der neuen leider nur 
https://reiki-lernen.de/category/coaching/

 * [ ] Bitte die Bezeichung so anpassen, dass anstelle von category das Wort themen im Link steht.

**Comment by springers54** [comment]
habe ich irgendwie hinbekommen
