### ISSUE TITLE
Menüs sind  nicht bearbeitebar

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#129]
Ich habe einen Teil des Inhaltes von der alten Seiten importiert und dabei festgestellt, dass ich keine Zugriff auf die Menüs habe. In da Header-Menü sind alle neuen Seiten aufgenommen werden. Im Admin ist das Header-Menü aber komplett leer. Bitte stelle es so ein, dass das Header, Extra und Footer-Menü im Adminbereich berarbeitbar sind.
![grafik](https://user-images.githubusercontent.com/6114076/45105234-15629c80-b134-11e8-80d6-5bda3bbaa908.png)

**Comment by joergsteinhauer** [comment]
Das habe ich mit Entsetzen gerade auch gesehen... Irgendwie hat der Import aus der alten Seite so einiges Zerschossen. Ich muss erstmal selber klar kommen, was hier schief läuft.

Ich glaube, ich brauche Zugriff auf die Datenbank. Schicke mri bitte die Zugangsdaten per Email.

Könnte dauern, sieht nicht nach einer trivialen Sache aus, zumal ich mich im WP-Backend nicht wirklich auskenne...

**Comment by springers54** [comment]
Ich denke, es liegt nicht am Import, sofern am Theme und den Veränderungen. Vielleicht kannst du dein Menü löschen? Dann können wir das Header Menü einsetzen. 
Bei Shop hat alles funktioniert, da hatte ich nach den gleichen Importen Zugriff auf die Menüs.
Also wichtig, dass ich alle 3Menüs nutzen und anpasse  kann für später.

Übrigens sind immer Bearbeiten Zeichen auf den Seiten, wie ein rotes Edit Feld oder blaue Bleistifte an den Menüs. Mach die bitte weg. 
Ich muss als Admin die Seite so seheh, wie sie wirklich ist. Für das Bearbeiten ist die Adminleiste ganz oben ausreichend.
![grafik](https://user-images.githubusercontent.com/6114076/45226309-ceed7900-b2be-11e8-83f0-fe40c1212b07.png)

**Comment by springers54** [comment]
ich komme leider mit den Menüs nicht weiter, kann auch das Footer-Menü nicht bearbeiten.

**Comment by joergsteinhauer** [comment]
Ich muss es ja auch erstmal im Theme im PHP anpassen. Da scheint etwas nicht korrekt zu sein.

**Comment by springers54** [comment]
ich habe gerade mal probiert, das Theme umzustellen. Wenn man das macht, kann man das Menü löschen und neu anlegen. Aber leider nicht, wenn man auf dein Theme zurückgeht. Da muss im Theme selbst ein Bug sein.

**Comment by joergsteinhauer** [comment]
Ja, eben. Mein Theme ist doch noch lange nicht final, es ist noch voll "work in progress". Es wird noch einige Bugs geben.
Ich wiederhole nochmal, dass ich kein Fullstack Wordpress Entwickler bin, sondrn eher visueller Entwickler. Einige Sachen kenne ich nicht und muss mich selber einarbeiten. 

Step by Step. bin gerade eben dabei den Fehler zu suchen.

**Comment by joergsteinhauer** [comment]
Habe die Menüs gefixt. Der Teufel war im Detail bzw. auch im PHP Spaghetti-Code, den ich nun mal nicht ganz verstehe.

Edit-Buttons im Admin sind nun auch versteckt.

**Comment by springers54** [comment]
Leider funktioniert das nicht richtig. Nachdem ich mühsam das Menü neu erstellt habe
![grafik](https://user-images.githubusercontent.com/6114076/45256695-64aa0680-b39a-11e8-893e-c01e53c81223.png)
war keine Unterstruktur von Menüpunkten möglich. Vermute, dass die Ebenen bei dir noch nicht funktionieren.
![grafik](https://user-images.githubusercontent.com/6114076/45256706-86a38900-b39a-11e8-9402-81efedea184f.png)

**Comment by joergsteinhauer** [comment]
Da hat sich das Markup des Menüs etwas geändert - warum auch immer. Gabs einen WP-Update? Sowas könnte nur bei einem kompletten CMS Update kommen.
Habe es angepasst.

Bitte darauf achten, dass die Menüs nicht zu voll werden - sonst sieht man auf mobilen Geräten nicht alle Punkte:
![grafik](https://user-images.githubusercontent.com/1843754/45263888-9e2e5080-b432-11e8-9064-c7036b310bdf.png)

Auf Desktop haben Menüpunkte, die Untermenüs haben, einen Pfeil nach unten:
![grafik](https://user-images.githubusercontent.com/1843754/45263898-c027d300-b432-11e8-8b0c-272907f03365.png)

Sieht jetzt eher komisch aus, weil jeder Punkt Untermenüs hat... aber ich finde so ist die Usability besser.

**Comment by joergsteinhauer** [comment]
Was ist mit dem Extra-Menü? Wo soll das vorkommen? Wo sieht man das auf der alten ZR Seite?

**Comment by springers54** [comment]
Das Extra-Menü wird bei Zen-Reiki auch nicht verwendet, früher dachte ich immer, das wäre das auf der rechten Seite, aber das wird nur durch die Widgets gestaltet.

Nimm diese Zipfel bitte wieder weg. Das sieht nicht gut aus.
![grafik](https://user-images.githubusercontent.com/6114076/45264187-d042b100-b438-11e8-913d-40db885e9ca0.png)

Der Abstand der Menüpunkte erscheint mir zu groß. Hier das Original. Unsere Farbe wirkt auch freundlicher. Die Untermenüs sind nicht Kapitälchen.
![grafik](https://user-images.githubusercontent.com/6114076/45264194-f49e8d80-b438-11e8-9613-800e8585bb36.png)

Kann man die Menüs auf dem Handy so gestalten, dass man sie scrollen kann?

**Comment by springers54** [comment]
Wo ist der Menüpunkt Login/Logout geblieben? Den liefert eigentlich das Theme mit.
![grafik](https://user-images.githubusercontent.com/6114076/45264236-cd948b80-b439-11e8-9c54-5b34ee2b7342.png)

**Comment by joergsteinhauer** [comment]
Habe einiges angepasst, folgendes bleibt offen bzw. muss noch geklärt werden:

> Kann man die Menüs auf dem Handy so gestalten, dass man sie scrollen kann?

Nein bzw. könnte evtl. klappen (50/50), müsste ich aber einiges Umbauen - lohnt sich nicht wirklich.
Wir könnten auf mobile z.b. nur die Hauptpunkte anzeigen. Oder einige Unterpunkte ausblenden.

> Wo ist der Menüpunkt Login/Logout geblieben? Den liefert eigentlich das Theme mit.

Diesen Punkt gab es noch nie im neuen Theme. nein, das theme liefert es nicht. Das Theme habe ich ja selber mit entcikelt, da gab es diesen Punkt nicht. Habe es eben eingebaut, war (für mich) tricky. Ist auch gleich auf Deutsch. 

> Suche

Brauchen wir hier das Suchicon inkl. Suchfeld (rechts neben dem Menü) wie auf der alten ZR Seite?

------------------
Nochmal zum Thema "Custom Theme": Für alle meine selbst entwickelten WP Themes nutze ich die Vorlage von https://underscores.me/ - das ist ein "starter" Theme, welcher mit Grundsachen kommt und direkt dafür Gedacht ist, darauß eigene Themes zu entwickeln. Es gibt auch einige andere ähnliche Vorlagen.
Wie auch immer - d.h. dass einige Features ggf. nach implementiert werden müssen und dieses Theme hier rein gar nichts mit dem eug zu tun hat, worauf das alte ZR Theme basiert.

**Comment by springers54** [comment]
* [ ] Fußzeilenmenü sollte nicht mehrzeilig sein
![grafik](https://user-images.githubusercontent.com/6114076/45497835-02c21600-b779-11e8-8ac6-f82a67504420.png)
Zu deinen Fragen:


> Nein bzw. könnte evtl. klappen (50/50), müsste ich aber einiges Umbauen - lohnt sich nicht wirklich.
> Wir könnten auf mobile z.b. nur die Hauptpunkte anzeigen. Oder einige Unterpunkte ausblenden.

Ausblenden wäre nicht schlecht. Nur die Hauptpunkte ist etwas zu wenig. Aber alle Punkte brauchen wir mobil nicht.

> Brauchen wir hier das Suchicon inkl. Suchfeld (rechts neben dem Menü) wie auf der alten ZR Seite?

Nein, denke ich nicht. Das Suchfeld ist schon ok so. Problem haben wir dann nur bei der Ganzseite, weil man das Suchfeld dann auch nicht sehen würde. Wie machen wir es da? Die Ganzseite als Startseite finde ich schon sinnvoll und auch bei einigen Unterseiten

> Wie auch immer - d.h. dass einige Features ggf. nach implementiert werden müssen und dieses Theme hier rein gar nichts mit dem eug zu tun hat, worauf das alte ZR Theme basiert.

Bei dem, was ich jetzt sehe habe ich mich gefragt, ob wir nicht mit einen fertigen Theme besser gefahren wären, dass wichtige Elemente von unseren Problemen bietet aber ohne Cherry auskommt. Ich befürchte, dass uns das alles über den Kopf wächst. Egal, welche Seite ich aufmache, es ist überall etwas nachzuarbeiten.

**Comment by joergsteinhauer** [comment]
> Bei dem, was ich jetzt sehe habe ich mich gefragt, ob wir nicht mit einen fertigen Theme besser gefahren wären [...]

Sehe icht komplett anders. 
1. Hätten wir diesmal wieder ein fertiges Theme genommen, hätten wir trotzdem einige Sachen anpassen müssen. Negativ: man kennt das Theme nicht und fängt viele Baustellen an, bei denen man nicht weiß wie man sie lösen kann etc. Und: das neue Theme würde anders aussehen - was wäre dann? Würde man alles komplett umstylen? Oder so lassen wie es ist? Warum dann möchtest du im jetzigen neuen Theme das Aussehen möglichst genau an das alte Theme anpassen? Das ist auch so ein Thema, was ich immer wieder sehe - es heißt - "bitte anpassen an das alte Theme" - ich frage mich warum muss das unbedingt sein? Kleine Abweichungen sind doch ok, solange die Seite bedienbar bleibt und gut aussieht. Die User gewöhnen sich schnell daran, dass Sachen etwas anders aussehen. Aber das ist ein anderes Thema.
2. Ich sehe bis jetzt keine gravierenden Probleme, es wächst nichts über den Kopf. Vielmehr sehe ich eine normale Entwicklung eines maßgeschnittenes Themes.
3. Es gibt überall was nachzuarbeiten. Nein, ich sage es sogar nochmal gezielt anders: nicht "nachzuarbeiten", sondern "zu entwickeln". Das Theme ist noch lange nicht fertig, das habe ich doch schon mal gesagt und ist vollkommen normal :-). Das Theme entwickelt sich - wir passen es unseren Bedürfnisse an und zwar so, dass es nicht zu viel wird und das System performant bleibt. Das ist ja eines der Ziele - abgesehen vom ganzen Cherry-Mist, war die performance des Themes komplett im Keller.
Ja es gibt viele Baustellen - aber eigentlich war das doch klar? Die ganze Website ist so komplex, da muss man das Theme entsprechend anpassen. Cherry hat vieles geliefert, aber auch einfach zu viel, sodass es zu Problemen führte.

Insgesamt finde ich also weiterhin den angeschlagenen Weg optimal, da wir wissen, was wir entwickeln, keine "black holes" haben wo man nicht durchsieht und gezielt Sachen entwickeln. Step by Step - ich sehe is jetzt keine gravierenden ankommenden Schwierigkeiten - selbst mit meinen mangelnden Backend-PHP-Kentnissen. Und wenn es dahingehend Probleme auftauchen, holen wir uns eben hilfe von weiteren Entwicklern - Arun hat doch m.m.n. solide Arbeit geleistet.

**Comment by joergsteinhauer** [comment]
> Fußzeilenmenü sollte nicht mehrzeilig sein

Was genau meinst du? Ichs ehe im aktuellen Footer Menü nur "Impressum". Wenn man weitere Menü-Punkte einbindet, könnte das Menü tatsächlich mehrzeilig werden - heißt - die Wörter rutschen untereinander, wenn nicht genug Platz da ist. Normales responsives Verhalten.
Das "Zen-Reiki-Internetschule 2018" ist Copyright vermerk und ist nicht teil des Menüs.

> Ausblenden wäre nicht schlecht. Nur die Hauptpunkte ist etwas zu wenig. Aber alle Punkte brauchen wir mobil nicht.

Ok - welche Punkte sollte ich dann ausblenden? Achtung, das ist dann ncith dynamisch - heißt - wenn sich MEnüpunkte ändern, muss ich CSS anpassen. Hoffe das Menü bleibt so wie jetzt

> Nein, denke ich nicht. Das Suchfeld ist schon ok so. Problem haben wir dann nur bei der Ganzseite, weil man das Suchfeld dann auch nicht sehen würde. Wie machen wir es da? Die Ganzseite als Startseite finde ich schon sinnvoll und auch bei einigen Unterseiten

Super. Oft wird die Suiche im Footer verankert - finde ich immer ganz nett. Stört nicht, weils immer unten ist und ist auf jeder Seite verfügbar. Und da die Suche nicht sooo wichtig ist, ist sie unten gut angebracht.

**Comment by springers54** [comment]
Im jetzigen System ist die Fußzeile genau eine Zeile, am besten immer vergleichen, wenn du Dinge nicht verstehst, denn meine Aussagen beziehen sich auf die alte Seite.
Menüs müssen dynamisch und von mir selbst ohne Anpasssung von dir bearbeitbare sein. Also über die normale Wordpress Menüs Funktion.
Suche im Footer fände ich seltsam, kenne ich auch von anderen Seiten nicht. Dann eher im Header über den Menüpunkten.

Ich verstehe deine Argumentation schon bezüglich des Themes. Allerdings wird das alles sehr aufwändig und uns am Ende nicht übrig bleiben als beide Systeme parallel zu entwickeln und alle neuen Dinge auch im neuen System aufzunehmen.

**Comment by joergsteinhauer** [comment]
> Im jetzigen System ist die Fußzeile genau eine Zeile

Ok, sehe es jetzt. Finde es aber nicht gut - man sieht den Unterschied nicht zwischen den Footer-Links und Copyright-Text. Schlechte Usability. Was spricht dagegen, dass Copyright-Text drunter steht?

Das meine ich übrigens immer wieder - es wird versucht soviel wie möglich an das alte Theme anzugleichen, obwohl das alte Theme in vielen Hinsichten einfach schlecht umgesetzt ist.
Ich habe das neue Theme mit absicht etwas anders gemacht - sprich - aus Usability-sicht etwas verbessert. Kann ja auch sein, ich übersehe bestimmte Gegebenheiten. Bitte mich da gleich aufklären und argumentieren, warum was wie anders gemacht werden soll :-)

> Menüs müssen dynamisch und von mir selbst ohne Anpasssung von dir bearbeitbare sein. Also über die normale Wordpress Menüs Funktion.

Menüs bleiben ja auch weiterhin über Admin bearbeitbar. Einzig wird das Ausblenden einiger Punkte starr über CSS funktionieren. Das meine ich. Heißt, wenn du die Seiten-Namen und/oder Menüpunkte umbenennst, kann es vorkommen, dass dann auf einmal ein anderes Menü versteckt wird. Denn im HTML wird eine ID ausgegeben, diese ist an eine Seite gebunden.
Ich möchte das dich nur gleich wissen lassen.

> Suche im Footer fände ich seltsam, kenne ich auch von anderen Seiten nicht. Dann eher im Header über den Menüpunkten.

Ok, also seltsam ist es nicht, eher seltener als im Header. Aber trotzdem praktikabel:
https://goo.gl/r5vasY
Ich erstelle aber gern vorerst ein paar Vorschläge wie es aussehen könnte, bevor ich was umsetze

> Ich verstehe deine Argumentation schon bezüglich des Themes. Allerdings wird das alles sehr aufwändig und uns am Ende nicht übrig bleiben als beide Systeme parallel zu entwickeln und alle neuen Dinge auch im neuen System aufzunehmen.

Genau so habe ich es von Anfang an vermutet. Es ist einfach sehr komplex. Vlt. hätten wir gleich am anfang einen konkreteren Plan aufstellen müssen, wie was verlaufen könnte.

**Comment by springers54** [comment]
Bin im Moment unterwegs und kann nur eingeschränkt antworten.
Es spricht generell nichts gegen 2 Fußzeilen, aber ich wollte den Fußbereich schmal lassen.
Die zweite Zeile macht ihn höher.

Generell möchte ich möglichst das alte Erscheinungsbild behalten, es gefällt mir.
Nicht schon wieder Änderungen, die Lehrer haben sich mit dem letzten Wechsel schon extrem schwer getan.

Vielleicht ist es gut, dass wir das alles nicht vorher besprochen haben, vielleicht hätten wir dann nichts angefangen. Nun ist es so. Wir können nur schrittweisen vorgehen. Immer ein Problem nach dem anderen und aus jeder Sache, die fertig ist, lernen wir.

Die Ablösung von Cherry ist richtig. Dahinter stehe ich. Wir haben nur Buchteile gebraucht und das System ist total unübersichtlich.

**Comment by joergsteinhauer** [comment]
Ok, verstehe. Wenn die Lehrer sich damit schwer tun - dann ist es so und wir müssen reagieren bzw. entsprechend agieren. Ist auch kein Beinbruch.

Falls nur die höhe des Footer das PRoblem ist - kann man ihn woanders noch etwas kompakter gestalten. Ich würde aber weiterhin den Copyright auf extra Zeile darstellen. So ein Footer wird sowieso nur selten genau angeschaut und geklickt.

**Comment by springers54** [comment]
Ok. Ob nun eine oder 2Zeilen, ist nicht wichtig.
Mit der Suche in der Fusszeile habe ich eher ein Problem. Nehmen wir die Startseite, die ist schon extrem lang. Da geht der Footer unter, man kommt nicht darauf, dass man dort hinscrollen muss.
Da brauchen wir eine andere Lösung für die Ganzseiten.

**Comment by joergsteinhauer** [comment]
Jep, ich mache da einen Entwurf für die Suche im Header.

**Comment by joergsteinhauer** [comment]
Suche im Header wird in #138 umgesetzt.
