### ISSUE TITLE
Kontaktformulare als einfacher Seitentyp

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#130]
... vielleicht sollten wir hier beginnen.
Wir haben auf der alten Seite ein zweispaltiges Kontaktformular, das sollte wieder darstellbar sein.
![grafik](https://user-images.githubusercontent.com/6114076/45264261-16e4db00-b43a-11e8-89bc-ab0114fb8412.png)
Anstelle des Cherrys erst einmal ein Hintergrundbild in ein Div legen? Dafür müsstest du ein Styling vorgeben, weil solche Bilder an verschiedenen Stellen auftauchen.

Ich weiß nicht, wie aufwändig ein Parallaxeslider ist, den wir jetzt ja haben. Also wenn Seite nach unten gescrollt wird, dann, scrollt das Bild mit einer anderen Geschwindigkeit.

**Comment by joergsteinhauer** [comment]
Gleich vorab: bitte nur ein Thema in einem Ticket behandeln.
Ich sehe heir 3 Sachen:
1. Kontaktformular
2. Dynamische Hintergrundbilder (je nach Seite etc.) #131 
3. Paralaxslider

Ich gehe hier nur das erste Thema an: Kontaktformular. Sollte kein Problem sein.
Bitte für andere Sachen extra Ticket anlegen und vor allem die Sache mti dem Hintergrundbild genauer beschreiben.

**Comment by joergsteinhauer** [comment]
Formular ähnlich wie auf der alten Seite nun zweispaltig

**Comment by springers54** [comment]
* [x] können wir die Buttons zum Anklicken immer nach rechts setzen? Das ist in den meisten Systemen so und für mich nutzerfreundlicher.
 * [x] Im Moment sind die Beschriftungen so groß wie die Eingabefelder, Im alten System sind die etwas kleiner, sieht für mich besser aus.

**Comment by joergsteinhauer** [comment]
Alle Absende-buttons in CF7 Formularen sind nun rechtsbündig. Sollten wir weitere Fälle haben (außerhalb der CF7 Formulare), so bitte hinweisen, da mache ich es dann dort auch.
