### ISSUE TITLE
Hintergrundbild für Formulare

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#131]
Auf der alten Seite haben Formulare ein Hintergrundbild. Dieses hat noch einen Parallaxeslider, das bedeutet, es scrollt in einem eigenen Bereich. Wenn man die Seite nach unten scrollt, dann srollt das Bild ebenfalls nach unten aber in einer andren Geschwindigkeit.

Im ersten Schritt sollten wir erst einmal ein Hintergrundbild im Formular einbauen und das Styling der alten Seite annähern.
https://zen-reiki.de/kontaktformular/
http://reiki-lernen.de/kontaktformular/

**Comment by joergsteinhauer** [comment]
Soll das Bild möglichst im Admin konfigurierbar sein? Das wäre mehr Aufwand und ich wüsste erstmal nicht mal, wie und mit wieviel Aufwand das geht. 
Andere Variante wäre weniger dynamisch über CSS. 

Ich schaue, was sich wie machen lässt.

**Comment by springers54** [comment]
Es reicht, wenn es ein festes Bild aus der Mediathek ist. Im Moment isr es Kontakt4.
Was du mit im Admin konfigurierbar meinst, ist mir unklar.
Wenn man ein DIV um das Formular legt, kann man dort dich auch ein Bild reinpacken?

**Comment by joergsteinhauer** [comment]
Ok, gut so. Dann mache ich es lieber statisch über CSS.

Wie ichs meine: im WP Admin kann man u.a. solche Sachen, wie Header-Bild einstellen. Dies wird dann, je nach Theme Konfiguration, eben auf der Seite sichtbar. Ähnliches kann ich mir für andere Custom-Sachen vorstellen. Aber das ist zuviel Aufwand.

**Comment by springers54** [comment]
Je nach Theme muss sich  das nicht verändern. Es reicht css, so dass es eine Regel gibt, wie ich ein Bild hinter ein Formular lege und vielleicht auf der einen Seite Bild 1 und auf einer anderen Bild 2

**Comment by joergsteinhauer** [comment]
Gut, soweit umgesetzt. 
Alle Seiten haben einen Klassen-Slug im body-tag, also z.b. hat die Kontaktseite eine Zusatzklasse im body:
`<body class="[...] page-kontaktformular [...]">`
Anhand dieser Klasse wird im CSS das Hintergrundbild gesetzt. Falls also auf einer anderen Seite das gleiche oder andere Bild in gleicher Art und Weise angezeigt werden soll, muss man das im CSS regeln.

**Comment by springers54** [comment]
so richtig gut finde ich diese Lösung nicht, weil ich als Betreiber der Seite keine Möglichkeit habe, das Bild zu ändern. Es kann nicht sein, dass ich damit ins css muss.
Kann man nicht eine Stylingregel basteln, die ich im Quellcode sehe, wo ich selbst Einfluss auf Hintergrundbilder nehmen kann?

**Comment by springers54** [comment]
Vergleiche bitte mal beide Seiten und den Einbau der Bilder. Die neue Seite sieht einfach unschön aus.
Das Bild ist anders eingefasst, der schöne Scrolleffekt ist weg, die Felder sind weiß und nicht transparent vom Hintergrund
![grafik](https://user-images.githubusercontent.com/6114076/45892935-ed2c9c00-bdc9-11e8-9776-812c1020f940.png)

Alte Seite im Bildvergleich:
![grafik](https://user-images.githubusercontent.com/6114076/45892969-0897a700-bdca-11e8-96bb-2e4cbdf7db98.png)

Bekommt man so einen Scrolleffekt auch ohne Cherry hin?

**Comment by joergsteinhauer** [comment]
> Kann man nicht eine Stylingregel basteln [...]

Genau das habe ich doch anfangs gefragt. Du meintest, es reicht eine starre Lösung über CSS...
Gut, dann muss ich mir etwas dynamisches überlegen, wird schon irgendwie gehen müssen.

> Kontaktseite ...

- Das Bild ist bei mir auf HD Monitor fast genau so wie auf der alten Seite. 
- Felder transparent mache ich noch
- Parallax Effekt wird im extra Issue behaldelt, darüber haben wir doch schon gesprochen

**Comment by springers54** [comment]
ich habe dich dann wohl falsch verstanden. Mein Problem ist ja, dass ich selbst das Css nicht anpassen kann, da du das ja im LESS machst. Es würde mir prinzipiell reichen, wenn ich bestimmte css-Regeln wie auf der alten Seite modifizieren könnte und dann eventuell dort ein anderes Bild einfügen.

Aber es kann gut sein, dass wir auch noch andere Formulare bauen und dann das Hintergrundbild nicht passt.
Bei mir passt der Bildausschnitt nicht zu 100%, irgendwie ist oben jetzt mehr Rand zu sehen, als wenn da Medikamente drauf sind oder was das auch immer sein soll.

Die transparenten Felder, die Farben und die Schriften sollten der alten Seite entsprechen.

**Comment by joergsteinhauer** [comment]
Ok, das ist schon mal ein Anfang. Ich habe das dazugehörige CSS aus dem LESS in die Datei `custom.css` verschoben, hier kannst du gern nach belieben rumschreiben.
Wenn du auf anderen Seiten ein anderes Bild nehmen möchtest, musst du die bestehende Regel duplizieren und statt `.page-kontaktformular` entsprechend die passende Klasse einsetzen.

Eine anderweitige dynamische Lösung würde jetzt hier den Rahmen sprengen. So oft und durcheinander wird es ja nicht sein.

Bildausschnitt ist anders als auf der alten Seite u.a. durch die Höhe des Containers und vor allem durch das fehlende Parallax Effekt. Kann auch nicht sagen, ob mit Parallax dann das Bild haargenau den gleichen Ausschnitt hat. aber ist denn das so wichtig? Ich sage doch imemr wieder, dass es kleine Abweichungen ggü. dem alten Theme geben wird. Ist doch nicht schlimm, hauptsache das sieht stimmig und korrekt aus... habe das Gefühl wir verhaspeln uns auf solchen unwichtigen Details.

**Comment by springers54** [comment]
Super, das würde mir reichen. Habe ich mir angeschaut. Wenn ich dann noch wüsste, wie ich zum Beispiel für meine Lehrerseite ein anderes Bild nehmen könnte im Kontaktformular?

Oder im Anmeldeformular? Heißt dass dann .page-anmeldeformular?

Wir werden uns nicht in unwichtigen Details verhaspeln, ich tue mein Bestes. Kleine Abweichungen werden sein, das war vorher klar und macht nicht die Welt aus, da hast du vollkommen Recht.

**Comment by springers54** [comment]
https://reiki-lernen.de/anmeldeformular/
habe es jetzt mal probiert, aber so richtig funktioniert das nicht.
![grafik](https://user-images.githubusercontent.com/6114076/46057825-fca83e00-c157-11e8-88a6-109de259fc93.png)

ich möchte eigentlich davon ausgehen können, dass ich, wenn ich eine weitere Kontaktseite mache, das gleicht Styling habe?

Eine gewisse Parallaxe kann ich sehen, wobei man den Effekt noch etwas stärker machen könnte aus meiner Sicht. Die Felder sind aber hier nicht transparent, wie im Kontaktformular, Die Schriften haben eine andere Farbe..

Vorschlag: Neben der Fullwith-Page einen Seitentyp Kontaktformular machen, der die Basis des Stylings hat.
 * [x] Seitentyp?
 * [x] Felder transparent
 * [x] Schriften
 * [x] Button Farbe
 * [x] Abstände zum Menü
 * [x] Vergleich mit https://zen-reiki.de/kontaktformular/, bitte von  hier Styling übernehmen, was Schriften und Abstände angeht, sowie die Farben der Schriften

**Comment by joergsteinhauer** [comment]
- Problem neue Kontaktseiten: korrekt, das ist der richtige Weg - es gibt nun ein neues Template "Ganzseite mit Hintergrund und Parallax". 
Der Name ist selbsterklärend - die Seite hat alle Voraussetzungen für ein Hintergrundbild (Abstände, transparente Formulare etc.). Das Hintergrundbild selbst aber musst du weiterhin in der `custom.css` einstellen, das hat ja geklappt. Wobei ich es da noch optimiert habe. Das ganze ist jetzt noch flexibler. Z.z. ist das Bild für alle Seiten gesetzt, die das Template "Ganzseite mit Hintergrund und Parallax" haben. Falls du aber z.b. auf der Anmelde-Seite ein anderes Bild haben möchtest, musst du im CSS noch die body-Klasse ".page-kontaktformular" davor schalten.
```
.page-kontaktformular .has-background {
	background-image: url(img/bg-contact.jpg);
}
```
- Buttons sind grau, wenn sie inaktiv sind, d.h. wenn Voraussetzungen nicht erfüllt sind (z.b. nicht bestätigte AGB etc.)
- was meinst du mit "Abstände zum Menü"?

**Comment by springers54** [comment]
https://reiki-lernen.de/kontaktformular/
![grafik](https://user-images.githubusercontent.com/6114076/46124525-021f8a00-c225-11e8-9a35-1e8f027be46b.png)


>     * Buttons sind grau, wenn sie inaktiv sind, d.h. wenn Voraussetzungen nicht erfüllt sind (z.b. nicht bestätigte AGB etc.)

Das ist bei dem andenren Formular auch so, dass man es eigentlich nicht absenden können dürfte, da Pflichtfelder nicht ausgefüllt sind. Wenn es möglich ist, würde ich diesen Effekt lieber nicht haben, sondern einfach nur gelbe Button


>     * was meinst du mit "Abstände zum Menü"?

ist jetzt da, vorher klebte das Bild an der Menüleiste, jetzt ist ein weißer Abstand da.

**Comment by joergsteinhauer** [comment]
Ich bin da ganz anderer Ansicht, was inaktive Buttons angeht. Es doch nur verwirrend, wenn ein normaler Button keine Aktion auslöst - man denkt, da ist etwas kaputt. 
Rein aus Usability-sicht sollte der inaktive Button schon als solcher erkennbar sein. Ich kann zusätzlich noch den entsprechenden Mauscursor einstellen, aber grau wäre schon gut. 
Das ist auch eigentlich ein gebräuchlihes Pattern in UX/UI.

**Comment by springers54** [comment]
Du bist  der Gestalter. Aber es sollte dann einheitlich auf allen Seiten funktionieren. Wenn im Kontaktformular gelb und im Anmeldeformular grau, dann würde ich das als Nutzer nicht verstehen.

**Comment by joergsteinhauer** [comment]
Im Kontaktformular gibts keine Pflichtfelder, deswegen ist der Button orange.
Die Logik  bei Buttons ist korrekt, vielmehr müssen die Formulare an sich optimiert werden.
Z.b. müsste man noch klar ersichtlich machen, welche Felder pflicht sind - schaue ich mir noch an, das ist alles kein Problem, sobald der formular-Plugin da mitmacht.

**Comment by springers54** [comment]
Die Pflichtfelder haben ein *. Das ist die übliche Praxis
Man kann das Formular nicht absenden, wenn Pflichtfelder fehlen.

**Comment by joergsteinhauer** [comment]
Ok, ich habe gefunden, was dazu führte, dass das ganze Validierungsverhalten "getört" hat. 

Im Anmeldeformular gibt es Checkboxen, diese sind pflicht. Dabei validiert CF7 das Formular anders, wenn es Checkboxen enthält: zuerst werden normale Eingabefelder validiert, danach die Checkboxen. Solange die Pflicht-Checkboxen nicht angeklickt wurden, bleibt der Button inaktiv. Komplett anders also, als wenn man keinen Text in die Pflicht-Eingabefelder eintippt.
Nachzulesen: https://contactform7.com/acceptance-checkbox/

Zum Glück gibt es eine Einstellung, die das Validierungsverhalten bei Checkboxen genau so macht, wie bei Eingabefeldern. Was ich auch gemacht habe. 
Nun ist der button imemr orange, also NICHT inaktiv, wenn Pflichtfelder nicht ausgefüllt sind. Nun haben wir gleiches Verhalten überall.

**Comment by springers54** [comment]
Ich muss das .leider nochmal aufmachen.
Geh bitte auf die Seite der Kontaktformulare und scrolle die mal runter.
Die Felder laufen aus dem Bild. Es sollte hier auch so sein, dass nur das Bild scrollt, aber die Texte stehen bleiben.

https://reiki-lernen.de/kontaktformular/
https://reiki-lernen.de/anmeldeformular/

![grafik](https://user-images.githubusercontent.com/6114076/50386112-2c2bff80-06e1-11e9-9ef8-ec9c31e67420.png)

Weiterhin funktioniert hier die gelbe Schrift nicht mit p class="title-h6"

Im Sinne der einheitlichen Gestaltung wäre es gut, wenn die Überschrift H1 wie bei den anderen Seiten oben steht und nicht Teil des Hintergrundbildes ist, also diese bitte aus der Gestaltung rausziehen.

**Comment by joergsteinhauer** [comment]
Ja, das parallax Zeug scheint überall noch buggy zu sein. Rest sollte kein Problem werden.

**Comment by springers54** [comment]
Das Parallaxezeug sollte auch hier kompett weg.

- [x] Bitte die Seitenüberschrift aus dem Hintergrundbild nehmen

- [x] `<p class="title-h6">Kontakt zur Zen-Reiki-Internetschule</p>` ergab früher eine geelbe Farbe, die ist leider auch eg

**Comment by joergsteinhauer** [comment]
Was meinst du damit?

> Bitte die Seitenüberschrift aus dem Hintergrundbild nehmen

**Comment by springers54** [comment]
Auf allen Themen- Übersichtsseiten steht die H1 oben, dann kommt das Bild. Im Formular ist die H1 im Bild.

**Comment by springers54** [comment]
Ich habe jetzt mal etwas gebastelt:
![grafik](https://user-images.githubusercontent.com/6114076/50737051-33fda080-11c5-11e9-8296-7d71f3f9f6f7.png)

So würde es prinzipiell gehen, es stört nur, dass die Felder weiß sind und nicht halbtransparent, so dass man noch etwas vom Hintergrundbild sehen kann. Kannst du das noch umsetzen?

![grafik](https://user-images.githubusercontent.com/6114076/50737078-70310100-11c5-11e9-8709-c4ffb0872130.png)

Wenn du dafür vielleicht eine weitere Klasse machen könntest?
https://reiki-lernen.de/kontaktformular

**Comment by joergsteinhauer** [comment]
Ein Screenshot hilft immer besser... Aber nun weiß ich, was gemeint ist.

Ich löse das eher über ein Template, weil der Umbau im Content so doch nicht ganz sinnvoll ist und nur mit viel Arbeit und extra HTML verbunden ist.

**Comment by springers54** [comment]
Wir haben 2 Seiten, wo das Formular nach Außen gezeigt wird, das ist also kein Aufwand.
Außerdem haben wir hier die volle Gestaltungsmöglichkeit, könnten selbst jederzeit ein anderes Bild einsetzen.
Für mich ist nur das Problem zu lösen, dass die Felder nicht weiß, sondern halbtransparent sind.

> Ein Screenshot hilft immer besser... Aber nun weiß ich, was gemeint ist.

... verstehe ich nicht. Hatte ich doch geschickt.

**Comment by joergsteinhauer** [comment]
> ... verstehe ich nicht. Hatte ich doch geschickt.

ja, aber nicht gleich bei der Anforderung ;-) egal.

-------------------

Habe das Template "Ganzseite mit Hintergrund" nun soweit angepasst, dass alles passt: https://reiki-lernen.de/anmeldeformular/

Es ist nicht richtig, das Layout im Editor zu machen.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/50817350-d16ee680-1323-11e9-9834-957db2cca45f.png)
 
und jetzt deine Variante:
![grafik](https://user-images.githubusercontent.com/6114076/50817389-f1060f00-1323-11e9-80a5-628779f7b7b4.png)

Sorry, da gefällt mir die obere viel besser, die Schriften, die Größen, die Abstände, die Farben.
Also bitte nur die Felder halbtransparent und den Rest so lassen

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/50817584-98834180-1324-11e9-805a-3b1339f893c2.png)

Die Headings stimmen dann auch nicht

**Comment by joergsteinhauer** [comment]
Die Größen, Farben etc sind nicht das Prioblem, ide passe ich an. Viel mehr gings mir hier darum, das Layout-Zeug nicht in den Content zu verschieben. Außerdem geht in deiner Variante das Hintergrundbild nicht bis zum Rand - das sieht nun wirklich nicht gut aus. 
Ich mach mich noch mal ran, das sind Kleinigkeiten...

**Comment by springers54** [comment]
Ja, mit dem Rand hast du auf jeden Fall Recht.

**Comment by springers54** [comment]
Die Überschriften habe ich angepasst, die Größen und Farben musst du nochmal kontrollieren

**Comment by joergsteinhauer** [comment]
Habe es angepasst.

Die orange Überschrift hat un folgenden Markup:

`<p class="title-h6 has-style-primary">[...]</p>`

Die Klasse `has-style-primary` sorgt für die Farbe, diese Klasse kannst du übrigens nach belieben überall auf die H-Titel oder auf alle Elemente, die bereits eine Klasse `title-h[...]` haben, setzen - falls du die Titel in orange haben möchtest.
