### ISSUE TITLE
Ganzseite erlauben

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#132]
In der alten Seite haben wir die Möglichkeit, Full Width Pages zu nutzen, das fehlt deinem Theme noch.
Brauchen wir aber an vershiedenen Stellen.
wir brauchen also mindestens diese 2 Standardtemplates:
![grafik](https://user-images.githubusercontent.com/6114076/45497173-72cf9c80-b777-11e8-84db-85b024dc9dd5.png)

Bei dir ist da nichs auswählbar.

**Comment by springers54** [comment]
Ich habe jetzt die alte Fullwidth-Page einfach mal in dei Verzeichnis kopiert und immerhin erscheinen dass Templates zur Auswahl. Nur es wirkt noch nicht.
Wir können sicher alte Elemente nutzen, müssen die dann aber jeweils programmtechnisch anpassen
![grafik](https://user-images.githubusercontent.com/6114076/45588643-18217680-b918-11e8-9a8a-269d0c5b8c06.png)

![grafik](https://user-images.githubusercontent.com/6114076/45588659-4dc65f80-b918-11e8-88c8-2f249366505a.png)

**Comment by joergsteinhauer** [comment]
Ja, dieses Feature habe ich noch nicht implementiert - wie auch einiges weitere Sachen, da ich per defautl nicht davon ausgehe, dass man sie alle braucht. Ich muss explizit wissen, welche Features gebraucht werden.

Sollte auch kein Problem werden - habs noch nie gemacht, werde demnächst angehen.

Eine neue Datei im Theme alleine wird so leider nichts bringen. Wie bei allen Funktionalitäten in CMS, wird auch hier noch einiges an Logik gebraucht.

**Comment by joergsteinhauer** [comment]
Erledigt, testweise gleich auf der Kontaktseite eingestellt.

**Comment by springers54** [comment]
super, danke, wieder ein kleiner Schritt
