### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#133]
Sollten wir nicht den Entwicklungsserver auch unter https laufen lassen? Ansonsten kann und das später bei der Einbindung von Bildern Probleme machen, das war auf der alten Seite auch so.

**Comment by joergsteinhauer** [comment]
JA, sowas wäre gleich am Anfang sinnvoll. 
Allerdings ist die aufgabe bei mir eher falsch, das ist eine Konfigurationssache, hat nichts mit Theme oder Styling zu tun.

**Comment by springers54** [comment]
ok, dann haben wir es jetzt immerhin. Also bei mir läuft die Seite jetzt unter https.
