### ISSUE TITLE
Visuelle Anpassungen/Optimierungen

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#134]
Mir fallen immer wieder Sachen auf, die ich beim Styling noch nicht berücksichtigt habe. Ich liste diese alle mal auf und fixe nach und nach.

- [x] Button-Styling bei "disabled" https://reiki-lernen.de/anmeldeformular/
- [x] bessere Usability bei Buttons - Hover, Active etc. Evtl Farbe/Verlauf noch optimieren
- [x] Schriftgröße in der Sidebar (Forum) angleichen 
![grafik](https://user-images.githubusercontent.com/1843754/45803829-d77c8100-bcba-11e8-9271-3579075555ba.png)
- [x] Farben (orange) im Forum angleichen (zu dunkel)
- [x] Styling für den aktiven Submenüpunkt anpassen (z.b. grau/dunkel statt orange)
- [x] "Mehr Lesen" und ähnliche Links/Buttons an globalen Styling angleichen, z.b. "Jetzt schüler werden" auf https://reiki-lernen.de/schueler-werden/. Hier wird noch das alte HTML verwendet `btn btn-primary`.
- [x] Abstände anpassen 
![grafik](https://user-images.githubusercontent.com/1843754/45804058-67bac600-bcbb-11e8-831e-0839a14543d4.png)
- [x] Themen-Liste anpassen https://reiki-lernen.de/themen/
- [x] Parallax: https://github.com/dixonandmoe/rellax
- [x] Responsive Forum Layout 
![grafik](https://user-images.githubusercontent.com/1843754/45890405-2c0b2380-bdc3-11e8-81ae-10ed42cfa4d4.png)

**Comment by joergsteinhauer** [comment]
Fragen an Sylvia:

- was passiert mit einzelnen alten Cherry-Shrtocodes, wie `[parallax]` etc.? Die sind ja auf allen möglichen Seiten verteilt und diese brauchen wir wahrscheinlich nicht, weil ich diese Fearures anders löse. Macht Sinn, diese von den Seiten zu löschen. Ich denke, wir sollten das Zeug ganz am Ende löschen, weil ich z.z. nicht sagen kann, ob wir diese Shortcodes doch noch brauchen

**Comment by springers54** [comment]
Ich denke, wir sollten das nicht so einfach im Moment alles rauslöschen, sondern seitenweise bearbeiten. Die Codes haben ja eine Funktion und wir müssen in jedem Fall entscheiden, wie diese Funktion mit anderen Mitteln nachgebaut wird oder ob wir darauf verzichten.

**Comment by joergsteinhauer** [comment]
Genau, das denke ich auch so.

**Comment by joergsteinhauer** [comment]
Parallax Effekt ist auf der Kontaktseite schon mal aktiv, schaue mal bitte drüber. 

Vorerst geht das nicht über eine Einstellung im Admin Editor, sondern statisch über die Konfiguration in der JS Datei und in der Template-Datei für die "Fullwidth Page" (PHP).
Das wäre auch weiterhin der einfachste Weg für mich. Weiß nicht, wieviel Aufwand es bedeuten würde, das ganze über Shortcode oder andere Einstellung im Admin Editor umzusetzen - wahrscheinlich recht groß.

**Comment by springers54** [comment]
Prima, man sieht den Effekt.
Nur leider geht es ganz so einfach nicht. Denn wir haben den Effekt ja auf mehreren Seiten und oft nicht über die Ganzseite, wie hier im Formular, sondern auch nur in einem Teilbereich. Wie ist das dann?
Mir ist schon klar, dass wir es so einfach wie möglich machen müssen, aber zumindest muss es für mich in der custom.css in irgendeiner Weise nachvollziehbar sein.

**Comment by joergsteinhauer** [comment]
zu Parallax: Ja, den Effekt wollen wir auch auf anderen Seite haben. Ich muss dann Seite für Seite schauen, wie ich es dort am Besten einfüge - und zwar so, dass möglichst du selber die Konfiguration machen kannst. 
Dabei erfolgt die Konfiguration nicht über CSS, sondern JS. An sich könntest du auch dort schreiben, wenns nicht anders geht. Schauen wir dann, was am Besten ist.

Ich habe im Forum das "Fullwidth" Template eingestellt, wie auf der alten Seite. Damit gibts nun auch keine Layout-Fehler mehr.

**Comment by joergsteinhauer** [comment]
Ich würde dieses Issue schließen, da ich an sich alle Aufgaben erledigt habe. 
Falls ud noch Fragen zu Parallax hast, machen wir das am besten im neuen Issue.
