### ISSUE TITLE
Texte im Blocksatz

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#135]
kann es sein, dass durch eine Änderung der Blocksatz unserer normalen Absätze verloren gegangen ist? Sitze gerade mit Dani vor dem Rechner und wir sind beide der Meinung, dass die Absätze früher im Blocksatz waren.

Lässt sich das einstellen? Bitte auch für die neue Seite so umsetzen.

**Comment by joergsteinhauer** [comment]
Also erstens würde ich Blocksatz überhaupt nicht empfehlen: https://www.firmennest.de/webdesign/blocksatz-oder-flattersatz-responsive-design/
Zweitens sehe ich auf der alten Seite nirgendwo Blocksatz im Fließtxt... hmmm, z.b. https://zen-reiki.de/lehrerring/

Wollt ihr das wirklich haben? Eigentlich keine gute Idee...

**Comment by springers54** [comment]
Ok, danke für die Nachhilfe, dann besser nicht.
