### ISSUE TITLE
Gekürztes Menü für Responsive Design: gibt es keine bessere Lösung?

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#137]
Ich würde folgende Punkte auf Handy ausblenden:
![grafik](https://user-images.githubusercontent.com/6114076/45929649-fac25d00-bf54-11e8-8011-74452cea09da.png)

Kann man den Abstand zwischen den Menüpunkten nicht etwas verringern?

Wichtig sind die Kontaktinformationen und Formulare.
Unbedingt sollte man **suchen** können und sich **einloggen**. Diese Punkte müssen sichtbar sein.

Eine gute Lösung ist es nicht, mit dem Ausblenden, da es für mich für die weitere Pflege unpraktisch ist. Besser wäre es, das Menü so zu zeigen,d ass man es scrollen kann.
Somit halte ich die Ausblendevariante für den schlechtesten Weg.

**Comment by joergsteinhauer** [comment]
Ich habes es jetzt doch noch so umgebaut, dass das Menü scrollbar ist. 
Leider musste aber der X-button zum schließen des Menüs entfernt werden. Aber das Menü lässt sich beim Klick auf die große dunkle Fläche auch schließen bzw. der User will dann meist sowieso einen Menüpunkt anklicken.

Es gibt noch keine Suche im Menü. Die werde ich im extra Ticket umsetzen: #138
