### ISSUE TITLE
Suche im Header

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#138]
Es soll ein Suchformular im Header zuerst entworfen, dann umgesetzt werden.

**Comment by joergsteinhauer** [comment]
Habe es soweit umgesetzt, nach meinem Ermessen. Schaue bitte drüber, finde es ganz gelungen.

**Comment by springers54** [comment]
Also glücklich bin ich damit nicht. Wir hatten ja das letzte Mal schon gesagt, dass die Lupe nicht von jedem verstanden wurde. Ich hätte am liebsten das Suchfeld ganz einfach oben, wie auf sehr vielen Seiten.
![grafik](https://user-images.githubusercontent.com/6114076/46187521-46259400-c2e4-11e8-84da-626557096c63.png)
Auch nicht schön finde ich, dass man dann auf eine komplett leere Seite kommt, in der nur das Suchfeld ist. 
Also so hätte ich mir das eher vorgestellt:
![grafik](https://user-images.githubusercontent.com/6114076/46187829-d7e1d100-c2e5-11e8-8195-afeeb07fc2f4.png)
Eventuell auch oben Leiste und darunter das Suchfeld. Falls es oben bleibt, könnte man die kleinen Spitzen über die Menüpunkte auch setzen, hätte aber die Situation, dass die Menüs das Suchfeld überdecken würden.

**Comment by joergsteinhauer** [comment]
Hm... ich kann mich nur vage daran erinenrn, dass wir das thema mit dem Lupen-Icon angesprochen haben. Kann wirklich sein, dass ich mir da unschlüssig war, ob das jeder versteht. Aber auch wenn, muss ich meine Aussage wieder revidieren - denn das ist an sich ein sehr verbreitetes Muster was die Suche angeht. Die Lupe versteht an sich jeder. 

Viel wichtiger ist aber der User-Fokus in unserem spezielen Fall: ist denn die Suche so wichtig? Wenn ja, muss sie sofort sichtbar sein (als Sucfeld). Wenn nicht, kann sie weiterhin so bleiben wie ich es nun entwickelt habe.

Das ist übrigens keine komplett neue leere Seite, sondern ein Layer! Schaue bitte genauer hin. Dieses Design-Pattern trifft man oft und ist sehr bequem - es wird nur auf das wesentliche fokussiert.

Falls nun die Suche doch als Suchfeld eingebaut werden soll, wäre das ein kompletter Umbau des Headers. Ich dachte du willst so viel wie möglich wie im alten Design belassen? Verstehe dann nicht den Wunsch, den Header komplett zu ändern. 
Du musst dann auch bedenken, dass es dan nicht mehr so schön aussieht. Denn das ganze Design ist so gestaltet, dass die Elemente zueinander vertikal mittig ausgerichtet sind. Würde nun ein Suchfeld unter dem Menü kommen, würde es das ganze Layout kaputt machen. Wie du auch sagst - würde das Dropdown Menü dann z.b. auch die suche überdecken. Und es ist einfach zu angeklatscht.

Hast du dir die mobile Version angeschaut?

Also ich würde empfehlen, die Suche so zu lassen wie sie jetzt ist - denn es gibt keine Nachteile - sowohl aus Usability als auch aus Design Sicht.

**Comment by springers54** [comment]
Habe Enkel zu hüten und nicht soviel Zeit.
Ich habe mir gestern die mobile Version angesehen und davon bin ich begeistert. Da kommt die Suche durch die Alleinstellung richtig gut rüber.
Wenn die Suche ein Overlay ist, dann würde ich sie etwas transparenter machen. Aber sonst bin ich bei dir, wir lassen es so, wie du es entworfen hast.
Am PC würde ich zwar ein Suchfeld besser finden, aber da haben wir mehr Menüs im Sichtfeld und wir können dann nur hoffen, dass die Nutzer die Lupe auch zum Suchen nutzen.
 * [x] Suchoverlay transparenter machen.

**Comment by joergsteinhauer** [comment]
Hier ist an sich alles erledigt - Issue schließen?

**Comment by springers54** [comment]
* [x] Search Results for: bitte in Deutsch
