### ISSUE TITLE
Styling Sidebar Box

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#141]
### Bild 1
IST:
![grafik](https://user-images.githubusercontent.com/1843754/46228456-6c8a1480-c362-11e8-80cc-eb02e546b6a4.png)

SOLL:
![grafik](https://user-images.githubusercontent.com/1843754/46260840-b2beaf80-c4eb-11e8-96d0-53a7ac79c93a.png)

- [x] Styling box (Hintergrund zusammenhängend)

**Comment by springers54** [comment]
so unbedingt würde ich die Vorschau gar nicht haben wollen.
Es reicht mir eine Liste aus. Vielleicht könnte man die einzelnen Bereiche ettwas abgrenzen.

Wie stelle ich mir das vor? Die Hintergrundfarbe, aber keine weißen Abstände zwischen den einzelnen Einträgen in einer Rubrik

**Comment by springers54** [comment]
Die Vorschau und das Mehr Lesen halte ich für verzichtbar. Wie siehst du das?

**Comment by joergsteinhauer** [comment]
Ok, sehr gut. "Mehr lesen" und Vorschautexte finde ich auch nicht notwendig, zumal diese die Seite einfach überfrachten. Dann verzichten wir auf sie, denn dies einzubauen macht auch haufen Arbeit und ich wüsste z.z. noch nicht mal, wie man das hinkriegt (habs schon probiert).

Styling passe ich an.

**Comment by springers54** [comment]
das Vorschau Problem haben wir leider auf der Hauptseite der Beiträge, schau dir das auf der alten Seite an.
Aber rechts zusätzlich wäre dann überflüsig,
https://prnt.sc/l33vfl

**Comment by springers54** [comment]
### Bild 2
![grafik](https://user-images.githubusercontent.com/6114076/46604896-05095d00-caf8-11e8-8378-8ad34f45193b.png)

Ich habe die Suche rausgenommen, da es dann einheitlich mit der Lupe gemacht werden sollte auf allen Seiten. Damit muss die Ausrichtung korrigiert werden. in der Höhe.

**Comment by joergsteinhauer** [comment]
- Ausrichtung der Aufzählung angepasst
- Schrift und Trenner wie in unteren Widgets gemacht, so apsst das besser zusammen. Schriftgröße würde ich nicht größer machen, sondern genau so groß lassen wie in unteren Widgets:
![grafik](https://user-images.githubusercontent.com/1843754/47240149-c2912b80-d3e7-11e8-8789-b66b66ae9408.png)
- Sidebar-Abstand nach oben angepasst
-------------------

Dieses Problem müssen wir eh komplett noch lösen, dafür brauchen wir am besten ein neues Issue:
```
das Vorschau Problem haben wir leider auf der Hauptseite der Beiträge, schau dir das auf der alten Seite an.
Aber rechts zusätzlich wäre dann überflüsig,
https://prnt.sc/l33vfl
```

**Comment by springers54** [comment]
* [x] Styling der Boxen für Neueste Beiträge und Kommentare bitte überarbeiten. Wir finden die weißen Bereiche dazwischen nicht gut, Eher auch eine Aufzählung wie im Bild 1 dieser Issue, vielleicht mit einem Hintergrund zur Abgrenzung. Aber enger zusammen und als Block geschlossen. So wie es im Bild 2 schon mal teilweise war.

**Comment by joergsteinhauer** [comment]
Ok, habs mal weiter angepasst. Bitte anschauen.

**Comment by springers54** [comment]
gefällt mir noch nicht wirklich, die Linien in grau finde ich störend. Ich würde es etwas enger zusammenziehen und ein Aufzählungszeichen davor machen

**Comment by joergsteinhauer** [comment]
Hmpf, ok. Habs angepasst, jetzt sind Pfeile drin. Weiß nicht ob die ForenBoxen auch so gestaltet werden sollen. Finde die jetzt auch ganz gut. Kann sie aber auch ncoh mit Pfeilen ergänzen.

**Comment by springers54** [comment]
Ja, prima, gefällt mir jetzt auch. Vielleicht noch etwas weniger Abstand zwischen den Aufzeichnungen?
Im Moment sind es 28px, die Regel 1.15 greift nicht. Durch die kleinere Schrift sehen die Abstände wesentlich größer aus als oben bei den Themen.
Die Anpassung der beiden Forenboxen wäre gut. Dort muss auch keine rote Schrift drin sein.
 * [x] Zeilenabstand etwas verringern 
* [x] Forenboxen an Styling anpassen.

**Comment by springers54** [comment]
Könnten wir die Forumsboxen auch noch anpassen? Mein Vorschlag wäre, nur Thema und max. 2 Zeilen, nicht Autor und Datum und sonst was? Dann würde es einheitlicher aussehen und wir nehmen dann vielleicht auch 3 Elemente in die Box auf, das kann am im Forum einstellen.

**Comment by joergsteinhauer** [comment]
Die "Autor" und "Datum" Texte habe ich per CSS entfernt (sehe sonst auch nicht, wie man das in Einstellungen nur für Widgets komplett entfernen kann).

Auch die Zeichen-Anzahl der Vorschautexte kann man nirgendwo einstellen.
