### ISSUE TITLE
Teaser Slider + Parallax Effekt

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#142]
![grafik](https://user-images.githubusercontent.com/1843754/45811870-8d9d9600-bcce-11e8-81f1-e312b5d17857.png)

**Frage** @springers54 :
Muss dieser Slider über Admin konfigurierbar sein? Also z.b. Bilder über Mediathek auswählbar sein? 

Wenn ja - wäre das hier Plugin notwendig.
Wenn nein - würde ich es ohne Plugin machen, was dann besser für Performance ist. Die Auswahl und Anzahl der Bilder wäre eher starr über Javascript und CSS Dateien geregelt - aber das ist relativ einfach und könnte ggf. auch von dir angepasst werden.

Ich wäre für eine Lösung OHNE Plugin.

**Comment by springers54** [comment]
Ich bin auf jeden Fall für eine Lösung ohne Plugin, es würde mir eine mögliche Konfiguration ind costum.css reichen, wo ich die Namen der Bilder, die im Slider gezeigt werden, auswählen kann.
 * [ ] Schaffung eines Stylings, das per costum.css angepasst werden kann
 * [ ] Erlauben einer Textveränderung in den Slidern auch per costum.css

**Comment by joergsteinhauer** [comment]
Ok, dann wird es höchstwahrscheinlich so aussehen:
- Bilder werden im CSS festgelegt.
- Anzahl der Bilder und andere globale Einstellungen werden im JS festgelegt
- Texte werden entweder im JS oder im PHP festgelegt.

Aber alles relativ einfach und schnell zu verstehen, dafür schreibe ich dann auch eine Anleitung.

**Comment by joergsteinhauer** [comment]
Ich habe nun einige Zeit am Slider gebastelt, es war sehr komplex. 
Es sieht an sich ganz gut aus, wobei nicht ale Effekte etc. Haargenau wie auf der alten Seite sind - ich bin trotzdem zufrieden damit.

Schaue mal bitte drüber.

Es ist im Gegensazu zum Slider auf der alten Seite viel schneller, fühlt sich leichter an, ist auch im Code vieeeel schlanker und kommt ohne WP-Plugins aus, nicht mal jQuery braucht es (nur native JS). Funktioniert auch nicht über shortcodes, sondern direkt als reines HTML.

Die Konfiguration erfolgt aber komplett als HTML im Artikel selbst, dazu werde ich am Ende noch eine Anleitung erstellen.

**Comment by joergsteinhauer** [comment]
Generell ist die Startseite ein Sonderfall, daher ist da einiges mit reinem HTML umgesetzt - anders als auf der alten Seite - dort ist es auch ein sonderfall, aber die Custom-Sachen sind dort über shortcodes umgesetzt.

Shortcodes sind meist ok, aber erfordern auch viel Aufwand - dazu kommt die Tatsache, dass ich da nicht immer durchblicke und so ein Shortcode für mich schwer zu entwickeln ist - es erfordert eben fundierte PHP WP Kentnisse.

**Comment by springers54** [comment]
ich finde das prima so, einzig der auotmatische Wechsel müsstee noch passieren, das war beim alten Slider.
Der Parallaxe-Effekt reicht aus und ist sichtbar. Besser finde ich, dass der Bereich nicht ganz so hoch ist und damit nicht so dominand.
Die Startseite ist eein Sonderfall. Da kann einiges HTML sein, da bin ich bei dir

**Comment by joergsteinhauer** [comment]
Super, ja der auto-wechsel kommt noch.
Gut, dann sind wir uns einig, das erleichtert vieles!

**Comment by springers54** [comment]
Du hast den Sclideshow-Effekt hinbekommen, prima. Ich finde ihn im Moment aber etwas hektisch, das Bild springt zum nächsten. Kannst du es etwas fließender gestalten?

**Comment by joergsteinhauer** [comment]
Habe es übrigens etwas fließender gestaltet. Passt so? Wenn ja, das Issue bitte gern schließen.

**Comment by springers54** [comment]
also im Moment gibt es gar keinen Slider, sondern nur ein Bild, was springt und das auch nach einer ziemlichen Zeit. Da muss etwas kaputt gegangen sein. Im Quelltext wird auch nur noch Slider1 geladen.
Das Bild steht eine Zeit, dann ruckt es zum nächsten Bild. Kann man das Bild etwas langsamer einblenden?

Der Parallaxe-Effekt ist sichtbar und reicht aus.

**Comment by joergsteinhauer** [comment]
Ok, es war tatsächlich immer nur das erste Bild eingestellt. Habe es korrigiert. Der Slider "wischt" von rechts nach links, anerds als auf der alten Seite.

Und es gibt irgendwie Probleme mit dem Slider im FF - hier geht es bei mir nur sporradisch, .z.b wenn ich den Browser neu starte. Im chrome funktioniert alles. Wie ist es bei dir?

> Kann man das Bild etwas langsamer einblenden

Meinst du langsamere Animation oder die Zeit zwischen dem Wechseln der Slider verlängern?

**Comment by springers54** [comment]
> Meinst du langsamere Animation oder die Zeit zwischen dem Wechseln der Slider verlängern?

eine langsamere Animation, die Wechselzeit ist eher etwas zu lang als zu kurz.
Bisher hat es im FF bei mir funktioniert mit dem Wechsel.

**Comment by springers54** [comment]
- [x] Kannst du bitte die gelbe Leiste in der Höhe reduzieren?
![grafik](https://user-images.githubusercontent.com/6114076/50737143-314f7b00-11c6-11e9-890d-92bc5568c4ef.png)

Gut ist, dass die Slider in der Höhe weniger Platz beanspruchen als auf der alten Seite.

**Comment by springers54** [comment]
prima, danke
