### ISSUE TITLE
Service Box inkl. Titel 

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#143]
![grafik](https://user-images.githubusercontent.com/1843754/45811936-bcb40780-bcce-11e8-96cc-f43488b1ecd0.png)

**Comment by joergsteinhauer** [comment]
@springers54 ich bin gerade beim Entwickeln und Stylen, brauche aber bitte alle Icons als Vektor. Das erste Icon habe ich selber gefunden. Reicht mir, wenn du sie in der Dropbox unter `Wordpress_Media\Icons\my-icons-collection(3)\Vektor\svg` ablegst

**Comment by springers54** [comment]
Ich weiß nicht, ob ich dir mit alles Bildern als SVG dienen kann, denn einige waren aus dem Theme, andere habe ich mir gesucht.
Die meisten kleinen Icons haben wir nur als jpg oder png, aber nicht als svg. Was nun?

**Comment by joergsteinhauer** [comment]
Ok, schade. Dachte du hast sie alle bei iconfinder gesucht? Na gut, wenns so ist - dann bitte in best möglicher Auflösung in der Dropbox ablegen. Ich schaue was sich machen lässt...

**Comment by springers54** [comment]
ich habe die Icons von https://www.flaticon.com/
Alle, die ich dort gesucht habe, habe ich dir als SVG gespeichert  in `Dropbox\Wordpress_Media\Icons\my-icons-collection(3)\SVG\my-icons-collection.zip`
Es sind aber auch welche drin, die ich nicht verwendet habe.

Die vom Theme habe ich in keiner anderen Auflösung als die, die du über Filezilla selbst herunterladen kannst.

Ich bin allerdings auf die Icons nicht voll fixiert. Hast du andere, die passen, können wir die auch nehmen.

**Comment by joergsteinhauer** [comment]
Ok, wenn Icons nicht komplett die gleichen sein sollen, meine Vorschläe für ide zwei fehlenden:
- "Schüler werden" 
![grafik](https://user-images.githubusercontent.com/1843754/46435949-ec93ee00-c757-11e8-873c-359584fda867.png)
https://www.flaticon.com/free-icon/pc-search_81871#term=monitor&page=1&position=19
- "Reiki-Einweihungen" 
![grafik](https://user-images.githubusercontent.com/1843754/46436103-5f04ce00-c758-11e8-9a67-6558d39a61de.png)
https://www.flaticon.com/free-icon/team_56950#term=group%20people&page=1&position=8

**Comment by springers54** [comment]
Also die Striche sollten dann schon über den Kopf, kannst du das ranmachen?
Das andere Icon mit Schüler werden finde ich zwar besser, aber zur Not geht das, was du gesucht hast.

**Comment by springers54** [comment]
WArum nutzt du keinen Konverter? https://convertio.co/de/jpeg-svg/
![grafik](https://user-images.githubusercontent.com/6114076/46453483-0c500400-c7a2-11e8-9e3d-e4a90349d32a.png)
![grafik](https://user-images.githubusercontent.com/6114076/46453499-24278800-c7a2-11e8-9236-751a37b450e0.png)
Finde ich wesentlich besser,
sind auf der Dropbox unter fehlende _Icons.zip

**Comment by joergsteinhauer** [comment]
Die Striche kann ich noch drauf setzen. 
Ich versuche immer bereits existierende Icons zu verwenden, die sind auch meist gut und zueinander passend gemacht.
Converter sind mist, da die ungenau sind, das ist doch alles verschoben.

**Comment by springers54** [comment]
Aber schöner sind die alten Icons leider

**Comment by joergsteinhauer** [comment]
Ich hab die Icons etwas angepasst, sehen fast wie die alten aus.

Zur Service Box gehören folgende shortcodes:

```html
[service-box-wrapper]

[service_box title="Schüler werden" icon="pc-search" text="Du kannst dir aus unserem Team deinen Wunschlehrer aussuchen. Kontaktiere ihn bitte per Mail. Der Lehrer entscheidet, ob er mit dir arbeiten möchte oder ob ein anderer Lehrer aus dem Team vielleicht besser zu dir passt." btn_link="internetschule/schueler-werden/" btn_size="normal" target="_self" custom_class="extra"]

[service_box title="Reiki-Einweihungen" icon="team" text="Nach dem Kennelernen bekommst du einen Einweihungstermin. Die Einweihung wird als Ferneinweihung vom Lehrer auf den Schüler übertragen. Nach der Einweihung gibst du deine Schülermeinung ab und bekommst Unterlagen." btn_link="internetschule/reiki-einweihungen/" btn_size="normal" target="_self" custom_class="extra"]

[service_box title="Ausbildungskosten " icon="coins-on-hand" text="Zen-Reiki-Lehrer verschenken die Einweihungen, auch die damit verbundene Mailbetreuung ist Teil unseres sozialen Engagements. Zertifikate werden gegen eine Servicepauschale von 20€ erstellt. Lies hierzu die AGB unter Lernen. " btn_link="internetschule/ausbildungskosten/" btn_size="normal" target="_self"]

[service_box title="Coaching und Heilen" icon="heart-in-hands" alt="Zen-Reiki: Coaching und Heilen" text="Intensive Coachingbetreuung und weitergehende Heilbehandlungen sind kostenpflichtige Leistungen und können individuell mit dem jeweiligen Lehrer abgesprochen werden. Schau dir dazu die Profile unserer Lehrer an." btn_link="internetschule/coaching-und-heilen/" btn_size="normal" target="_self"]

[/service-box-wrapper]
```

Ich denke, das ist alles selbsterklärend. An sich genau so wie auf der alten Seite.
