### ISSUE TITLE
Credo: Featured Box - Wir sind anderes

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#144]
Inkl. Parallax Effetk

![grafik](https://user-images.githubusercontent.com/1843754/45812003-e40ad480-bcce-11e8-81fb-7927758c3944.png)

**Comment by joergsteinhauer** [comment]
@springers54 
Ich hatte erstmal vor, dieses Feature als shortcode umzusetzen.
Allerdings wäre das viel mehr Aufwand (habe ich am Bsp. der **Service-Box** gesehen).
Daher werde ich dieses Feature hier erstmal als reines HTML umsetzen.

**Comment by springers54** [comment]
Ist ok, da wir das nur hier brauchen. Shortcodes machen eigentlich nur Sinn, wenn es Bausteine sind, die auf mehrerem Seiten verwendet werden oder eine eigene Verwaltung inhaltlich sinnvoll ist. Ist an dieser Stelle nicht so.

**Comment by joergsteinhauer** [comment]
Genau so ist es, wunderbar.

**Comment by joergsteinhauer** [comment]
Erster Schritt ist getan, schaue mal bitte drüber. Ich werde ggf. noch ein paar Sachen fein tunen.

**Comment by joergsteinhauer** [comment]
Habe die 4 Boxen doch als shortcodes gemacht, weil das so besser im Admin zu managen ist. Reines HTML wäre zu globig und shortocde in diesem Fall war einfach. 

Der Rest drumrum ist reines HTML.

Das BG-Bild ist wieder in der custom.css konfiguriert.

**Comment by springers54** [comment]
Super, warum auch immer, heißt dieser posttyp news und wurde in credo umbenannt. Ich kann die Daten nur importieren, wenn du mir den Typ auch als News benennst.
![grafik](https://user-images.githubusercontent.com/6114076/46596053-5d7e3180-cadb-11e8-880d-2ccfd318d1ae.png)

**Comment by joergsteinhauer** [comment]
Hm ja... verstehe. Kann so auch gar nicth gehen, denn diese Featured Box ist z.Z. noch komplett statisch als HTML eingebaut. Da wird nichts aus irgendwelchen Seiten gezogen. Um das dynamisch zu bauen, werde ich etwas länger brauchen.

**Comment by springers54** [comment]
Es geht nicht mal nur um den Einbau auf der Startseite, diese hat ja nur die kleinen Icons, einen Anteasertext mit Link auf diesen Post-typ. Damit ich den Posttyp importieren kann, müsste er angelegt sein.
Da es sich um 4 Seiten handelt, kann man die auch händisch kopieren und manuell verlinken.
Wir müssen uns nur klar sein, wie das Vorgehen sinnvoll ist. Ändern werden sich die Inhalte kaum oder mehr als 4 verwendet werden.

Im aktuellen System ist es hier zu finden:
![grafik](https://user-images.githubusercontent.com/6114076/47299012-83e2b780-d619-11e8-9b2a-0cf0481dc542.png)

**Comment by joergsteinhauer** [comment]
Ok, ich glaube ich fange langsam es zu verstehen.

Im alten System gibt es zwar den Menüpunkt "News", so auch den Posttype "News" usw. Allerdings ist der Slug zu diesen Newsbeiträgen ".../credo/..." - warum auch immer. Das macht so nicht wirklich Sinn oder ich kanns nicht nachvollziehen. Ich finde es besser, wenn das Zeug entweder "news" oder "credo" heißt. Nun sind die dazugehörigen Einträge in der DB als "news" hinterlegt, also solche musst sie auch erstmal im neuen System importieren. Da gibts keinen anderen Weg, also muss der Posttype im neuen System auch "news" heißen. Was ich nun auch gemacht habe. Der Slug heißt wieder "credo", denn "news" wäre verwirrend.

Wir testen das mal so, hoffe es geht alles. Wenn ja, kann ich darauß wieder eine dynamischen Shortcode erstellen, der die Daten aus diesen News-Artikeln (credo) dynamisch anzeigt. Da muss man dann nichts mehr händisch im Template ausgeben.

**Comment by joergsteinhauer** [comment]
So, nun auch hier nach langem Frickeln das Shortcode erfolgreich aktualisiert - und zwar wieder mit dem Script aus dem CherryFramework. Habe es eben optimiert und nur das rüber genommen, was wir brauchen. Die Inhalte kommen nun also dynamisch aus den "News" Beiträgen (Credo).

Gleichzeitig die Größe von ein paar SVG Icons angeglichen.

Die News (Credo) Beiträge haben als Vorschaubild nun ein SVG, zum Glück erlaubt WP das.

**Comment by springers54** [comment]
* [x] News in Crede umbenennen. Der Import ist durch, so dass es jetzt nicht mehr News heißen muss. Das kam vom alten Theme, da ich den Posttyp dafür missbraucht habe, Von der Semantik her hat das aber mit News nichts zu tun.

**Comment by joergsteinhauer** [comment]
Du meinst sicherlich das Umbenennen auf der Admin-Ebene? Habe ich erledigt. Post-Type bleibt weiterhin "news", soweit ich es verstanden habe, ist es dann u.a. der Kennzeichner in der DB. Slug ist weiterhin "credo".

**Comment by joergsteinhauer** [comment]
@springers54 Wäre hier noch was zu machen?

**Comment by springers54** [comment]
Wird in #169 fortgesetzt
