### ISSUE TITLE
Meinungen auf der Startseite: Typ Testimonial: (Recent Posts Box)

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#145]
![grafik](https://user-images.githubusercontent.com/1843754/45812047-03a1fd00-bccf-11e8-921b-44a451099420.png)

**Comment by springers54** [comment]
Ich habe das mal umbenannt, weil Titel sehr irreführend ist. Es handelt sich in dieser Box um die sogenannten Testimonials, also Kundenmeinungen.
![grafik](https://user-images.githubusercontent.com/6114076/47299400-64985a00-d61a-11e8-9d06-f6241e437765.png)

Wir haben es hier wieder mit einem eigenen Posttyp zu tun, dem Typ testi, der müsste also geschaffen werden, um die Meinungen zu importieren.

**Comment by joergsteinhauer** [comment]
Post type habe ich angelegt, die Bezeichner/Wording im Admin etc. etwas besser benannt, als im alten System, schaue mal bitte drüber, ob das Wording so passt.

Sobald du die Artikel importiert hast, kann ich mit dem Shortcode anfangen.

**Comment by joergsteinhauer** [comment]
Styling ist umgesetzt (z.z. noch mit statischem Inhalt).

**Comment by springers54** [comment]
Also der Import hat funktioniert, vielen Dank. 
Allerdings müssen wir am Styling noch arbeiten. Auf der Startseite werden jetzt so viele Elemente angezeigt, wie wahrscheinlich vorhanden sind, da kommt nur eins hin.

- [x] Styling
------------------------------

> schaue mal bitte drüber, ob das Wording so passt.

Ich würde es einfach Meinungen nennen, das reicht vollkommen, dieses Testemonial muss nicht davor.

- [x] Wording

**Comment by springers54** [comment]
Im alten System ist hier die Überschrift als Titel mit gesetzt:
![grafik](https://user-images.githubusercontent.com/6114076/47723722-6b941d80-dc55-11e8-9ad4-3c962c0fc3a1.png)

Im neuen System fehlt diese

- [x] Überschrift

--------------------------------

Das Bild ist nicht umflossen

- [x] Bild umfließen

--------------------------------

Das kursiv aus dem alten System würde ich nicht verwenden, das hat keinen Sinn

- [x] Kein kursiv

**Comment by joergsteinhauer** [comment]
Super. Ja, es werden noch alle Meinungen angezeigt. Das mache ich als nächstes. 

Vorab aber: im alten System wird immer die letzte Meinung angezeigt. Soll das nun im neuen system genau so werden? alternativ könnte man alle Meinungen in einem Caroussel darstellen (also slider-ähnlich), wo man über Pfeile nach links/refchts alle vorhandenen Meinungen anzeigen könnte. Wäre aber sicherlich mehr Aufwand.

**Comment by joergsteinhauer** [comment]
So, die Meinungen sind jetzt haargenau so wie im alten System. Ich musste leider (oder gut so? - weiß selber nicht) die Logik aus dem Cherryframework kopieren, da ich selber sowas nicht hingekriegt hätte - das ist dann schon reine PHP Entwicklung.

Letztendlich sind es zwei Sachen aus dem CherryFramework - ein "On the fly" resizer für die Bilder (https://github.com/syamilmj/Aqua-Resizer) und der shortcode für die Meinungen. Ich habe es dann halt noch verbessert und optimiert.
spricht insgesamt nichts dagegen es so zu machen.

**Comment by joergsteinhauer** [comment]
TODO @joergsteinhauer Titel (entry-header) nicht per CSS ausblendenm, sonder über PHP o.ä.

**Comment by springers54** [comment]
Ich denke auch nicht. Ich würde für die Startseite an dieser Stelle auch keinen Slider oder sonst was nehmen wollen. Die Frage ist, wer überhaupt bis da unten scrollt und da wäre weiterer Aufwand schade.

Es reicht, wenn immer die letzte Meinung dort angezeigt wird.

**Comment by joergsteinhauer** [comment]
Wunderbar. Ich denke schon, dass es soweit runter gescrollt wird. 

Also bleibt hier nur noch eins (was aber nicht dringend ist):

- [x] PHP Script für den Shortcode aufräumen
