### ISSUE TITLE
Artikel Header Bilder

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#146]
@springers54 
Header Bilder müssen größer sein, damit sie den ganzen Content-Raum einnehmen. 
Dies kommt daher, weil der Content Bereich im alten Theme schmaler war https://reiki-lernen.de/faqs/. Dort waren also kleine Bilder notwendig. Nun sind die Bilder ja gleich geblieben, der Content-Bereich aber hat sich vergrößert.

Wie viel Aufwand wäre es, die Bilder händisch auf allen Seiten zu aktualisieren?

Ich könnte die bilder zwar per CSS größer skalieren, aber dann wären sie unscharf.

![grafik](https://user-images.githubusercontent.com/1843754/45803769-b025b400-bcba-11e8-9c82-9fbff6f0216d.png)

**Comment by springers54** [comment]
* [x] @joergsteinhauer Bildgröße für Themen-Header festlegen
So viele Seiten sind das nicht, also das könnte händisch geändert werden, wenn du die Größen vorgibst.

**Comment by joergsteinhauer** [comment]
`845px` breit müssen die bilder sein, z.z. sind sie `800px`

**Comment by springers54** [comment]
gemacht habe ich die, muss ich nur noch hochladen

**Comment by springers54** [comment]
Warum skalierst du die Bilder im Moment sogar runter?
![grafik](https://user-images.githubusercontent.com/6114076/49919916-90142400-fea8-11e8-8dca-ea5bdbab6d87.png)
Das mit der Bildbreite von 845px, die ich gemacht aber noch nciht hochgeladen habe, müsste sich dann erledigt haben?

**Comment by joergsteinhauer** [comment]
Korrekt, die Breite des Contents hat sich in irgendeinem Issue (weiß jetzt nicht mehr wo) geändert - nun sind es 780px

**Comment by springers54** [comment]
Sollten wir dann die Bilder in 780 erstellen und ablegen?

**Comment by joergsteinhauer** [comment]
Das wäre natürlich optimal... aber nur, wenn wir uns jetzt final auf diese Content-Breite festlegen (wovon ich ausgehe - ich sehe keinen Grund die Breite noch irgendwann zu ändern, ist gut so jetzt).

**Comment by springers54** [comment]
ist keine Prio-Aufgabe, kann auch noch nach dem Umzug gemacht werden

**Comment by springers54** [comment]
ist in #186 weiter besprochen, darum hier zu.
