### ISSUE TITLE
Ladezeiten der Seite verbessern

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#147]
https://tools.pingdom.com/
![grafik](https://user-images.githubusercontent.com/6114076/46602813-92957e80-caf1-11e8-97fe-5dc01b525bea.png)

Die alte Seite zum Vergleich:
![grafik](https://user-images.githubusercontent.com/6114076/46602877-c1135980-caf1-11e8-812e-03e7b71844f8.png)

und neu:
![grafik](https://user-images.githubusercontent.com/6114076/46602923-edc77100-caf1-11e8-995b-879023d117c9.png)

![grafik](https://user-images.githubusercontent.com/6114076/46602995-10f22080-caf2-11e8-88d1-56fc695ca3d5.png)

Es sind die Lehrerbilder, die wir unbedingt ändern müssen, damit wir eine performante Seite bekommen. Das momentane Verfahren funktioniert nicht.

**Comment by joergsteinhauer** [comment]
Jep, da ist noch einiges zu optimieren, aber meist sind das die Bilder. Sowas mache ich imemr dann, wenn Layout fertig ist. Gehe ich später an.
Hoffe, dass das CSS und JS im Gegensatz zur alten Seite besser ausfällt.

**Comment by springers54** [comment]
Ich denke, wir sollten das nicht am Ende machen. Es liegt ja hauptsächlich am Lehrerblock #123 .
Es wäre mir wichtig, dass wir hier eine Lösung haben, mit der wir leben können. Offensichtlich werden auch auf der Homepage die großen Bilder geladen, was keinen Sinn macht.
Nun gibt es 2 Möglichkeite, wie wir vorgehen können. Die erste besteht darin, dass du deinen Baustein optimierst. Wenn das zu aufwändig ist, dann besteht die zweite Möglichkeit darin, den Teambaustein als Tabelle auf der Seite zu bauen, die kleinen Bilder zu laden, mit den großen zu verlinken sowie mit den Seiten der Lehrer.

Das wäre zwar weniger elegant, aber auch machbar, denn die Lehrer wechseln nicht jeden Tag. Und es läuft nach einem festen Schema ab.

Aus meiner Sicht sollten wir eine Grundoptimierung der Seite schon während der Gestaltung im Auge behalten und das Feintuning dann am Ende machen. Ansosnten machen wir zu viele Baustellen nciht zu.

**Comment by springers54** [comment]
> Hoffe, dass das CSS und JS im Gegensatz zur alten Seite besser ausfällt.
![grafik](https://user-images.githubusercontent.com/6114076/46650599-66373c00-cb9d-11e8-8923-78355eaacdb6.png)
![grafik](https://user-images.githubusercontent.com/6114076/46650604-6c2d1d00-cb9d-11e8-832b-49dbe6cf9417.png)

https://gtmetrix.com/reports/reiki-lernen.de/iTxLdXKd
![grafik](https://user-images.githubusercontent.com/6114076/46650633-8535ce00-cb9d-11e8-9278-16d0126caad8.png)

https://freetools.seobility.net/de/seocheck/check?url=https%3A%2F%2Freiki-lernen.de&crawltype=1
![grafik](https://user-images.githubusercontent.com/6114076/46650796-2886e300-cb9e-11e8-8662-45368bf2e071.png)

https://varvy.com/
![grafik](https://user-images.githubusercontent.com/6114076/46650959-b531a100-cb9e-11e8-81f3-a614b2d7fe40.png)

**Comment by joergsteinhauer** [comment]
Ok, grundsätzlich korrekt. Neu entwickelten Features sollten gleich zumindest grob optimal entwickelt werden, einige Sachen habe ich teilweise außer Acht gelassen (optimierte Bilder, SVG, valides CSS/HTML). Werde ich alsbald nachholen.

Problem Lehrerbilder lösen wir in einem anderen Issue, bitte dort angehen: #123

Die meisten Tools meckern Optimierungen im Bereich Komprimierung an (Bilder, CSS, JS). Bilder habe ich oben erwähnt, CSS und JS wird am Ende durch ein Plugin komprimiert - darauf sollten wir also am Ende schauen.

Was noch offen ist - sind die ganzen OnPage Sachen (Markup, Meta-Tags etc.).

Des Weiteren gibt es Sachen im Server-Bereich zu optimieren, da bin ich raus.

**Generell sollte die Seite ja sowieso nicht live geschalten werden, bevor wir nicht die meisten Kinderkrankheiten beseitigen.**

**Comment by joergsteinhauer** [comment]
Alle Bilder (so wie sie sind - unabhängig davon, ob die einzelnen Features noch optimiert werden) wurden händisch optimiert. 
Normalerweise macht man sowas nicht händisch, aber da sich die betroffenen Elemente nicht oft ändern (Teaser, Lehrer) habe ich sie eben händisch optmiert.

Die Bilder waren bis dato nicht gut benannt (mal klein, mal groß, mal ein komischer Buchstabe am Ende, mal mit, mal ohne NAchname - keine konsistente Benamung) und waren in diversen Verzeichnissen verstreut. Ich habe es so gut wie ging vereinheitlicht.

Für SVG gibt es extra Issue: #149

**Comment by joergsteinhauer** [comment]
Habe nun einige Zeit mit Validieren verbracht, an sich sind das alles keine schwerwiegenden Probleme, lsäst sich nach und nach lösen.

Einzig gibt es noch ein komplexeres Problem bei Shortcodes und HTML in Artikeln - hier werden beim Zeilenumbruch noch die automatische Wordpress p-tags eingefügt, das macht den Quelltext invalid... aber das PRoblem ist auch lösbar, dauert eben ggf länger.

**Comment by springers54** [comment]
Das einfache Umbenennen würde aber nicht gehen, da wir sonst den Zusammenhang mit den alten Seiten verlieren.
Für die Startseite ist das ok, für alle anderen Seiten nicht, denn das würde bedeuten, dass ich die Sachen nicht zu einem späteren Zeitpunkt updaten kann. Es sind noch lange nicht alle Dinge der alten Seite übertragen, so dass es noch nicht mal möglich wäre, beide Seiten parallel zu pflegen.

Die Übertragung aller Inhalte wäre die Voraussetzung, um dann beide Seiten eigenständig zu sehen.

Das betrifft auch das Verschieben von Bildern in andere Ordner, denn am Ende geht dann gar nichts mehr.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/46714521-22efd280-cc5c-11e8-81c9-b14c1f901709.png)

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/46714553-503c8080-cc5c-11e8-9a1d-e644d4208d07.png)

So stellt es sich jetzt da, also viel sieht man noch nicht.

**Comment by joergsteinhauer** [comment]
> Das einfache Umbenennen würde aber nicht gehen, da wir sonst den Zusammenhang mit den alten Seiten verlieren.

Guter Punkt, daran habe ich nicht gedacht. Dann binde ich wieder die alten Bilder ein, ersetze die aber auf dem FTP mit den optimierten Versionen (wenn nichts dagegen spricht). Einen anderen Weg haben wir nicht wirklich.

> So stellt es sich jetzt da, also viel sieht man noch nicht.

Ich  bin doch noch lange nicht fertig mit den Optimierungen, Step by Step...

**Comment by springers54** [comment]
Ich schließe das hier erst einmal, weil wir aktuell andere Baustellen haben. Die endgültige Seo-Optimierung sollten wie dann vornehmen, wenn die Probleme wie Bildergrößen und Archivseiten durch sind.
