### ISSUE TITLE
Login und Logout anstelle von Anmelden/Abmelden

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#151]
Wir nutzen auf der alten Seite bewusst Login und Logout, weil m,an sich auf der Seite mit dem Link nicht Anmelden kann.

Anmelden wird von den Leuten so verstanden, als wenn sie sich dort als neuer Schüler anmelden können, was aber so nicht funktioniert.
Deshalb ist es Login und Logout. Ich weiß, dass damals Arun das geändert hat. Wenn du es nicht hin bekommst, muss ich ihn fragen. Im Menü steht mir der Punkt nicht zur Verfügung, so dass ich es selbst nicht ändern kann.

**Comment by joergsteinhauer** [comment]
Erledigt
