### ISSUE TITLE
Template Archives übernehmen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#152]
Die Seite https://zen-reiki.de/archiv/ zeigt das Archiv der Beiträge an und basiert auf dem Template Archives
Dies müsste für die neue Seite übernommen werden.
![grafik](https://user-images.githubusercontent.com/6114076/46753041-0cc72e00-ccbf-11e8-97f6-d0d6d5d3a207.png)

**Comment by joergsteinhauer** [comment]
Habe initial schon mal geschaut, wie das derzeit funktioniert hat - ist mal weider schön im Cherry verwurstelt. Mal sehen wie schnell ich hier voran komme.

Frage: welche Beiträge sind heir gemeint? Komplett alle? Oder eines bestimmten Typs?

**Comment by springers54** [comment]
> Frage: welche Beiträge sind heir gemeint? Komplett alle? Oder eines bestimmten Typs?

Hier sind alle Seiten und alle Beiträge drin. Es ist nicht auf bestimmte Rubriken beschränkt

**Comment by joergsteinhauer** [comment]
Ok, habe die Grundfunktionalität aus CherryFramework übernommen, angepasst und entschlankt. Schaue bitte drüber

**Comment by springers54** [comment]
Toll, dass es vom Grundaufbau schon mal funktioniert, prima.
Kannst du das Styling noch etwas angleichen? Im Moment sind die Schriften und Abstände größer, dadurch wird es aber nicht besser lesbar.
![grafik](https://user-images.githubusercontent.com/6114076/48213638-8fa2dd80-e37e-11e8-88e2-dcc6a5d815ed.png)
 neu ist es:
![grafik](https://user-images.githubusercontent.com/6114076/48214330-08ef0000-e380-11e8-9760-0c3aaeb75ab1.png)

 * [ ] Abstände kleiner machen?
 * [ ] Schriften kleiner?
 * [ ] erste Spalte breiter machen?
 * [x] Doppelpunkte oben weg hinter Monat und Betreff

Überschriften scheinen erst mal soweit vorhanden zu sein, jedenfalls h1 und h2

![grafik](https://user-images.githubusercontent.com/6114076/48215281-35a41700-e382-11e8-8b10-f9d1f233415f.png)

Ich habe mir gerade mal ein Addon heruntergeladen, HeadingsMap
kannst du mit den Fehlern etwas anfangen?

**Comment by joergsteinhauer** [comment]
zu **Abstände kleiner machen, Schriften kleiner, erste Spalte breiter machen?**

Also beim besten Willen, aber so wie es ist, ist es doch am Besten. Denn im alten System ist diese Liste sowas von unlesbar. Die Abstände zwischen den einzelnen Listen-Einträgen sind fast genau so hoch, wie der Zeilenabstand - somit sieht man nicht, welcher Text zu welchem Eintrag gehört. Es ist wie ein grauer Block. Das ist sowas von unlesbar.

Im neuen System sind die Abstände zwischen Einträgen mit Absicht größer als der Zeilenabstand, somit sieht man zusammenhängende Blöcke.
Schriftgröße kleiner machen ist schlecht - für Fließtext empfiehlt (nicht nur google) eine mind. Größe von 16px, was wir momentan haben.

Was stört dich denn an der Liste? Dass sie so lang ist? Es ist eben viel Inhalt, es tut ja nicht weh nach unten zu scrollen, aber wohl, wenn der Text nicht lesbar ist.

Und immer wieder: die Orientierung am Styling der alten Seite kann ich echt nicht nachvollziehen - die alte Seite ist teilweise furchtbar gestylt, das Thema hatten wir doch schon mehrmals. Ich empfehle nicht auf das alte System zu schauen, sondern einfach mal User freundliche Lösungen zu entwickeln. Meist ist es nur Gewohnheit, wenn man denkt, dass das neue Design nicht so gut ist. Abwarten und dann wird sich zeigen, dass es besser ist.

**Comment by springers54** [comment]
> Und immer wieder: die Orientierung am Styling der alten Seite kann ich echt nicht nachvollziehen - die alte Seite ist teilweise furchtbar gestylt, das Thema hatten wir doch schon mehrmals. Ich empfehle nicht auf das alte System zu schauen, sondern einfach mal User freundliche Lösungen zu entwickeln. 

Na, ja, ganz teilen kann ich die Meinung nicht. Siehe Startseite, nur im Vergleich sieht man, wo es noch hapert. Uns haben die alten Archivseiten besser gefallen. 

Ich finde, in der Mitte ist Platz verschenkt. Insofern würden für die langen Listen bei einer breiteren ersten Spalte und schmaleren 2. und 3. Spalte für die Lesbarkeit ein Gewinn entstehen, selbst, wenn die Schriftgrößen so bleiben würden.

**Comment by joergsteinhauer** [comment]
Ja, dies Startseite hat tatsächlich noch viele Baustellen, die wir ja auch nach und nach lösen. Aus meiner ersten Sicht fand ich die Startseite persönlich ok, weil ich vom Aussehen der alten Seite nicht beeinflusst war. Ich habe die Seite von null auf nach meinem Gefühl aufgebaut und kann ja anfangs nicht wissen, ob euch das alles so zusagt. Wenn eben etwas nicht passt, sollte das angesprochen werden, ich kann ja alles anpassen. Wie gesagt, das machen wir ja jetzt auch so - alles gut.

Hier auf der Archiv Seite habe ich pragmatisch eine einfache Lösung gebaut - wie sonst überall auch - und zwar eine 3-spaltige Liste, deren Spalten eben gleich breit sind. Das ist ja auch default-Layout, mit dem Hintergedanken, dass diese Liste auch woanders genutzt werden kann und zwar mit anderen Inhalten. 
Wenn es euch nun aber nicht ganz gefällt, dann sollte eher das genaue Problem angesprochen werden, WARUM euch was nicht gefällt bzw. wie man was verbessern könnte. Einfach zu sagen - _alte Seite gefällt uns besser_ - bringt so leider nicht viel, weil mir der Grund nicht gleich klar ist.

Und genau das meine ich - eine klare Aufgaben-Stellung hätte auch hier vieles einfacher gemacht, z.b.:

```
Bitte eine responsive Liste erstellen, die 3 Spalten hat. Achtung aber, die erste Spalte hat mehr Inhalt und sollte bestenfalls mehr Platz einnehmen, damit die Lesbarkeit steigt, sich die 3 Spalten visuell besser trennen und somit Mehrwert für User entsteht. 
```
Wenn ich so eine Aufgabenstellung hätte, wäre mir sofort klar, was warum gemacht werden muss.

-----------

Ich passe die Liste jetzt an bzw. ergänze diese mit dem Extra-Layout. Es funktioniert dann natürlich nur auf dieser Seite. Und generell ist es nicht wirklich ratsam, für jede kleine visuelle oder inhaltliche Abweichung so eine extra Lösung zu bauen. Das sind nur nicht mehr bytes, sondern ist vielmehr die Wartbarkeit des Codes und der diversen Elemente schwer - weniger ist mehr. Zu viele unterschiedliche Sachen machen es schwer, die Software schnell wartbar und erweiterbar zu machen. Man kann dieses Prinzip aus der Typografie abschauen - da sagt man auch, mehr als 3-4 verschiedene Schriftarten/Größen etc. sollte man auf einmal nicht verwenden.

**Comment by springers54** [comment]
ok, diese Seite können wir erst mal so lassen
