### ISSUE TITLE
<p class="title-h2"> wieder erlauben

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#153]
Wir hatten auf der alten Seiten Pseudoüberschriften, weil man vielleicht nicht alle Punkte in einem Inhaltsverzeichnis hat. Diese sind zur Zeit nicht mehr da. Da sie an mehreren Stellen verbaut sind, wäre es sinnvoll, wenn du diese wieder aufnimmst.

**Comment by joergsteinhauer** [comment]
Ich müsste mal wie imemr sehen, wo was verbaut ist. Bräuchte bitte Testlinks!

**Comment by springers54** [comment]
`<p class="title-h3">`
https://reiki-lernen.de/wp-admin/post.php?post=303&action=edit
hier zum Beipiel. Title-h3.
Der Vorteil ist, sieht aus wie eine h3 ist aber keine. Das brauche ich zum Beispiel für das Inhaltsverzeichnis, weil damit Überschriften dort nicht aufgenommen werden. Ansonsten werden die Inhaltsverzeichnisse zu lang.

**Comment by joergsteinhauer** [comment]
Ok, sehe jetzt. Eingefügt. Analog zu `h2` gibts auch alle anderen von `h1` bis `h6`.
