### ISSUE TITLE
Lehrerseite Karin Netzke als Muster

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#154]
Bevor ich alle Lehrerseiten nochmal anfasse und vergleiche, sollten wir die eine Musterseite fertigstellen.
Hier gibt es noch einige Unterschiede im Styling, die wir beheben müssen.
 * [x] Wenn wir ein Inhaltsverzeichnis nehmen wollen, machen wir das wieder über ein Plugin?
 * [x] Bisher hatte jede Lehrerseite so einen Vorspann, der ist weg.
![grafik](https://user-images.githubusercontent.com/6114076/46753813-1fdafd80-ccc1-11e8-8e9c-255a3651b106.png)
 * [x] Auf der neuen Seite hat die Bildergalerie einen seltsamen Abstand, den ich nicht beeinflussen kann. Richtig wäre:
![grafik](https://user-images.githubusercontent.com/6114076/46753878-4d27ab80-ccc1-11e8-8a0b-dd7786a07971.png)
 * [x] Deine Überschriften sowie Titelzeile sind im neuen Layout nicht lesbar: alt war es:
![grafik](https://user-images.githubusercontent.com/6114076/46753934-75afa580-ccc1-11e8-8c16-2a81666ed0c7.png)

neu ist es:
![grafik](https://user-images.githubusercontent.com/6114076/46753960-852eee80-ccc1-11e8-8bce-b73afa221d23.png)

**Comment by joergsteinhauer** [comment]
* Inhaltsverzeichnis funktioniert über ein JS Plugin, muss ich noch implementieren.

* Vorspann kam aus einem Custom-Admin-Widget, der Cherry Framework mitlieferte. 
Dies kann ich leider nicht nabilden bzw. nachbauen, zu komplex. Optional wäre möglich, diese Textschnipsel manuell beim jedem Lehrer im Artikel einzutragen.
![grafik](https://user-images.githubusercontent.com/1843754/47114121-3baf4800-d25b-11e8-85f6-decaf24a95fc.png)

* Abstand vor der Galerie kommt eben durch Elemente, die die Galerie mitliefert. Anscheinend funktioniert hier etwas nicht korrekt, sodass das Layout zerschossen wird. Der Plugin "WP Media folder" liefert die Möglichkeit, für eingefügte bilder im Artikel Galerien und Lightboxen zu aktivieren. Und eben bei der Galerie-Option kracht es. Ich hab schon 15 min lang gesucht, bis jetzt nicht rausgefunden, wie man das löst. Soll ich mehr Zeit damit verbringen? 
Viel lieber hätte ich die Galerie-Option deaktiviert und auf dieses Galerie-Feature verzichtet. Man hätte dann eine einfache Auflistung der Bilder, ohne diese Slider effekt. Lightbox würde weiter gehen, zumal wir für Lightvox noch einen weiteren Plugin haben.
![grafik](https://user-images.githubusercontent.com/1843754/47114346-db6cd600-d25b-11e8-8b0b-7409e06a77b9.png)

* Überschriften beim Formular habe ich angepasst, hier war das Markup der Formular-Box noch das alte. Ich habe die Problematik bereits in einem anderen Issue erwähnt:

ALT:
```html
<div style="background-color: #374047; padding: 20px;">
<h6>Kontakt zu Reiki-Lehrer Karin Netzke</h6>
[contact-form-7 id="2813" title="Lehrer contact form_Karin"]
</div>
```

NEU:
```html
<div class="zr-box-contact">
<h6>Kontakt zu Reiki-Lehrer Karin Netzke</h6>
[contact-form-7 id="2813" title="Lehrer contact form_Karin"]
</div>
```

**Comment by springers54** [comment]
>     * Inhaltsverzeichnis funktioniert über ein JS Plugin, muss ich noch implementieren.

das kann ich auch machen, dann  nehmen wir das alte Plugin einfach wieder?

>     * Optional wäre möglich, diese Textschnipsel manuell beim jedem Lehrer im Artikel einzutragen.

Ja, das wäre kein Porblem, muss ich nur wissen, wie es geht und formatiert werden muss. Es darf nicht mit Überschriften gemacht werden, da sonst die Hierarchie durcheinander kommt, ich kann nicht nach einer H1 eine h6 bringen wollen.

>     * Soll ich mehr Zeit damit verbringen?
>       Viel lieber hätte ich die Galerie-Option deaktiviert und auf dieses Galerie-Feature verzichtet. Man hätte dann eine einfache Auflistung der Bilder, ohne diese Slider effekt. Lightbox würde weiter gehen, zumal wir für Lightvox noch einen weiteren Plugin haben.

Ich habe auf Testseite Jörg die möglichen Galerien eingefügt. Zuvor die neueste Version des Plugins installiert und auch dein Plugin deaktiviert. Leider hat das keinen Effekt gehabt.
Ich bin nicht dafür außer mediafolder ein weiteres Plugin zu installieren, was die Lightboxen bringt. Das ging vorher ohne und sollte auch hinterher ohne gehen.
Ich habe in Ticket geschrieben bei Joomunited, schließlich ist das eine Kaufversion, da sollen die sich drehen.
Nein, dort erst mal keine Zeit investieren, sollte es nicht gehen, dann weichen wir auf die Masonry-Option aus.
![grafik](https://user-images.githubusercontent.com/6114076/47132908-a89bff80-d2a6-11e8-95b8-1b5c681569fa.png)

**Comment by joergsteinhauer** [comment]
- Textschnipsel habe ich eingefügt, dafür auch gleich ein neues Format im Editor erstellt (`Beschreibung`). Es ist ein einfahcer Pagagraph, was auch semantisch korrekt ist.

![grafik](https://user-images.githubusercontent.com/1843754/47181817-44b81c00-d324-11e8-9c10-33613592056a.png)

- Inhaltsverzeichnis: ja, stimmt, das war doch ein WP Plugin: https://de.wordpress.org/plugins/table-of-contents-plus/

- Lightbox Plugin, was du deaktiviert hast, war notwendig z.B. für die großen Lehrer Bilder auf der Startseite. Auf der alten ZR Seite greift bei den Lehrer-Bildern die mit Cherry mitgelieferte Lightbox. Nun haben wir ja kein Cherry auf der neuen Seite. Hier kann ich bei den Lehrer-Bildern leider nicht die Lightbox vom "WP Media folder" Plugin anwenden. Also brauche ich eine andere Lightbox, in diesem Fall war es die "Featherlight". 
Also entweder wir aktivieren das Plugin wieder oder es gibt keine Lightbox für die Lehrer-Bilder.

Ja, mal sehen was Joomunited zum Fehler sagt. Masonry ist aber auch ok, wobei hier viel mit JS nachjustiert wird, d.h. die Performance leidet und nicht zu wenig! Ich würde heir empfehlen, eine einfache Galerie ohne zusätzlichen JS anzuwenden, die ich aber noch zusätzlich mit CSS schön aufbereiten könnte.

**Comment by springers54** [comment]
> Ja, mal sehen was Joomunited zum Fehler sagt.

Der Fehler ist behoben. 


>     * Also entweder wir aktivieren das Plugin wieder oder es gibt keine Lightbox für die Lehrer-Bilder.

habe ich wieder aktiviert, ich dachte, die beeinflussen sich gegenseitig.
Mit der Unterzeile können wir das so machen.


>     * Textschnipsel habe ich eingefügt, dafür auch gleich ein neues Format im Editor erstellt (`Beschreibung`). Es ist ein einfahcer Pagagraph, was auch semantisch korrekt ist.

Ich arbeite **NIE** im visuellen Editor, dafür bin ich zu sehr Programmierer und muss genau sehen, was passiert. Saubere Seiten bekommt man nur im Texteditor. Daher kannst du allen Schnick hier weglassen, weil das keiner nutzt. Ich brauche eine ordentliche Liste mit Styling-Regeln 
`<p class="zr-text-description">Zen-Reiki-Lehrer seit 2005</p>`
reicht also vollkommen aus.

**Comment by springers54** [comment]
* [x]  wir brauchen wieder die Überschriften, die vorne anfangen. War im alten System
`<h2 class="clear-fix">Botschaft an meine Schüler</h2>`

Ich habe jetzt nochmal beide Seiten verglichen im alten und neuen System und die von Karin sieht schon ziemlich gut aus. Das Zitat ist anders, da nur die Kennung vorne ist, gefällt mir aber sogar besser so auf der neuen Seite.

**Comment by joergsteinhauer** [comment]
- Super, wo war das Problem beim Slider? Bei uns oder beim Plugins selbst?
Ich habe gesehen, dass beim Hover die Unterschriften schlecht formatiert sind, habe es gleich etwas optimiert:
![grafik](https://user-images.githubusercontent.com/1843754/47238609-06cdfd00-d3e3-11e8-8958-bc7b10d9241f.png)

- Ja, also die Lightbox Plugins kommen sich tatsächlich in die Quere - besser gesagt, by default werden zwei Lightboxen gestartet. Allerdings liefert das Featherlight-Plugin gleich eine Option auf jeder Seite, mit der man dieses Plugin für die jeweilige Seite deaktivieren kann. so habe ich es z.B. auch auf der Lehrerseite deaktiviert, wo ja das WPMF Lightbox greift:
![grafik](https://user-images.githubusercontent.com/1843754/47238735-675d3a00-d3e3-11e8-8cbb-785fccb1159b.png)

- Visueller Editor: Wow, das ist sogar besser so! Gefällt mir, wusste ich gar nicht. Dann macht es so einiges einfacher. 

- was meinst du mit "die vorne anfangen"? Verstehe ich nicht ganz. Ich sehe auf der alten und neuen Seite diese Überschrift "Botschaft an meine Schüler", aber die sehen doch gleich aus?

**Comment by springers54** [comment]
>     * Super, wo war das Problem beim Slider? Bei uns oder beim Plugins selbst?

bei denen und die haben es sehr schnell gefixt

>     * Ich habe gesehen, dass beim Hover die Unterschriften schlecht formatiert sind, habe es gleich etwas optimiert:

Das ist gut, war recht schlecht zu lesen bisher.

>     * so habe ich es z.B. auch auf der Lehrerseite deaktiviert, wo ja das WPMF Lightbox greift:

so können wir es auch machen. Wäre es umgekehrt nicht sinnvoller, das andere Plugin nur für die Startseite und die Lehrerseite zu aktivieren?


>     * Visueller Editor: Wow, das ist sogar besser so! Gefällt mir, wusste ich gar nicht. Dann macht es so einiges einfacher.

Es geht noch weiter. Versuche am besten nie, im visuellen Editor zu arbeiten, zu speichern und dann in den Texteditior zurückzuschalten. Da kommt teilweise so ein Murks in die Seite, dass ich das ganz schnell gelassen habe. Bequemlichkeit ist nicht alles.


>     * was meinst du mit "die vorne anfangen"? Verstehe ich nicht ganz. Ich sehe auf der alten und neuen Seite diese Überschrift "Botschaft an meine Schüler", aber die sehen doch gleich aus?

Das hängt von deinem Bildschirm ab. 
![grafik](https://user-images.githubusercontent.com/6114076/47288808-05c1e900-d5f8-11e8-97b9-eb85db3eb6a2.png)
Der Code war nur von meiner Styling-Liste kopiert, ist also auf Karins Seite an einer anderen Stelle. Bei Bildern brechen die Überschriften teilweise falsch um, darum diese class=clearfix von dir

**Comment by joergsteinhauer** [comment]
> Wäre es umgekehrt nicht sinnvoller, das andere Plugin nur für die Startseite und die Lehrerseite zu aktivieren?

Ich sehe beim "WP Media Folder" Plugin dafür leider keine Option. Also nein, das geht nicht.

> Versuche am besten nie, im visuellen Editor zu arbeiten, zu speichern und dann in den Texteditior zurückzuschalten. 

Ja, das kenn ich ganz gut. Ich ging davor halt immer aus, dass du/ihr die Artikel im Editor-Modus ändert, daher habe ich es teilweise auch so gemacht. Aber nun ist geklärt, wir arbeiten ab jetzt immre im Text-Modus.

> [...] darum diese class=clearfix von dir

Ich sehe immer noch nicht, wo diese clear-fix Klasse auf der alten Seite implementiert ist. Kann sein, dass ich es dortt mal eingefügt habe. Problem ist aber klar - einige Texte, vor allem Überschriften, die nach einem links/rechts ausgerichteten Bild folgen, brechen nicht um. Normales float-Dilemma. Der Text/Überschrift bleibt eben im "Fluß" und legt sich "um das Bild herum". Dafür ist der "float" ja auch da. Nur sieht das manchmal komisch aus. Da gibts eben die Variante, dass man die betreffende Überschrift "cleared", sodass sie in einer neuen Zeile anfängt. Habe ich am Bsp der Karin's Seite eingsetzt. du kannst es gern weiter benutzen. 
Allerdings ist imemr Acht gebeten: Manchmal ist die Textlänge kleines bisschen länger als das Bild und wenn man dann clear-fix benutzt, entstehen zu große Lücken zwischen den Texten:

![30825ad9c1441ab8330b7db59d9ac03b](https://user-images.githubusercontent.com/1843754/47603614-e1e31680-d9ee-11e8-80a8-b7a8a4774e16.gif)

**Comment by springers54** [comment]
Ich habe das Plugin von Inhaltsverzeichnis eingefügt und versucht, einzustellen.
Folgende Probleme treten auf:
 * [x] Inhaltsverzeichnis steht zu weit oben, es ist nach der ersten Überschrift ausgerichtet. Schön wäre es, wenn es erst im Text beginnen würde, wie auf der alten Seite. Man kann zwar in den erweiterten Einstellungen auch einen Versatz von oben definieren, aber ich weiß nicht, was dann auf Mobiltelefonen passiert. Der Versatz steht jetzt auf 30Px, dann müsste man die Ausrichtung auf oben setzen und den Versatz größer machen.
 * [x] Dein Springproblem ist mir klar, ist halt so. Man kann nicht alles haben. Irgendwo ist es immer ein Kompromiss
 * [x] Die Struktur der Überschriften stimmte nicht im Kontaktbereich, da sprang es von H3 auf H5, ich habe das nun geändert.
```
`<h3>Bildergalerie von Reiki-Lehrer Karin Netzke</h3>
[gallery link="file" columns="5" display="slider" ids="2851,2852,2854,2853,2850"]
<h4>Fragen? - Kontakt aufnehmen </h4>
<div class="zr-box-contact">
<p class="title-h6">Kontakt zu Reiki-Lehrer Karin Netzke</p>`
```

Leider ist damit die gelbe Schrift wieder verschwunden. vielleicht kann man hier eine Klassenerweiterung machen class="title-h6-gelb"

**Comment by joergsteinhauer** [comment]
Problem mit dem Inhaltsverzeichnis gestaltet sich schwieriger, als gedacht. In Plugin Einstellungen kann man die Position des TOC bestimmen, leider nur bedingt - so ist für uns das Optimalste die Position direkt nach der ersten Überschrift, alles andere macht keinen Sinn. 

Leider haben wir aber im neuen System die "text-description" (`Zen-Reiki-Lehrer seit YYYY`) direkt unter der ersten Überschrift, sodass der TOC sich zwischen die Überschrift und die "text-description" schiebt.

Ich kann also keine dynamische Lösung per CSS für solchen HTML-Aufbau erstellen. Ein weg wäre, wenn diese "text-description" IN die Überschrift hinein wandert, also so:

```html
<h2>Über mich: Karin Netzke: Reiki-Lehrer <span class="zr-text-description">Zen-Reiki-Lehrer seit 2005</span></h2>
```

Ich finde es sogar Seo-Technisch besser, denn eine aussagekräftigere Überschrift ist besser.

Schaue also bitte drüber, ob das so passt - dann müsste man das auch entsprechend auf allen anderen Lehrer-Seiten anpassen.

Zusätzlich ist das TOC Plugin nicht wirklich responsive, ich habe das noch etwas optimiert für unseren Fall.

**Comment by springers54** [comment]
Das sieht für mich super aus so. Passen wir dann für die anderen Seiten einfach an.

**Comment by springers54** [comment]
Bin jetzt nochmal an der Grundstruktur der Lehrerseiten dran.
![grafik](https://user-images.githubusercontent.com/6114076/48246053-265ab300-e3ee-11e8-9da8-8cf5dc452276.png)
 *  [x] 1 - Wäre es möglich, anstelle von team lehrer zu verwenden? Denn sonst stimmen alle alten Links nicht, wenn wir umschalten.
 * [x] 2 - Ich habe die Seite jetzt mit einer H1 begonnen, optisch haut das soweit hin.
Allerdings zeigt er immer noch einen Strukturfehler an.
 * [x] 3 - Wir haben jetzt 2 H1, was auch nicht sein darf. Die ausgeblendete H1 muss komplett weg


![grafik](https://user-images.githubusercontent.com/6114076/48246462-d4b32800-e3ef-11e8-9754-073dccd46bd0.png)

![grafik](https://user-images.githubusercontent.com/6114076/48246629-6d49a800-e3f0-11e8-92c5-6fdf3a633fc7.png)

**Comment by joergsteinhauer** [comment]
2. Ja, du hast quasi im content die H1 manuell eingefügt. Das ist suboptimal. Jedes CMS nutzt für die H1 den Titel des Beitrags / der Seite:

![grafik](https://user-images.githubusercontent.com/1843754/48290941-ec80bf80-e474-11e8-9a2c-5cfe56d1ec8a.png)

Dieser titel sollte dann auch wirklich für die H1 genommen werden, das is die Core-Funktionalität und die sollte nicht umgangen werden.

Ich würde hier vorschlagen, die H1 aus dem Content rauszunehmen, statt dessen nur den Zusatztext "Zen-Reiki-Lehrer seit 2005" direkt drunter als H2 mit einem passenden Styling zu setzen:
```html
<h2 class="title-h5">Zen-Reiki-Lehrer seit 2005</h2>
```

Würde dann so aussehen:
![grafik](https://user-images.githubusercontent.com/1843754/48291133-982a0f80-e475-11e8-965c-a24b11a2d7bb.png)

**Comment by joergsteinhauer** [comment]
Habe auch hier nun den Inhalt angepasst, also die H-Titel. 

H1 kommt aus dem Seitentitel, den Rest habe ich geändert jeweils eine Stufe runter (H2-H3 usw.), die Struktur ist jetzt korrekt und sieht so aus:

![image](https://user-images.githubusercontent.com/1843754/48917328-7d4c9780-ee86-11e8-8cd8-3adaa3e1ba29.png)

Man kann hier aber je nach Wunsch noch alles anpassen, zusätzlich auch noch über die CSS-Titel-Klassen (z.b. `.title-h3`).

Bleibt erstmal übrig: Slug von `team` auf `lehrer` ändern

**Comment by joergsteinhauer** [comment]
So, Permalinks (also `slug`) für den "Team-Posttype" ist nun auch geändert von `team` zu `lehrer`.

Als Info: es hat nicht gereicht, einfach den Slug in der WP Action zu ändern:
![image](https://user-images.githubusercontent.com/1843754/48918734-d91b1e80-ee8e-11e8-9641-88568309900d.png)

Man musste zusätzlich noch alle Permalinks im WP neu einlesen (flush). Dazu geht man in "Einstellungen" -> "Permalinks" und klickt auf "Speichern", ohne dabei irgend etwas geändert zu haben.

**Comment by springers54** [comment]
prima, dann ist dieses Problem vom Tisch.
Nochmal zur Musterseite:
![grafik](https://user-images.githubusercontent.com/6114076/48949916-e04b3680-ef39-11e8-86d7-71f9fe6fc72d.png)

Seitentitel ist die H1, diese Unterzeile sieht aber aufdringlicher aus als früher. Kannst du das noch anpassen?

![grafik](https://user-images.githubusercontent.com/6114076/48949990-096bc700-ef3a-11e8-9297-a9f651c20acd.png)
Die Überschriften stimmen von der Struktur erst einmal

Er zeigt aber bei document und nav immer noch rot an.
![grafik](https://user-images.githubusercontent.com/6114076/48950046-2e603a00-ef3a-11e8-8231-fa056738521a.png)
Bekommst du das noch weg?

**Comment by joergsteinhauer** [comment]
Ich bin erstmal auf ein anderes Problem gestoßen:

Die Startseite war etwas zerschossen:
![image](https://user-images.githubusercontent.com/1843754/48968462-6629b900-eff0-11e8-98d2-9fa90c55e5f0.png)

Das kommt durch das HTML im Seitentitel:
![image](https://user-images.githubusercontent.com/1843754/48968455-5e6a1480-eff0-11e8-9e1a-4fc9e8353582.png)

Auch wenn das HTML auf der eigentlichen Lehrerseite funktioniert, sollte man sowas nicht machen. Eingabefelder, die nicht für Inhalt gedacht sind (so eben z.b. Titel, Datum etc pp) sollten nur reinen Text enthalten.

Denn solche Sachen, wie Titel etc, werden dann weiter im Template für diverse Sachen verwendet. Deswegen kracht es dann auch, wenn auf einmal HTML-Schnipsel rauskommen.

Mein Vorschlag: HTML aus dem Seitentitel entfernen und das `Zen-Reiki-Lehrer seit 2005` direkt im Inhalt ausgeben. Ist dann eben eine H2:
![image](https://user-images.githubusercontent.com/1843754/48968526-ff58cf80-eff0-11e8-8b34-eb8428efd177.png)

**Comment by joergsteinhauer** [comment]
Das Problem mit "HTML 5 Outline" können wir vernachlässigen.

Erstens ist dieses Feature in keinem Browser integriert, obgleich es aber bereits in W3C definiert ist:
https://www.w3.org/TR/2017/REC-html52-20171214/sections.html#creating-an-outline

In Plugin Einstellungen gibts auch mehr nazulesen. Ich empfehle dieses Feature im Plugin zu deaktivieren:
![image](https://user-images.githubusercontent.com/1843754/48968660-d2a5b780-eff2-11e8-83e6-085696579b23.png)

Ich habe mich zu der ganzen Problematik kurz eingelesen, aber so richtig ist mir noch nicht klar warum und wozu das ganze ist... Ist mir gerade auch zuviel unnötiger Aufwand, da dieses Feature zu vernachlässigen ist.

Zweitens ist das Markup trotzdem valide.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/48976408-4b565380-f087-11e8-9df7-f20b882efe7c.png)

Also so geht es nicht, das meinst du doch nicht ernst, oder?

**Comment by springers54** [comment]
ich habe jetzt aus deiner h2 ein p gemacht, dadurch ist es etwas besser,
Zumindest ist das Inhaltsverzeichni wieder unten
![grafik](https://user-images.githubusercontent.com/6114076/48976432-ebac7800-f087-11e8-9d6a-62fb63eb01f9.png)

Aber gefallen tut es mir nicht. Weil der Abstand zur H1 einfach da ist und damit das nicht mehr wie eine Unterzeile aussieht, so wie es früher war. Wie können wir dieses Problem lösen?

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/48976487-f1568d80-f088-11e8-975d-c55018747680.png)
ich habe jetzt die 2. H2 wieder weggenommen. Dann muss ich aber as dem p wieder eine H2 machen, damit das Inhaltsverzeichnis an der richtigen Stelle bliebt.
Ich glaube, damit kann ich leben. Ich lasse Dani nochmal draufgucken.

**Comment by joergsteinhauer** [comment]
Dich störte die Position des Inhaltsverzeichnisses? 

Ich sehe hier 3 Sachen, die aufeinander prallen und wir müssen hier einfach einen Kompromiss finden, mit dem vor allem du leben kannst:
1. HTML im titel ist nicht zulässig, HTML musste dort also weg
2. H-Titel Struktur muss sinnvoll sein und valide
3. Inhaltsverzeichnis fängt nach der ersten Überschrift an -> hier haben wir nicht allzu viel Spielraum

Für mich gilt wie immer Funktionalität vor Desing -> zuerst müssen wir dafür sorgen, dass die technische Basis korrekt ist, also:
1. H-Titel Struktur muss passen
2. kein HTML im titel

Danach können wir am Design optimieren.

Ich habe doch keinen Plan, was mit dem `Zen-Reiki-Lehrer seit 2005` passieren soll - soll das ein H-Titel sein oder einfacher Text?  Wenn es ein H-Titel ist, taucht es dann im TOC auf - macht das Sinn? Also entscheide du, mache bitte das Markup so wie es semantisch Sinn macht und beim Styling ist doch viel möglich -> das kann ich dann optimieren.

**Comment by springers54** [comment]
Das einzige, was mich stört ist der Abstand der Unterzeile zur H1 und ja, im Inhaltsverzeichnis muss die Zeile eigentlich auch nicht aufscheinen. Wenn ich die Zeile als Überschrift ausblende, was möglich ist, dann ist aber die Position des Inhaltsverzeichnisses weg, Geht also auch nicht.
Aber es ist so und wir können damit leben. Darum sollten wir das schließen und hier nicht weiter Zeit investiren.
