### ISSUE TITLE
Systeme (Post Type: Solutions)

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#155]
ALT:
https://zen-reiki.de/system/

NEU:
https://reiki-lernen.de/system/

Für die Systeme-Seite muss auch noch einiges implementiert werden:

- [x] Post type `solutions`
- [x] Styling "Service Box"
- [x] Styling "Parallax Box"
- [x] Styling "Weitere Systeme"

**Comment by springers54** [comment]
Importiert habe ich die Inhalte, nun kannst du dich an das Styling machen. 

- [x] das Wording wäre hier **systeme**

Kannst du danach einfach diesem Posttyp umbenennen? Denn importieren werden wir dann nicht mehr, sondern diese Seiten parallel pflegen

**Comment by joergsteinhauer** [comment]
Posttyp ändern wird schwierig. So wie ich es vermutet habe, sind die Einträge in der BD unter "solutions" abgelegt. Heißt, man müsste in der DB die posttypen auch ändern. Das ging ohl mal mit einem Plugin, aber ejtzt nicht mehr. Es bliebe nur ein weg über manuelle MySQL Scripte:
https://wordpress.stackexchange.com/questions/97026/how-do-i-safely-change-the-name-of-a-custom-post-type/129537#129537

Frage mich aber, ob das unbedingt sein soll? Was spricht dagegen es weiterhin bei "solutions" zu lassen? Ist ja dan nur der Posttyp... die Labels heißen ja alle "Systeme"

**Comment by springers54** [comment]
ich dachte nur wegen der Einheitlichkeit oder dem besseren Verständnis. Ansonsten ist es egal, wir werden es in der Datenbank schon finden. Solutions und Systeme haben ja wenigstens noch eingen gewissen geistigen Bezug, was man bei News und Credo eher nicht sagen kann.

Die Vorschau sieht schon gut aus, allerdings funktionieren die Links nicht auf die weiteren Systeme

 * [x] Weitere Systeme mit den Seiten verlinken

**Comment by joergsteinhauer** [comment]
Gut, dann lassen wir es bei "solutions". Ist sonst zu viel Aufwand.

Stimmt, Links zu System-Seiten habe ich übersehen, ist erledigt.
