### ISSUE TITLE
Fußzeile in Beiträgen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#156]
Beiträge haben eine eigenständige Fußzeile:

Siehe:
https://reiki-lernen.de/category/coaching/

![grafik](https://user-images.githubusercontent.com/6114076/47727894-94b8ac00-dc5d-11e8-87da-cf8cb4c09de3.png)

Generell sollte diese Zeile einheitlich aussehen mit den Elementen:

- Datum
- Autor
- Rubrik
- Kommentar

Weitere Dinge, werden hier nicht angezeigt. Mit Schlüsselwörtern arbeite ich nicht, die könnten auch komplett raus, weil die Suche das auch hergibt.

 * [x] überflüssige Elemente entfernen oder ausblenden
 * [x] Sprache deutsch, also Kommentare oder Kommentieren wenn es noch keine Kommentare gibt.

**Comment by joergsteinhauer** [comment]
So wie ichs sehe, müssen nur die "Tags" entfernt werden.
