### ISSUE TITLE
Ausrichtung Überschriften

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#157]
Sollten im rechten Seitenteil und im Contentbereich auf der gleichen Höhe sein.
![grafik](https://user-images.githubusercontent.com/6114076/47728428-9b93ee80-dc5e-11e8-8242-2f58cbb66c78.png)

https://reiki-lernen.de/system/kundalini-reiki/

**Comment by joergsteinhauer** [comment]
Erledigt
