### ISSUE TITLE
Seitebreite Ganzseite max 1200 px?

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#158]
Die alte Seite ist schmaler eingestellt als die neue, was immer wieder Probleme macht
![grafik](https://user-images.githubusercontent.com/6114076/47806477-2c8bc800-dd3a-11e8-9d24-e5cd38f221f8.png)

Die Bannerbilder sind mit 1200 px angelegt, wie man sieht, ist das noch zu schmal. Wäre es  ein Problem, die Ganzseite auf diese Breite zu beschränken?

**Comment by joergsteinhauer** [comment]
Genau, die neue Seite ist breiter, ich habe sie eben gleich vom Anfang an an das heutige Standard angepasst. Es macht einfach Sinn, den gegebenen Platz auszunutzen.

Es ist aber kein Problem, die Seite schmaler zu machen. Ich probiere es demnächst, sollte ohne große Hürden zu machen sein.

**Comment by joergsteinhauer** [comment]
Sollte erledigt sein
