### ISSUE TITLE
Seitentitel - verstecken oder anzeigen

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#159]
Im Laufe der Umsetzung kam imemr wieder der Wunsch, die H1 Titel zu verstecken. Dies habe ich global per CSS gemacht. Mittlerweile stellt sich heraus, dass die H1 Titel nicht auf jeder Seite versteckt werden sollen.

Problem 1:
Dieses hin und her, verstecken/anzeigen je nach Seite, ist ziemlich verwirrend und nicht immer optimal umsetzbar. Es ist einfach fehleranfällig, da man die Titel z.z. nur per CSS ausblenden kann. Dafür muss man diverse CSS Logiken aufbauen, die aber nicth stabil sind.

Problem 2:
Es ist nicht gerade klug, die wichtigste Überschrift zu verstecken. Warum überhaupt? 

Weil sie groß ist und "unschön" aussieht? Dann sollte man es schöner machen und design technisch besser ins Layout integrieren bzw. dafür sorgen, dass diese Überschrift sich nicht mit anderen Seiten-Elementen beißt. Vielmehr sollte man also hier den Inhalt der Seite anpassen.

Oder weil sie nicht den passenden Text enthält? Dann sollte da ein passender Text rein.

Design sollte nie über die Funktionalität gehen. So ist eine fehlende Überschrift immer eine Nachteil der Usability. Allein schon, dass man irgendwas ausblenden, spricht dafür, dass der Content nicht optimal aufgebaut ist. 

Verstecken ist in jedem Fall eher falsch.

---------------------

Es gäbe also aus meienr Sicht folgende Problemlösungen:

1. Einsetzen eines Plugins, mit dessen Hilfe man die Schriften eifach nicht ausgibt - das ist aber schlecht für Seo, denn da würde die H1 fehlen und das ist GAAANZ schlecht für google... Mit diesem Plugin würde es gehen: https://wordpress.org/plugins/hide-title/

2. H1 Tittel nicht verstecken, sondern viel mehr die Inhalte der Titel anpassen und besser ins Layout integrieren.

---------------------

Vlt. ist mir etwas nicht bekannt bzw. ich habe was übersehen, dann bitte darauf hinweisen :-)

**Comment by springers54** [comment]
1. Auf der Homeseite wirkt der Seitentitel in H1 komplett daneben.

2. Auf anderen Seiten ist die H1 einfach durch die Bezeichnung im Link gesetzt, passt aber nicht zur Seite, Die Links dürfen auch nicht zu lang sein. Die Seite beginnt dann mit der H2 .

3. Ich glaube, es würde zuviel vom Konzept jetzt ändern, wenn wir das grundlegend auf den Kopf stellen.

4. H1 fehlend geht gar nicht und die Struktur der Überschriften muss auch stimmen. Darum beginnen meine Seiten eigentlich immer mit einer H2, da die H1 ja weg ist. Aber eben nur in der Ansicht, nicht in der Seitenstruktur.

5. Bei den Seiten, wo es nicht passt, müssen wir uns was einfallen lassen. Eine andere Idee habe ich momentan nicht.

**Comment by joergsteinhauer** [comment]
1. Auf der Startseite macht man es oft etwas anders: die H1 ist dann das Logo im Header und ist dann nicht mehr im Content vorhanden. so würde ich es machen.

2. 

> Auf anderen Seiten ist die H1 einfach durch die Bezeichnung im Link gesetzt

Das verstehe ich jetzt nicht ganz, wie meinst du das?

3. Vom Konzept würde das nicht viel ändern:
- rein visuell müsste man eben überlegen, wie und wo so eine H1 am besten rein passt. Wenn ich alle Details kenne, kann ich ja einen Vorschlag machen.
- rein strukturell (HTML) würde das auch nicht viel ändern, denn sowohl jetzt als auch danach wären alle H-Titel im Markup

4. Korrekt - H1 darf nicht fehlen. Auch per CSS zu verstecken ist nicht gut. Es gibt viele Diskussionen dazu, ob es SEO-technisch gut ist, Sachen per CSS zu verstecken - ich bin kein Freund davon. Ich finde - wenn schon was wichtiges im Markup ausgegeben wird, muss es auch sichtbar sein. Man muss es nur passend gestalten und layouten.

5. Genau, das machen wir. Ich gehe alle Seiten durch und bringe Vorschläge.

**Comment by springers54** [comment]
Also prinzipiell bin ich bei dir, wenn wir etwas verbessern können und Fehler, die im alten System gemacht wurden, aus der Welt schaffen, selbst, wenn das mit Aufwand verbunden ist.

Ich habe bisher fast alle Seite mit einer H2 begonnen. Die H1 wird durch den Seitentitel vergeben, aber fast nie angezeigt.

Die H1 müsste dann vom Styling der H2 entsprechen. Weil sie fast immer neben dem rechten Seitenbereich und dem Wort Themen steht. Sie sollte nicht größer sein.

Im alten System hatten wir teilweise gar keinen Einfluss auf die interne Verarbeitung, das haben wir jetzt aber.

Wichtig ist, dass wir sie nicht auf der Startseite haben, wenn du sie dort im Logo verstehen kannst, ist alles gut.

 * [ ] @joergsteinhauer : Vorschlag zum Styling, so dass die Integration möglich ist in den verschiedenen Post-Typen
 * [ ] @springers54 @Dani2909 : Seiten durchgehen, Posts durchgehen und aus der ersten H2 eine H1 machen.
