### ISSUE TITLE
Überschriftenstruktur: Grundsatzentscheidung

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#160]
Ich glaube, wir sollten uns hierzu grundlegend verständigen
![grafik](https://user-images.githubusercontent.com/6114076/48215838-6d5f8e80-e383-11e8-87c1-53eea0ab4305.png)
Dieses Bild ist von der Seite https://reiki-lernen.de/system/usui-reiki/

Was fällt auf?
 * [x] h1 fehlt, wird uns jeder um die Ohren hauen
 * [x] zu viele h2, ohne dass dort ein Text folgt, ich glaube, das mag auch keiner

Mein Vorschlag: den rechten Seitenbereich nicht mit Überschriften ohne Inhalt vollpfropfen. Eventuell Themen noch als H2, dann müssten die Einzelthemen aber h3 sein, damit es überhaupt einen Sinn hat.

**Comment by joergsteinhauer** [comment]
Meinst du zu viele H2 in der Sidebar? Ja, da sind nur H2, aber die sind jeweils in einer eigenen Section und haben doch alle entsprechende zugeordnete Inhalte - Listen etc. Da ist alles ok.

Die H1 muss auf jeden Fall rein.

**Comment by joergsteinhauer** [comment]
Ich habe jetzt nachgeschaut, wie die Struktur ist: die H1 fehlt, muss aber unbedingt rein. Am Besten ist es, wenn die erste Überschrift als H1 gesetzt ist. Und nicht der Logo-Text oder so. Denn eine "unique" H1 pro Seite ist viel besser als immer die gleiche H1 auf jeder Seite.

Im Falle von https://reiki-lernen.de/system/usui-reiki/ wäre das dann "Vorbemerkungen und Historie zu Usui-Reiki".

Nun leider ist diese Überschrift eine H2, danach kommen die vielen H3:
![image](https://user-images.githubusercontent.com/1843754/48737697-037e9900-ec4f-11e8-8ea8-cf1b869ab612.png)

Das ist ziemlich ungünstig. Denn das würde bedeuten, dass man auf jeder Seite im Content manuell alle H2 zu H1, H3 zu H2 usw. ändern müsste. Wäre denn das eine Option für dich? Ich vermute, alle Seiten manuell anzupassen ist Nonsens.

Eine andere Variante wäre, fest im WP-Template eine H1 oberhalb des Contents einzuführen. Somit würde dieser vor den H2 auftauchen. Allerdings wäre das dann sicherlich immer der gleiche Text (den wir erst definieren müssten) und würde somit weniger SEO-Vorteile bringen.

Was machen wir also?
1. manuell auf jeder Seite die H-Titel ändern
2. H1 fest im Template oberhalb des Contents einführen - man könnte hier auch das Logo und dessen Text als H1 definieren.

**Comment by springers54** [comment]
Es macht uns nichts aus, alle Seiten manuell zu ändern. Das ist eine Fleißarbeit, aber es sind ja nicht hunderte Seiten. Außerdem müssen wir ohnehin jede Seite einzen sauber durchsehen, ob sie noch Fehler durch die Umstellung hat.
Ich halte eine geänderte H1 pro Seite auf jeden Fall für sinnvoller als eine feste H1 für alle Seiten.

Mein Problem ist eher ein anderes. Ich hatte es bisher so verstanden, dass der Titel der Seite gleichzeitig die H1 ist, diese nur nicht dargestellt wurde.
![grafik](https://user-images.githubusercontent.com/6114076/48755831-09986800-ec97-11e8-99fb-02909b21bef8.png)

Mir wäre folgende Lösung am liebsten:
 * [x] der Seitentitel hat gar keine Bedeutung als Überschrift, er wird nur für den Link verwendet
 * [x] ich habe volle Kontrolle über alle Überschriften, also ich beginne generell mit einer H1 auf der Seite und stufe dann runter
 * [x] Jede Steite beginnt oben mit der H1-Überschrift, die aber vom Styling der H2 entspricht, da diese ja im rechten Menü verwendet wird
 * [x] Homesite hat keine sichtbare Überschrift, da ist sie im Logo verankert

![grafik](https://user-images.githubusercontent.com/6114076/48756008-c4286a80-ec97-11e8-9f86-c8155da0de3e.png)

Kannst du das so umsetzen?

**Comment by joergsteinhauer** [comment]
Ok, also alle Sachen sind an sich umsetzbar, nur bei dieser hier sehe ich keinen Sinn:

> der Seitentitel hat gar keine Bedeutung als Überschrift, er wird nur für den Link verwendet

Zur Erklärung: ich kenne viele CMS und sie alle geben im Markup den Seiten-Titel als H1 aus - es steckt schon ein guter Vorsatz dahinter. Man hab eben eine Überschrift für eine Seite und genau die sollte die (Markup-technisch) die wichtigste Überschrift sein (H1). Somit spart an sich doch eher die Arbeit, irgendwelche Custom-titel dann direkt im Content zu setzen. 

Oder warum möchtest du unbedingt alle Titel selber im Content einfügen? 

Die Funktionalität mit der H1, wie sie jetzt ist, ist eine Core-Funktionalität - solche Sachen sollte man nicht unbedingt umkrempeln.

Anders gefragt: warum stört dich diese H1-Funktionalität? Möchtest du als H1 längere Texte haben? Kannst du ja machen - die URL kann man dann ja nachträglich noch anpassen.

-----------------------------

>  ich habe volle Kontrolle über alle Überschriften, also ich beginne generell mit einer H1 auf der Seite und stufe dann runter

dies ist jetzt auch schon möglich - alle titel sind ja im Content, müssen dann eben nur in korrekter Reihenfolge und Abstufung angepasst werden.

---------------------------------

> Jede Seite beginnt oben mit der H1-Überschrift, die aber vom Styling der H2 entspricht, da diese ja im rechten Menü verwendet wird

jede Seite beginnt bereits jetzt mit einer H1, diese ist nur per CSS ausgeblendet. Wenn wir uns im Punk 1 einigen, passe ich den Rest an - heißt, ich würde die H1 nicht mehr ausblenden und diese visuell an die H2 angleichen.

An sonsten kannst du im Content die H-Titel immer beliebig customisieren mit folgenden CSS Klassen:

```css
.title-h1
...
.title-h6
```

--------------------------

> Homesite hat keine sichtbare Überschrift, da ist sie im Logo verankert

habe es implementiert

**Comment by springers54** [comment]
Du hast Recht. Wenn es im System so vorgesehen ist, dass der Seitentitel auch die H1 ist, dann ist es so und wir machen es so. 
Das Argument, dass ich da die volle Kontrolle habe, ich Quatsch, die habe ich so und so. Denn den Link kann ich ja beliebig kürzen oder auch ganz anders schreiben.

 * [x] Seitentitel ist die H1 und wird angezeigt, den Rest passen wir manuell an. Wo es Probleme gibt, wird es sich zeigen, da müssen wir dann Sonderlösungen schaffen so wie bei der Homesite.

**Comment by joergsteinhauer** [comment]
Ok, guter Plan.

Ich habe nun alle versteckten H1 wieder eingeblendet. Sieht erstmal alles gut aus, musste hier und da etwas am CSS anpassen... aber es scheint erstmal zu funktionieren.

Die H1 hat jetzt die gleiche Größe wie die H2. 
D.h. ihr müsst jetzt eben auf jeder Seite die H-titel anpassen.

Zudem sehe ich, dass derzeit die H1 über dem Seiten-Thumb-Bild geladen wird:
https://reiki-lernen.de/faqs/
![image](https://user-images.githubusercontent.com/1843754/48896918-1361cd00-ee49-11e8-9b5c-3d3aff241585.png)

Ist es ein Problem? Rein syntaktisch macht es schon so Sinn, dass der Titel oberhalb des Inhalts steht. Und das Thumb-Bild ist eben Teil des Inhalts.
