### ISSUE TITLE
Seitenstruktur Ausbildungsangebot https://reiki-lernen.de/system/

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#162]
![grafik](https://user-images.githubusercontent.com/6114076/48981334-47045780-f0d4-11e8-9fa4-db745fab74d8.png)
Leider kann ich hier wenig machen, dass müsstest du verändern, an die Programmierung komme ich nicht ran.

**Comment by joergsteinhauer** [comment]
Jep, meine Baustelle. Du meinst sicherlich die Sprünge von h2 auf h4 sowie von h3 auf h5

**Comment by joergsteinhauer** [comment]
Erledigt
