### ISSUE TITLE
Audiobotschaft neben die Überschrift setzen? https://reiki-lernen.de/lehrer/sylvia-springer/

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#163]
Auf der alten Seite sitzt die Botschaft neben der Überschrift, das ist über eine Tabelle gemacht. Besteht die Möglichkeit hier auch?
![grafik](https://user-images.githubusercontent.com/6114076/48981371-d4e04280-f0d4-11e8-9e83-8ccaad738756.png)

**Comment by joergsteinhauer** [comment]
Na klar, grundsätzlich kein Problem. Ich schaue dann, wie am optimalsten wir das ganze Problem lösen... ohne dass man nachträglich was am Markup anpassen müsste... Zur Not muss man eben noch etwas HTML anpassen.

**Comment by joergsteinhauer** [comment]
Erledigt.

Allerdings musste ich am Markup was ergänzen:

![image](https://user-images.githubusercontent.com/1843754/48983643-cfddbc00-f0f1-11e8-83cc-2ae536167aec.png)


Im alten System wird ein extra Plugin für audio/video genutzt, im neuen System übernimmt das ganze ein fest eingebauter Plugin (http://www.mediaelementjs.com/).
Daher haben wir im neuen system eine komplett andere Situation.

**Comment by springers54** [comment]
prima
