### ISSUE TITLE
Styling Beitragsnavigation https://reiki-lernen.de/ausbildungskosten

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#164]
![grafik](https://user-images.githubusercontent.com/6114076/48981430-a9118c80-f0d5-11e8-9c53-0f7516de5274.png)
 * [x] Da wir sonst die gelben Schaltflächen verwenden, sollte das hier nicht auch genutzt werden? Kannst du einen Vorschlag machen?
 * [x] Das oben angezeigte Zahlenformat für das Datum ist falsch, da steht der Monat vorne und nicht der Tag. bitte ändern

**Comment by joergsteinhauer** [comment]
Die Schaltflächen habe ich mit Absicht so gemacht, das ist der sogenannte "Ghost"-Effekt. Wollte damit die geringere Wichtigkeit dieser Buttons unterstreichen. Kann es aber anpassen:
1. gelb ausgefüllt, wie die anderen Buttons
2. gelbe Umrandung/Schrift statt grau

**Comment by springers54** [comment]
ja würde ich mal so probieren

**Comment by joergsteinhauer** [comment]
Wie denn? :-) Variante 1 oder 2?

**Comment by joergsteinhauer** [comment]
Die Ausgabe der Datums war in WP Einstellungen falsch konfiguriert. Ich habe es geändert auf:
![image](https://user-images.githubusercontent.com/1843754/48983755-1bdd3080-f0f3-11e8-88bb-6a672ef6c126.png)

**Comment by joergsteinhauer** [comment]
Habe nun auch die Farben beim Ghost-Button angepasst. Ok so oder doch alles wie beim default-button machen?

**Comment by springers54** [comment]
wir haben das gerade mit Dani besorochen, diese Navigation sollten komplett weg, sie bringt zwar bei bestimmten Beiträgen vielleicht was, bei anderen aber ist sie total verwirrend und unschön
![grafik](https://user-images.githubusercontent.com/6114076/48999464-0ef22880-f157-11e8-9276-75bcd7b4ff81.png)
Das kommt auf der Seite, wo ein Buch vorgestellt wird: https://reiki-lernen.de/der-weg-zum-wahren-reiki-meister/
 * [x] Navigation entfernen

**Comment by springers54** [comment]
Datumsformat habe ich auf die deutsche Variante angepasst mit t.m.y

**Comment by joergsteinhauer** [comment]
Ok, dann lösche ich diese Navi. Styling ist bis jetzt halt nicht für alle fälle getestet worden, könnte man an sich noch anpassen und schöner machen... 
Die ist halt dazu da, um in einer Kategorie schnell zwischen Beiträgen blättern zu können.
