### ISSUE TITLE
Antworten auf Beiträge anpassen https://reiki-lernen.de/schueler-werden

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#165]
![grafik](https://user-images.githubusercontent.com/6114076/48981821-a6fdfc80-f0da-11e8-9b48-3d8a2cb6c017.png)
so sah es mal auf der alten Seite aus

Auf der neuen
![grafik](https://user-images.githubusercontent.com/6114076/48981835-c6952500-f0da-11e8-8ada-0eebf6eb79a3.png)
 * [ ] **Autorenteil fehlt komplett** unbedingt notwendig
 * [x] **Antworten als Überschrift setzen** One thought on ersetzen
 * [x] **Formatierung der Antworten anpassen** grpßes Bild analog zum Autorenbild
 * [x] **Button nach rechts** sollte einheitlich im ganzen System so sein

**Comment by joergsteinhauer** [comment]
Ich kann durchaus alles anpassen, aber wie ich es z.z. vermute, dauert es doch schon länger. 

Daher die Frage: ist es schlimm, dass es anders aussieht? Es ist ja nichts kaputt. so rein aus User-Sicht würde mich hier im neuen System an sich nichts stören (abgesehen von Kleinigkeiten).

Das ganze Layout der Kommentar-Blocks im alten System wurde durch Cherry-Framework und das Theme selbst so ziemlich customiziert, d.h. das weicht sehr vom WP-Standard ab. Mein neues Theme dagegen basiert sehr stark auf dem WP-Standard, was auch Sinn macht - denn nach einem Major-CMS-Update habe ich im neuen System keine Angst, dass da was kaputt geht. Das alte Theme dagegen ist zu stark abstrahiert, sodass dieser nach einem Update möglicherweise kaputt geht. Genau das sollte man vermeiden.
Es macht also wenig Sinn, die von WP vorgegebenen Strukturen zu ändern, wenn es dafür keinen gewichtigen Grund gibt.

-------------------

Was machen wir also? Wir könnten als erstes einen Kompromiss angehen und Layout nur mittels CSS möglichst an das alte Layout anpassen.

**Comment by springers54** [comment]
Ich habe oben nochmal in der Aufgabenliste fett gemacht und kommentiert, worauf es uns ankommt, Ob du es mit Css oder sonst wie umsetzt, das ist uns am Ende egal. Ob das Datum oben oder unten steht, ebenfalls.
CSS-Anpassungen müssen nur am Ende auch responsiv sein.

**Comment by joergsteinhauer** [comment]
Gut, die meisten Sachen habe ich gefixt.

-----------------------------

Die Sache mit dem "Authorenteil" gehört nicht unbedingt zur Kommentar-Section, das ist ein eigenständiges Element, welches auch eine losgelöste Logik hat. Dabei wird ja der Inhalt von https://reiki-lernen.de/author/zenreiki/ gezogen und zwischen dem Artikel und den Kommentaren angezeigt.

Wäre gut, wenn wir das in einem Extra-Issue lösen, damit dieses Issue hier geschlossen werden kann.

**Comment by springers54** [comment]
Folgende Dinge sollten nach meiner Ansicht in den Kommentaren noch geändert werden:
 * [x] Anpassung der unteren Linie an die obere, also dünner und über die ganze Breite
![grafik](https://user-images.githubusercontent.com/6114076/49365308-ba1a5900-f6e6-11e8-861b-afee9640cd46.png)

 * [x] Anstelle von Antwort und einer Zahl einfach das Wort Kommentare, egal, ob es einer oder mehrere sind
 * [x] Kommentare nicht nummerieren, Blid beginnt also links
 * [ ] Falls es möglich ist, die Datumszeile nach oben über den Namen setzen
![grafik](https://user-images.githubusercontent.com/6114076/49365521-56dcf680-f6e7-11e8-8fb1-af85a12998ef.png)
 * [x] Kommentarbutton auch nach rechts
![grafik](https://user-images.githubusercontent.com/6114076/49365574-77a54c00-f6e7-11e8-9730-dea496b313fd.png)

**Comment by springers54** [comment]
Der Teil Autorenprofil wird in #167 weiter bearbeitet.

**Comment by joergsteinhauer** [comment]
Die Datumszeile kann ich nur mit CSS leider nicht so verschieben. Und um das Markup anzupassen, müsste ich ziemlich viel im PHP customizieren, das macht wenig Sinn.
Ich habe einen Vorschlag gemacht, wäre das ok?

**Comment by springers54** [comment]
Ja, das ist gut so, können wir gern so lassen. Sieht auf jeden Fall ruhiger aus so.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/49448547-6f2d3e00-f7d9-11e8-968a-1ca0a9d9ec5b.png)
https://reiki-lernen.de/reiki-bei-epilepsie

Muss es doch nochmal aufmachen, die 1 oder Nummern bei den Antworten auf die Kommentare sollten auch noch weg.

**Comment by joergsteinhauer** [comment]
Jep, da war noch was. Gefixt
