### ISSUE TITLE
Autorenfeld unter den Beiträgen anzeigen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#167]
Analog zur alten Seite sollte ein Beitrag das Kurzprofil des Autors mit Bild haben.

https://zen-reiki.de/internetschule/schueler-werden/
https://reiki-lernen.de/schueler-werden/

Muster:
![grafik](https://user-images.githubusercontent.com/6114076/49367561-b558a380-f6ec-11e8-929a-c4de4bac0dee.png)

**Comment by joergsteinhauer** [comment]
Sollte erledigt sein.

**Eine Bitte doch mal wieder:**
IMMER URL's angeben, bei jedem Issue. Und nicht im Titel, sondern in der Beschreibung, damit die URL's auch zu klickbaren Links umformatiert werden.

**Comment by springers54** [comment]
* [ ] Ich würde es begrüßen, wenn dünne graue Trennlinien unterr dem Autorenfeld und unter dem Antworten-Bereich gezeigt würden, um eine bessere Abrenzung zu zeigen.

> Eine Bitte doch mal wieder:
IMMER URL's angeben, bei jedem Issue. Und nicht im Titel, sondern in der Beschreibung, damit die URL's auch zu klickbaren Links umformatiert werden.

War doch hier passiert? Stehen oben in der Issue.

**Comment by joergsteinhauer** [comment]
> War doch hier passiert? Stehen oben in der Issue.

Das habe ich nachträglich eingefügt ;-). Im Übrigen passe ich ab und zu die Issues an, damit sie nachvollziehbar sind

**Comment by springers54** [comment]
ok. Gebe mir Mühe, das so gut es geht umzusetzen

**Comment by joergsteinhauer** [comment]
Bitte im Screenshot angeben, wo genau die Trennlinien sein sollen, ich kann es nicht nachvollziehen. 

Zudem habe ich überall versucht eher durch Leerraum Abstände zu erzeugen, Trennlinien sind sperriger. Und Geschmackssache. Nur so, als Erklärung, warum ich ungern Trennlinien einsetze.

**Comment by springers54** [comment]
Der Block gehört unter den Beitrag und dann kommt erst das Autorenfeld
![grafik](https://user-images.githubusercontent.com/6114076/50266822-6ec1b380-0425-11e9-9465-5dd4bf281566.png)

Auch wenn wir dich wieder nerven mit früher war alles viel besser, leider empfinden wir manche Dinge genau so. Vielleicht nur, weil wir uns dran gewöhnt haben.
![grafik](https://user-images.githubusercontent.com/6114076/50267270-f5c35b80-0426-11e9-9e31-b8bfe0ba6637.png)

- [x] Die Zeile auf der alten Seite ist kompakter, die Schrift ist kleiner
- [x] Die Icons sind gelb und nicht schwarz
- [x] Die Textlinkfarbe ist dunkler, damit sind die verlinkten Texte besser zu lesen
- [ ] Das Kalendericon alt gefällt uns besser als das Kalendericon neu
- [x] Kommentaranzeige fehlt in der neuen Leiste komplett
- [ ] Altes Männekin gefällt uns auch besser als neues
- [x] Es fehlt auf der neuen Seite die Leiste mit den sozialen Interaktionen.

... ich weiß, du fluchst jetzt wieder...


Mein angesprochenes Problem mit den Linien würde ich vertagen, bis diese Dinge umgesetzt sind, weil das wieder die Optik verändern wird.

**Comment by joergsteinhauer** [comment]
Ich glaube, wir haben hier grundsätzliches Problem mit dem was ihr von mir erwartet und was ich leisten kann.

**Disclaimer:**
Ich bin kein Backend-WP-Entwickler. Das habe ich immer wieder gesagt. Ich bin Frontend-Entwickler. Ich suche mir Lösungen im Netz zusammen und setze diese ein, wenn ich sie halbwegs verstehe. Hier z.B. stoße ich langsam an meine Grenze - wie auch ab und zu in anderen Issues.

Mein initialer Vorschlag, ein eigenes WP-Theme zu erstellen und das alte gekauftes Cherry-ZR-Theme damit zu ersetzen, war von mir gut gemeint und ich war mir sicher, dass ich (wie auch meine andere etlichen WP Projekte) gut umsetzen kann und das Theme ausreichend eingebaute Funktionalitäten besitzt, die euch zusagen. Der Hauptgrund dafür, den ich sah, lag an der schlechten Performance des alten Themes. Ich erstelle die WP-Themes auf der Basis bestehender "Bundles", die die meisten Funktionalitäten enthalten und ich diese nur "umschubsen" und hübsch mache. 

Nun ist es bei dem neuen ZR-Theme hier wohl nicht mehr der Fall - das, was ihr braucht, scheint mehr und mehr eine ziemlich customisiertes Theme sein zu müssen. 

Ich muss auch gestehen, dass mir bei weitem nicht klar war, dass ich das neue Theme fast 1:1 nachgebaut haben wollt. Das ist nun ziemlich blöd, denn das kann ich garantiert nicht machen - es erfordert einfach fundiertes Backend-Wissen.

Ich habe bis jetzt schon einige Baustellen, für deren Lösung ich mehrere Std. im Netz gesucht und gelesen habe - das ist nicht wirklich produktiv, denn ein WP-Backend-Entwickler würde die Probleme innerhalb weniger Minuten lösen. Ich sehe es auch nicht wirklich sinnvoll, wenn ich Stundenlang nach Lösungen suche. Das ist nicht effizient. 

**Mein Vorschlag:** wir holen noch einen weiteren WP-Backend Entwickler mit ins Boot, der Sachen anpasst oder implementiert, die ich nicht machen kann. Falls es dazu kommen sollte, sollten wir uns vorher zum Workflow einig werden, denn es würden dann mehrere Menschen an gleichen Stellen coden.

-------------------------------------

**Nun zur Reihenfolge der Author-Box:** 

Ich weiß nicht, wie ich diesen Block unter die Meta-Box schieben kann. Ich habe gerade erfolglos nach einer Lösung gesucht, mehr Zeit zu investieren ist einfach Sinn frei. Also: entweder wir lassen es so oder das passt jemand anders an.

----------------------------------------

**Zu visuellen Unterschieden:**

Das habe ich bereits oben gesagt - mein Anspruch beim Erstellen des neuen Theme war nie, das alte Theme 1:1 nachzubauen. Warum auch, wenn das alte Theme nicht optimal ist? Ich habe es m.m.N. so gut es ging besser, moderner und fehlerfreie neu gebaut. Ja, es sieht anders aus - aber nur minimal. Für normalen User bedeutet es keine Nachteile. Dafür hat es Vorteile für Performance, Seo und manchmal auch UX.

All die Problemchen, die du in deiner Liste aufgeführt hast, sind keine Fehler, sondern subjektiver Geschmack basierend auf der Gewohnheit. 

Ich frage mich eben wieder - stört das denn wirklich? Also... ich kann das ja (fast) alles anpassen, nur ist es dann die Zeit, die drauf geht (=euer Geld), die nicht unbedingt sein muss. Es gibt doch viele anderen Baustellen, die wirklich wichtig sind und die volle Benutzung der Seite verhindern.

Ich möchte das jetzt einfach ansprechen, ich sehe da als Teil meiner Aufgabe - nicht nur blind alles umsetzen sondern auch handfeste Argumente und Verbesserungen einzubringen.

**Entscheidet also ihr letztendlich - wollt ihr alle Kleinigkeiten wirklich 1:1 nachgebaut haben oder lassen wir das so?**

Um fair zu bleiben, gehe ich die einzelnen Sachen an:

- Die Zeile auf der alten Seite ist kompakter, die Schrift ist kleiner
--> kann man kleiner machen, aber wieso? Klare Empfehlung von google - mind. 16px für Fließtext. Zudem sollte man mit zu vielen Schriftgrößen hantieren. Das machen nur Amateure - ein uralter Gestaltungsprinzip und Regel.

- Die Icons sind gelb und nicht schwarz
--> kann ich fixen, gar kein Problem an sich. Aber auch hier Empfehlung von google: Kontrastreiche Farben für Texte (einschl. Icons) - das Gelb ist leider zu hell. Trotzdem machen? Evtl. einen weiteren dunkleren Orange-Ton nehmen?

- Die Textlinkfarbe ist dunkler, damit sind die verlinkten Texte besser zu lesen
--> korrekt, das muss ich tatsächlich noch anpassen und zwar global

- Das Kalendericon alt gefällt uns besser als das Kalendericon neu
--> ich verwende die bekanntesten Icons aus der google Bibliothek - das ist nun wirklich sinnvoll, da diese Icons (nicht nur) auf Android eingesetzt werden und somit eben bekannt sind. Wiedererkennung ist sehr wichtig! Außerdem sind diese Icons zueinander passend. Im Alten System waren die FontAwesome-Icons verbaut. Aber nun habe ich die Icons aus der bekanntesten Bibliothek eingebaut - sollte man doch nun auch so weiter machen, das hat nur Vorteile. Und: letztendlich ist es nur Gewohnheit, wenn man sagt, dass alte "Sachen" besser gefallen.

- Kommentaranzeige fehlt in der neuen Leiste komplett
--> kann ich sicherlich noch einbauen

- Altes Männekin gefällt uns auch besser als neues
--> s. oben

- Es fehlt auf der neuen Seite die Leiste mit den sozialen Interaktionen.
--> sowas sehe ich als Zusatz und nicht als default-Funktionalität in einem Theme, ist also extra. Kann man ohne Probleme einbauen, bitte im neuen Issue

------------------

Und wenn ich meine "Empfehlungen von google", dann ist es wirklich wichtig. Ihr wollt bei google oben in der Suche erscheinen - nun sollte man dabei aber auch darauf hören, was google mag. Und genau dafür sind googles Empfehlungen.

**Comment by springers54** [comment]
> Entscheidet also ihr letztendlich - wollt ihr alle Kleinigkeiten wirklich 1:1 nachgebaut haben oder lassen wir das so?

Du gibst dir immer so viel Mühe, danke dafür erst einmal.
Noch mal grundsätzlich: Viele unserer Anmerkungen sind optionale Wünsche und kein Muss, dass etwas so passieren soll. Dani und ich sind gute Pragmatiker, die sich auch mit Dingen arangieren können, die nicht so sind, wie wir sie uns optimal wünschen. Wir sind immer für Kompromisse zu haben und wenn etwas technisch für dich zu schwierig ist oder Aufwand-Nutzen nicht stimmt, dann ist es halt so.
Auf dieser Basis haben wir über Monate gut zusammen gearbeitet und ich sehen keinen Grund, warum das in Zukunft nicht weiter klappen sollten.

> Die Zeile auf der alten Seite ist kompakter, die Schrift ist kleiner

dann lass es so, du bist der Gestalter

> Die Icons sind gelb und nicht schwarz

bitte machen

> Die Textlinkfarbe ist dunkler, damit sind die verlinkten Texte besser zu lesen

--> korrekt, das muss ich tatsächlich noch anpassen und zwar global
Ja bitte, unbedingt

> ich verwende die bekanntesten Icons aus der google Bibliothek 

Gib uns bitte den Link, der Bibliothek, dann können wir selbst an der einen oder anderen Stelle suchen und Vorschläge machen.

> Es fehlt auf der neuen Seite die Leiste mit den sozialen Interaktionen.

Machen wir eine separate Issue für nach der Umschaltung im Januar #174

**Comment by joergsteinhauer** [comment]
Wunderbar, danke dafür. Ich bin sehr für Pragmatismus. Wir haben es bis jetzt ganz gut gemeistert, da sind wir uns einig - dann also weiter so :-).

Die Icons Bibo ist die hier: https://materialdesignicons.com/
Die ist wirklich groß, aber es kann auch durchaus sein, dass ein spezielles Icons nicht aufzufinden ist. Da gehe ich immer den einfachen Weg und suche in den Issues nach diesen Icons (am besten diverse englische Begriffe ausprobieren): https://github.com/templarian/MaterialDesign/issues 
Manchmal findet man dann tatsächlich einen Entwurf, den man auch nehmen kann und der dann evtl. dem Projekt hinzugefügt wird. Wie auch immer - das gute daran ist, dass die Gestalter die Icons stimmig zueinander entwerfen und das ist goldwert.

**Comment by joergsteinhauer** [comment]
So wie ich sehe, sind hier noch 3 Sachen offen:

- [ ] Trennlinien: das hing ja an der Position des Autoren-Blocks. Diesen kann ich ja nicht ohne weiteres Verschieben. Was also machen mit den Trennlinien? Irgendwo welche einfügen?
- [ ] Icon für "Kalender" festlegen
- [ ] Icon für "Autor" festlegen

**Comment by springers54** [comment]
Icon für Autor: 
![grafik](https://user-images.githubusercontent.com/6114076/50652790-e47e6100-0f87-11e9-9859-8962115d4183.png)

Für den Kalender entweder
![grafik](https://user-images.githubusercontent.com/6114076/50653522-1690c280-0f8a-11e9-8887-bf8fbdec7054.png)
 oder
![grafik](https://user-images.githubusercontent.com/6114076/50653555-30caa080-0f8a-11e9-98aa-14c174634495.png)

Was dir von beiden besser gefällt

Trennlinie würde ich dann zwischen dem Beitrag und dem Autorenfeld setzen.

**Comment by joergsteinhauer** [comment]
Erledigt. Wobei ich mich frage, warum bei Icons das "Stift" Piktogramm sein muss, wenn das Icon doch **keine** Edit-Funktion hat?

**Comment by springers54** [comment]
Der User ist der Schreiber und hat den Stift in der Hand. Muss man nicht verstehen. Frauenlogik halt.

**Comment by joergsteinhauer** [comment]
Na ok, ist auch egal, hat mich nur gewundert. Lassen wir so. Ist auch zur Not schnell änderbar
