### ISSUE TITLE
Ersatz für Starliste

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#168]
Kannst du eine Class schreiben, die wir für Listen verwenden können, um diese mit einem gelben Punkt oder gelben Stern zu beginnen?

Früher hatten wir die star-list, die ist aber nun weg, da sie vom Cherry kam

**Comment by joergsteinhauer** [comment]
Klar, mache ich. Diese `star-list` Klasse ehemals von Cherry, gibts die noch im Markup? Wenn ja, auf welchen Seiten? Ich muss ja sehen wie es aussieht und ggf. gleich mal testen.

**Comment by springers54** [comment]
https://reiki-lernen.de/usui-reiki-dai-ko-mio/

**Comment by joergsteinhauer** [comment]
Habe nun den Shortcode implementiert und die Liste gestylt

**Comment by springers54** [comment]
Kannst du uns bitte eine weitere Liste machen, wo die Sterne gelb sind?

**Comment by springers54** [comment]
Kannst du uns bitte eine weitere Liste machen, wo die Sterne gelb sind?

**Comment by joergsteinhauer** [comment]
erledigt. Klasse heißt `star-list-primary`

**Comment by springers54** [comment]
Wie genau ist das zu verwenden?
![grafik](https://user-images.githubusercontent.com/6114076/50691368-c15bbc00-1030-11e9-930b-61916e53c37a.png)

Also so passiert erst mal gar nichts.

**Comment by joergsteinhauer** [comment]
shortcode dafür ist `[star_list_primary] `, da fehlte aber auch noch von meiner Seite etwas. Geht jetzt.

**Comment by springers54** [comment]
ok, hatte ich zuerst probiert, hatte aber keinen Effekt

**Comment by springers54** [comment]
prima, geht jetzt
[star_list_primary] 
<ul>
 	<li>Dai Kohmieoh</li>
</ul>
[/star_list_primary]
