### ISSUE TITLE
Parallax Problem (z.B. Scrollen bei "Wir sind anders")

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#169]
https://www.i-talk24.net/msg/63cd908
 * [ ] Text sollte stehen bleiben und nur das Hintergrundbild sich bewegen
 * [ ] Höhe des Hintergrundbildes anpassen

**Comment by joergsteinhauer** [comment]
Ja, tatsächlich ist mir bei dem Parallax Effekt auch ein ähnliches Problem aufgefallen, jedoch nur dann, wenn ich das Browser-Fenster verkleinere/vergrößere. Aber verkleinern/vergrößern macht kaum jemand, max. nur wenn man Bildschirm dreht (Smartphones, Tablets). 

Beim Laden der Seite wird alles im JS berechnet und passt sich dann der Fenstergröße an, das sollte an sich also alles gut funktionieren.

Hier sieht man bei mir, dass an sich alles sichtbar bleibt und somit gut aussieht:
![51594f1b21c11f81d37c3ced31cc5a67](https://user-images.githubusercontent.com/1843754/50118694-d1ae2180-0250-11e9-9138-bc5d8d358abc.gif)

Hast du da evtl. irgendwie mit der Fenstergröße gespielt oder passiert dieses Problem sofort beim ersten Aufruf der Seite? Welche Breite/Höhe hat dein Bildschirm (px)?

An Sonsten müsste ich schauen, wo das Problem liegt. Kann auch sein, dass die benutze JS Bibliothek nicht ganz so gut ist und ich was neues suchen muss.

**Comment by springers54** [comment]
In deiner Animation zeigt sich das Problem ebenso. Wenn man im Bereich der Lehrer ist, dann ist die Überschrift weg, der Text scrollt nach unten. 
Auch wenn dich der Vergleich mit der alten Seite nervt, hier steht die Überschrift und dei Bilder mit Text scrollen von rechts.
![grafik](https://user-images.githubusercontent.com/6114076/50135624-1f4c7d80-0295-11e9-864d-28d538c64388.png)
Damit sieht es ruhiger aus.
Nachdem der Text-Bildblock einmal eingeflogen ist, scrollt nur noch das Bild im Hintergrund, während der Text ruhig stehen bleibt.

**Comment by joergsteinhauer** [comment]
Ja, das kann ich nachvollziehen, ist auch nicht wirklich user freundlich. Sollte auf jeden Fall gefixt werden.

Nur will ich verstehen, warum sich das JS so verhält, daher auch meine Frage:
**wie groß ist dein Bildschirm?**

Gehe bitte auf https://www.mydevice.io/ und mache ein Screenshot von "Screen metrics":
![grafik](https://user-images.githubusercontent.com/1843754/50146775-da384380-02b4-11e9-864c-78802fc6c4a0.png)

Anscheinend funzt das JS so, dass es den Inhalt der PArallax-Box mittig ausrichtet, wenn diese Box mittig relativ zum Bildschirm liegt. Auf jeden Fall funzt das JS anders als im alten System.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/50163338-83486380-02e0-11e9-884c-f5086ea8c4d4.png)

**Comment by joergsteinhauer** [comment]
Ich brauche bitte doch die "SCREEN METRICS", weiter unten, die Boxen mit Rosa-Überschriften. Mir ist nicht nur die Breite wichtig.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/50265084-3074c600-041e-11e9-8cc5-cd8cf866a682.png)

**Comment by Dani2909** [comment]
![grafik](https://user-images.githubusercontent.com/39252760/50265192-c1e43800-041e-11e9-8dc4-e8e3a0db6609.png)

**Comment by joergsteinhauer** [comment]
Ich bin dran am Parallax Problem. Das ist alles andere als einfach.... Bitte auf der Startseite den Block "Wir sind anders" nicht anfassen, da ist eine Baustelle.

Parallax ist derzeit global deaktiviert

**Comment by joergsteinhauer** [comment]
Ich muss fluchen, dieser Parallax-Effekt und dann noch in diversen Ausführungen und in unterschiedlichsten Konstellationen ist einfach mal zu komplex und ich fand kein Plugin, was diese tausend Fälle abdecken könnte und gleichzeitig performant wäre (ich versuche kein jQuery zu verwenden).

Deswegen sitze ich bereits Stunden an dem Problem. Habe es erstmal auf der Startseite implementiert und wollte es nun auf Kontakt-Seiten einbauen, da gibt es aber wiederum unerwartete Probleme.

**Frage:**
ist dieser Effekt denn so wichtig? Braucht man das auf all den Seiten?

Bevor ich hier weiter Unmengen an Zeit investieren, muss ich sicher sein, dass wir auf dem richtigen Weg sind.

Parallax funktioniert weiterhin nur sporadisch.

**Comment by springers54** [comment]
bei uns funktioniert es gar nicht
![grafik](https://user-images.githubusercontent.com/6114076/50649355-efcc8f00-0f7d-11e9-8c2c-22a9b444638f.png)
also wichtig ist es nicht.
Schon gar nicht, wenn es unzuverlässig ist. Dann bin ich für konsequentes Weglassen im Sinne derzeitliches Effektivität

Das Hintergrundbild in Wir sind anders sollte aber da sein.

**Comment by joergsteinhauer** [comment]
Komisch. Bei mir gehts in chrome und Firefox, sollte auch sonst überall gehen.

Manchmal spinnt das JS etwas, da bin ich noch dran. Und der Cache macht auch Probleme. Bitte mal "hard refreshen", Anleitung für diverse Browser: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.XC5wRVxKhaR

Was genau funktioniert nicht?

Gibts es Fehler im Entwickler-Tool --> Console? Also Entwicklertool aufmachen (F12), dann unter "Console" schauen, was ausgegeben wird und ein Screenshot machen. Bei mir ist es so:
![image](https://user-images.githubusercontent.com/1843754/50660141-10f1a780-0f9f-11e9-9e1c-b04305862a2d.png)


-----------------

Wenns nicht so wichtig ist, würde ich das was ich bis jetzt gemacht habe, auch so lassen. Sprich - auf der Startseite den Parallax Effekt weiterhin lassen, dafür aber kein Parallax auf Kontaktseiten.

Übrigens, ist es meine Vermutung, dass u.a. Parallax im alten System die Seite so lahm gemacht hat.

**Comment by springers54** [comment]
Ich bin im FF und da geht es nicht
![grafik](https://user-images.githubusercontent.com/6114076/50690818-0da5fc80-102f-11e9-86a6-df50aaa04d44.png)

Kommt beim Scrollen auf der Seitee eein schwarzer Bereich, der zwar wegscrollt, aber häßlich ist.
 Im Crome der gleichee Effekt
![grafik](https://user-images.githubusercontent.com/6114076/50691000-b81e1f80-102f-11e9-9964-789d3770ac2d.png)

Die Parallaxe kommt zwar, aber dieser Trauerbalken ist einfach nichts.

Also meine Eempfehlung: Effekt komplett weg und nr Hintergrundbild

**Comment by joergsteinhauer** [comment]
Ok, genau diese Art von Infos brauche ich - was genau nicht funktioniert. Der dunkle Balken - da passte einfach das Bild noch nicht ganz, ich habs mal aktualisiert, sieht jetzt gut aus.

Ich finde am Ende den Parallax Effekt ja nicht schlecht, man muss nur solche Sachen mit Vorsicht einbauen und sowas funktioniert auch nicht bei jeder möglichen Auflösung und mit jedem möglichen Inhalt - es ist zumindest in unserem Fall nicht so dynamisch. 
Würde man jetzt also z.b. mehr Kacheln einfügen, müsste man ggf. die Einstellungen für diese eine Parallax-box anpassen. 
Aber nun funktioniert es - und leider auch fast nur auf HD-Auflösung - also 1920x1080 und ähnlich. 

Es ist hier also nötig, diesen Effekt nur bei bestimmten Auflösungen anzuschalten. Das muss ich noch optimieren.

Würde aber generell den Parallax-Effekt also schon lassen, das ist visuell ein Mehrwert, macht die Seite hübscher und moderner, nicht so langweilig. Und es wäre schade um die ganze Arbeit.
Auf mobilen Geräten hätte ich den Effekt sowieso ausgestellt, das macht dort wenig Sinn, vor allem wegen der Performance.

**Comment by springers54** [comment]
also das Problem besteht nach wie vor
![grafik](https://user-images.githubusercontent.com/6114076/50696692-6d58d380-1040-11e9-9522-2e4a3f5064c2.png)

Auch wenn ich kein Freund von verschenkter Arbeit bin, wir haben wichtigere Baustellen als diese im Moment und wenn es nicht mal auf allen Geräten und Auflösungen geht, dann weg damit.

**Comment by joergsteinhauer** [comment]
Das Problem liegt eher doch noch an der Fenstergröße. Es gäbe hier eben den Weg, den Parallax-Effekt nur für 1920x1080px zu aktivieren.... Aber ich stoße auf weitere Probleme, die das Plugin an sich irgendwie mit bringt und da gibt es (für mich) leider keine ersichtliche Lösung. 
Das ist schon doof, kränkt mich bissel, weil ich da so viel Energie reingesteckt habe. Aber es nützt jetzt nichts, so können wir das nicht lassen - also müssen wir den P-Effekt leider komplett deaktivieren.

**Comment by joergsteinhauer** [comment]
Evtl. für spätere Nachforschungen:

Das Problem ist , dass das JS-Plugin https://github.com/erikengervall/parallax-vanilla einen Js-Fehler wirft, wenn die Bibo zwar eingebunden wird, aber kein Parallax-Element auf der Seite existiert bzw. kein Parallax gestartet wird. 

Das "kein Parallax starten" passiert z.B. dann, wenn P-Effekt nur bei bestimmten Fenstergrößen starten soll und man mit mediaQueries im JS hantiert.

**Comment by springers54** [comment]
Ich verstehe deinen Frust nur zu gut. Aber manchmal ist ein Cut besser als weitere verpulverte Zeit.
