### ISSUE TITLE
Feintuning Lehrerbox

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#170]
Die Bilder sind hochgeladen, wie auf der alten Seite in 172 px. Das passt nicht ganz zu deine Boxen, die müssten also angepasst werden.
![grafik](https://user-images.githubusercontent.com/6114076/49825081-d91e8800-fd83-11e8-9f75-75c07ef554d6.png)
 * [x] Breite anpassen an die Bilder
 * [ ] Wenn möglich, nur den Vornamen des Lehrers zeigen, nicht den kompletten Namen
 * [x] Die Überschrift sollte nicht so an den Bildern kleben
 * [x] Den Weisbereich unter den Lehrern kleiner machen

Hier nochmal der Vergleich mit der alten Seite
![grafik](https://user-images.githubusercontent.com/6114076/49825199-27338b80-fd84-11e8-8dd6-b1b55e75306b.png)

**Comment by joergsteinhauer** [comment]
- Kachelbreiten habe ich nun angepasst. Die Kacheln waren bis jetzt flexibel, d.h. die Breite passte sich an, je nach Seitenbreite. Da ihr nun kleine Bilder hochgeladen habt und diese sicherlich möglichst scharf dargestellt werden müssen, dürfen die Bilder nicht skaliert werden. D.h. wiederum, dass die Kachel ebenfalls 172px breit ist. D.h. wiederum, dass die Kacheln feste breite haben und nicht mehr dynamisch sind, was aber nichts kaputt macht.
- Nur Vornamen anzeigen geht so nicht ohne Weiteres. Ich zeige z.z. den kompletten Seitentitel an. Wenn, dann müsste man hier enorm viel aufbohren und ein extra Feld irgendwo/irgendwie machen, wo man nur den Vornamen einträgt.
- Weißbereich unter den Lehrern - du meinst die Fläche, wo der Name steht? Habe es etwas kompakter gemacht, allerdings muss dabei die Schriftgröße kleiner werden. Viel mehr kleiner kann man es nicht machen, denn es kann durchaus lange Namen geben, die in eine Zeile nicht passen. Z.z. gibt es einen "edge case" bei Detlef, wobei der Name noch in eine Zeile passt - bei zwei Zeilen würde es dann aber so aussehen und das ist der minimale Abstand:
![image](https://user-images.githubusercontent.com/1843754/49896223-0128ec80-fe53-11e8-9152-cadbc8b5b9b7.png)

**Comment by springers54** [comment]
* [x] Leider geht deine feste Breite so nicht, weil es nicht mehr responsiv ist. Auf dem Handy werden dann auch Bilder in Breite 172 px gezeigt, das geht nicht.
Also selbst, wenn es ein kleines bisschen skaliert werden würde, muss es flexibel bleiben
 * [ ] Es wurden wieder nur 5 Lehrer gezeigt, also musste ich jetzt wieder die Zahl der Blogbeiträge höher setzen. Die beste Lösung ist das so also nicht, Für den Übergang wäre es zwar möglich, aber für die Zukunft müssen wir die Beitragszahl vom Posttyp abhängig einstellen können.
 * [x] Mit den Namen haben wir uns eine pragmatische Lösung einfallen lassen, da musst du nichts machen
 * [ ] Grauer Bereich oben ist zu groß auf der Homepage
![grafik](https://user-images.githubusercontent.com/6114076/49919530-2e06ef00-fea7-11e8-9a99-299412e3664d.png)

**Comment by joergsteinhauer** [comment]
### Breite der Kacheln

Tja, genau das habe ich in letzten Tagen versucht zu erklären - warum es wichtig ist, dass die Kacheln dynamisch und flexibel bleiben und warum man da auch entsprechend größere Bilder laden muss, damit diese nicht zu verpixelt werden. 
Mir war es so, als wäre euch die tatsächliche Bildgröße von 172px am Wichtigsten und die Responsivität egal. Nächstes mal wäre es gut, wenn die Anforderungen klar sind, z.b:
- Kacheln müssen responsiv sein
- auf Gerät A mit Bildschirmbreite XXX sollen so und so viele Kacheln in einer Reihe angezeigt werden
- Bilder selber dürfen max XXX px sein...

Wir tanzen hier um das gleiche Thema hin und her gefühlt seit Wochen, am Ende ist die Lösung relativ einfach - war aber so anfangs überhaupt nicht klar.

Und Aussagen wie "auf dem Handy [...]" bringen so leider auch nichts, denn es gibt Unmengen an verschiedenen Handys mit unterschiedlichsten Bildschirmbreiten - da muss ich schon wissen, welche Handys/Größen am wichtigsten sind oder zumindest mit welchen Handys ihr das testet.

### Anzahl der Beiträge

Korrekt, die Anzahl in Einstellungen auf unter 10 zu begrenzen ist nicht gut. Genau das hatte ich schon mal probiert und es hat nicht funktioniert (habe es dann aber wieder vergessen, warum und weshalb es zu Probleme kam). Das muss man andres lösen - wie, weiß ich selber noch nicht.

### Leerraum

Ich habe es mal angepasst, allerdings habe ich doch nicht ohne Grund das globale Layout nach gleichen Prinzipien aufgebaut, sodass alle Abstände innerhalb der Module oder vor/nach den Überschriften immer gleich sind. Und es gibt somit auch keine extra Anpassungen für Modul 1, 2, 3... Es ist immer gleich und so sollte es auch sein, das Layout sollte eine homogene Struktur aufweisen. Daher haben sich Abstände auch in anderen Modulen geändert, also nicht nur im "Lehrer-Block".
Ich hoffe die Anpassung ist OK so und ich würde abraten jetzt nur für den Lehrer-block extra was anzupassen.

**Comment by springers54** [comment]
> Wir tanzen hier um das gleiche Thema hin und her gefühlt seit Wochen, am Ende ist die Lösung relativ einfach - war aber so anfangs überhaupt nicht klar.

Ja, da hast du Recht, aber die Lösung, die wir jetzt haben, ist nicht vom Himmel gefallen, weder für dich noch für uns. Denn wir haben uns auch an vielen Stellen etwas einfallen lassen, um die Restriktionen, die die Neugestaltung bringt, so zu um gehen wie es derzeit geschehen ist. Ich finde, wir haben uns hier gut auf einander zu gearbeitet.

Dass die neue Seite responsiv sein muss, ist eine elementare Forderung, ich denke, das war eines der wichtigsten Ziele deiner Neugestaltung, dass dein Theme das sicherstellt.

Wir haben mit der jetzigen Beitragsbildbreite eine gute Voraussetzung geschaffen, dass die Seite schnell ist. Und logischerweise muss das Beitragsbild auf einem Handy kleiner sein.

Es sollten auf dem Handy in jedem Fall 2 Bilder nebeneinander passen, so war es auch auf der alten Seite, auch wenn du den Vergleich nicht magst.

Der Leerraum ist jetzt besser

**Comment by joergsteinhauer** [comment]
Ja, wir haben uns letztendlich aufeinander zugearbeitet, aber für meinen Geschmack mit zu viel Aufwand, der hätte vermieden werden könnte.
Ich stoße eben in meinem Beruf immer wieder auf ähnliche Probleme, daher spreche ich das hier an. Und da ich durch meine Erfahrung weiß, dass man sowas gut vermeiden kann, sollten wir vielleicht versuchen in Zukunft Aufgaben besser zu organisieren.

Um genau zu sein, wie ich schon sagte, sind **klare und detaillierte** Aufgaben das wichtigste. Um uns allen den Aufwand dabei möglichst gering zu halten, **mein Vorschlag**:

Ich passe die Beschreibung einer der nächsten Aufgaben (Issues) einfach mal selber an und somit hast du dann ein Bsp, an dem du dich orientieren könntest. Wir können mit einer einfachen Aufgabe beginnen. Schwierig sind dann komplexe Aufgaben und eben diese machen die meisten Probleme.

**Comment by joergsteinhauer** [comment]
Zur Kachel selbst nochmal:

- da ihr jetzt nur kurze Namen eingetragen habt, habe ich die Textfläche etwas kompakter gemacht und lange Namen werden einfach mit ... abgeschnitten, sollte aber kaum vorkommen.

- responsives Verhalten: Auf meinem Handy (HTC 10 - 360px bei 4dppx) sehe ich 3 Spalten. Wenn also hier die Kachelgrößen noch nicht ok sind, sag mir bitte, welches Geräte du nutzt. Außerdem empfehle ich ab jetzt an für Bildgrößen-Spezifische Probleme diese Seite:
https://www.mydevice.io/
Hier kann man schauen, was für Eigenschaften das Gerät hat und auf https://www.mydevice.io/#compare-devices sogar diverse Geräte vergleichen.

**Comment by springers54** [comment]
Ich denke, dass es auf der Startseite gut aussieht, auf unseren Handys auch. Ich habe auch ein HTC 10, insofern sehen wir das Gleiche.
Das Kompakte ist vollkommen in Ordnung.
Der Abstand oben ist immer noch ziemlich groß
![grafik](https://user-images.githubusercontent.com/6114076/50201372-27222580-035a-11e9-81fb-a9e2fb35bff0.png)

Fällt auch auf auf der Seite
https://reiki-lernen.de/lehrerring/
auf.
![grafik](https://user-images.githubusercontent.com/6114076/50201722-77e64e00-035b-11e9-839a-e01ac7dfd789.png)

Es fehlt uns auch ein Abstandelement. Früher gab es [spacer].
Egal, was ich mache, ob br pder p, um einen Abstand zu erzeugen, es hat keine Wirkung.

**Comment by joergsteinhauer** [comment]
Also, ich hab den Abstand noch etwas verkleinert - aber ich würde hier den Abstand wirklich nicht noch kleiner machen. Mut zur Lücke - um Inhalte visuell abzugrenzen eignet sich der Leerraum am besten. Das stört doch nicht oder wo genau liegt das Problem? Die Blöcke, die sich gegenseitig durch Leerraum abgrenzen, sind doch in sich geschlossen gut lesbar. Oder geht es darum, dass man auf kleineren Bildschirmen nicht so viele Infos auf einmal sieht?

Der jetzige Abstand (rot markiert) ist 72px
![image](https://user-images.githubusercontent.com/1843754/50247319-d51fe500-03d7-11e9-940c-3a3de755430a.png)

Auf https://reiki-lernen.de/lehrerring/ sehe ich jetzt gerade komplett was anderes als auf deinem Screenshot.

Wo versuchst du denn Abstand mit br/p tags zu erzeugen? Ich müsste den Quellcode sehen. Spacer wird im anderen Ticket gemacht.

**Comment by springers54** [comment]
Wir sind jetzt auf der Startseite: https://reiki-lernen,.de
![grafik](https://user-images.githubusercontent.com/6114076/50265434-e856a300-041f-11e9-9f4a-a27859375baa.png)
wir würden den Abstand unten als ausreichend Mut zur Lücke empfinden und den oben nicht größer haben wollen.

Zur Seite https://reiki-lernen.de/lehrerring/
Hat sich gestern komplett geändert, dadurch, dass wir die Texte aus dem Feld mit den Lehrern gezogen haben und eine echte Überschrift darüber habe, gibt es kein Abstandproblem mehr zum Text

Wir würden hier aber einen einheitlichen Rahmen bevorzugen, also er sollte oben und unten nicht höher sein als links und rechts
![grafik](https://user-images.githubusercontent.com/6114076/50265711-1e485700-0421-11e9-93c3-337ef90fea24.png)

**Comment by joergsteinhauer** [comment]
Sollte erledigt sein. War etwas mehr rumgefrimmel, weil das selbe Element ja auf diversen Seiten verwendet wird und dann mit und ohne de Überschrift, die ja einen Abstand braucht.
