### ISSUE TITLE
Stylingelement [spacer] oder Abstand  erzeugen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#171]
Wir brauchen für die Gestaltung der Seite ein Abstandselement. 
Im alten System war das [spacer]. 
Mir ist egal, wie es heißt, nur man muss auch mal einen Abstand einfügen können.

Siehe Seite https://reiki-lernen.de/lehrerring/

Inzwischen sieht es hier besser aus, weil wir die Überschrift rausgezeogen haben aus dem Lehrerblock und jede Überschrift zum Glück eine Abstand mitbringt.

**Comment by joergsteinhauer** [comment]
- wo sehe ich das im alten System? Ggf. Screenshot anhängen
- ich nehme an, der "spacer" war ein shortcode. Ich kann es wieder als Shortcode anlegen oder als reines HTML-Element... oder beides
- wie hoch muss das sein?

Grundsätzlich: was genau möchtest du damit erreichen? Wo wird denn ein Abstand gebraucht und warum?

**Comment by springers54** [comment]
>     * wo sehe ich das im alten System? Ggf. Screenshot anhängen

Also die Seiten sind generell mehr oder weniger vom Aubau gleich. Wenn ich die eine Link im neuen System schicke, der mit http://reiki-lernen.de/... beginnt, dann gibt es im alten System die Vergleichsseite mit https://zen-reiki.de/...
Ich dachte, der Teil war klar.



>     * ich nehme an, der "spacer" war ein shortcode. Ich kann es wieder als Shortcode anlegen oder als reines HTML-Element... oder beides

als Shortcode, wie es war, wäre gut, als Höhe würde eine Zeile reichen. Wenn man mal mehr Abstand brauchen würde, dann setzt man 2 hintereinander.


> Grundsätzlich: was genau möchtest du damit erreichen? Wo wird denn ein Abstand gebraucht und warum?

Mir ist klar, dass man so wenig wie möglich in die normale Gestaltung eingreifen sollte. Aber wenn man Bilder einfügt, dann kann es mal sein, dass man doch etwas mehr Freiraum braucht. Oder wenn Elemente, sie die Lehrerliste an einen Text stoßen. Oder wenn ein Formular mit Hintergrund einem Text folgt.

**Comment by joergsteinhauer** [comment]
`[spacer]` kann als Shortcode nun weiterhin verwendet werden, habe den Shortcode implementiert. Hat eine Höhe von 3rem = 48px (im alten System 49px).

Grundsätzlich spricht nichts gegen solche Hilfs-Elemente, solange diese nur in Ausnahmefällen eingesetzt werden. Wenn jedoch ein Spacer auf diversen Seiten immer an der gleichen Stelle eingesetzt wird, sollte man eher das globale CSS-Layout anpassen.

**Comment by springers54** [comment]
super danke.
