### ISSUE TITLE
Einheitliche Gestaltung der gelben Button 

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#172]
Bitte jetzt nicht als Krümelkäse auffassen: Die Schrift im Button ist nicht mittig.
Seite: https://reiki-lernen.de/themen/buecher/

- [x] Also den unteren Abstand dem oberen anpassen, so dass die Schrift in der Mitte ist. 

![grafik](https://user-images.githubusercontent.com/6114076/50266302-62d4f200-0423-11e9-8d1a-24a0f7bab73b.png)

--------------------------

Es geht weiter auf der Seite: https://reiki-lernen.de/schueler-werden/

- [x] Der obere Button wirkt zu wuchtig, es würde reichen, wenn er dem Standard entsprechen würde
![grafik](https://user-images.githubusercontent.com/6114076/50266469-f6a6be00-0423-11e9-8925-6f245488fe6c.png)

Unten ist wieder ein wuchtiger Button:
![grafik](https://user-images.githubusercontent.com/6114076/50266531-366da580-0424-11e9-8ad5-62f80b6132bd.png)

--------------------------

- [x] Vielleicht könnte die Class angepasst werden, damit die Buttons gleich aussehen?
`<p style="text-align: right;"><a class="btn btn-primary" href="/ferneinweihung">Ferneinweihungen?</a></p>`

**Comment by joergsteinhauer** [comment]
bei Punkt 2: habe den großen Button verkleinert, ich nehme an, dass er zu groß war. Den kleinen Button habe ich nichts angefasst. Und: was ist denn "Standard"?

bei Punkt 3: wo sehe ich diesen Quellcode?

**Comment by springers54** [comment]
Ist es möglich, dass die Buttons alle die **gleiche Größe** haben? Bitte an die kleine Größe des Buttons anpassen. Standard ist, wenn alle Button gleich groß sind ;-)

![grafik](https://user-images.githubusercontent.com/6114076/50327853-05a77200-04f1-11e9-8cbb-60eb96909344.png)

>bei Punkt 3: wo sehe ich diesen Quellcode?

z.B. auf der Seite, ist zwar ein anderer, aber der gleiche Quellcode class="btn btn-primary
 https://reiki-lernen.de/sylvia-springer-ausbildungen/

**Comment by joergsteinhauer** [comment]
Ok, dann alle Buttons klein, gar kein Problem. Initial habe ich genau so wie im alten System 2 unterschiedliche Größen entwickelt - da war ja an sich nichts verkehrt. 

Man muss aber vorher auch wissen, welche der beiden Varianten der "Standard" ist :-)

Habe nun eine einheitliche Größe definiert - µ größer als das kleine Button (fand es einfach viel zu klein) , aber am Ende nicht so globig wie vorher. Die Klasse `btn btn-primary` hat den selben Style, da braucht man nichts im HTML anzupassen

**Comment by springers54** [comment]
Ja, wir sind damit auch zufrieden. So sieht es gut aus.
