### ISSUE TITLE
Soziale Interaktionen unter den Beiträgen integrieren (Twitter, Facebook, ...

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#174]
![grafik](https://user-images.githubusercontent.com/6114076/50327144-13a7c380-04ee-11e9-9d53-d3b8d68157d7.png)

**Comment by joergsteinhauer** [comment]
Würde über Plugins gehen, z.B. das hier:
https://de.wordpress.org/plugins/ultimate-social-media-icons/

Ihr könnt Plugins gern mal installieren, ich passe es ggf. an

**Comment by springers54** [comment]
Wir haben das nochmal diskutiert. Da wir im Moment die sozialen Medien nicht bedienen und dies in der Vergangenheit auch eher von uns selbst benutzt wurde als von den Besuchern, würden wir das zurückstellen. Wir haben andere Dinge, die wichtiger sind.
