### ISSUE TITLE
Styling Suchergebnisse

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#176]
https://reiki-lernen.de/?s=test

Habe eben mal eine Suche gemacht nach dem Wort test
Hier kommen sowohl Seiten als auch Beiträge als Ergebnisse. Da wo es keine Kategorien gibt, also bei den Seiten sind am Ende 2 Striche

![grafik](https://user-images.githubusercontent.com/6114076/50737242-13364a80-11c7-11e9-9246-5ec4121e7c69.png)

Kannst du das so ändern, dass nur einer der beiden Striche gezeigt wird?

**Comment by joergsteinhauer** [comment]
Jep. Funktioniert nun über CSS. Wenn ein leerer Meta-Container ausgegeben wird, wird dieses versteckt.

**Comment by springers54** [comment]
hat bei mir noch keinen Effekt
![grafik](https://user-images.githubusercontent.com/6114076/50752179-6e128500-124d-11e9-8597-4889f079d8c3.png)

**Comment by joergsteinhauer** [comment]
Ah, sorry, vergessen zu erwähnen, dass eingeloggt sich in diesem Bereich (zwischen den Linien) eigentlich der Edit-Button befindet. Dieser ist ja aber per CSS ausgeblendet, den wolltest du nicht haben.

Also mal Wartungsmodus deaktivieren, ausloggen und schauen - da ist alles ok

**Comment by springers54** [comment]
Aber du kannst doch nicht damit rechnen, dass nur ausgeloggte User die Seite anschauen. Die meisten sind und bleiben auch längere Zeit eingeloggt oder loggen sich nie aus.

**Comment by joergsteinhauer** [comment]
Ok, das habe ich nicht bedacht. Wenn ihr also den Edit-Button überhaupt nicht braucht, entferne ich es komplett aus dem Markup und sorge dafür, dass die Linien entsprechend verschwinden. Das eine hängt mit dem anderen zusammen.

**Comment by springers54** [comment]
Den Edit-Button brauchen wir definitiv nicht, da es in meinen Augen keine saubere Lösung ist, auf einer Seite rumzudoktern

**Comment by joergsteinhauer** [comment]
sollte erledigt sein

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/51960186-2bad2400-2458-11e9-98f5-a7c8fab1c397.png)
Sollte Deutsch sein, wenn er nichts findet

**Comment by joergsteinhauer** [comment]
Erledigt. Falls wording nicht passt, bitte ansagen was da rein soll. Ich habe nach meinem Ermessen übersetzt.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/52360540-9ce26d80-2a3c-11e9-9b4f-54642af60cce.png)

Wenn man eine Seite aufruft, die es nicht gibt, daann kommt immer noch dies hier.

Kleiner Fehler:
NICHTS GEFUNDEN
Entschuldigung, es wurde nichts zu deinem Suchbegriffen gefunden. Bitte versuche es erneut mit anderen Suchwörtern.
  ... zu deinen

**Comment by joergsteinhauer** [comment]
Der Dt. text war nicht so passend, ich habe es anders gemacht. Zudem war die Sidebar nicht an der korrekten Stelle.

**Comment by springers54** [comment]
prima

**Comment by springers54** [comment]
https://zen-reiki.de/?s=ferneinweihung

Durch die geänderte Abstände sieht es nicht wirklich toll aus.

![grafik](https://user-images.githubusercontent.com/6114076/53584711-7ec3e500-3b84-11e9-99ef-94507eadcab2.png)
Meine Vorschläge:
 * [x] Zwischen den Suchergebnissen eine Linie ziehen, die eine optische Trennung macht
 * [x] Alle Titel fangen vorne links an
 * [x] die Metazeilen mit Datum und Kategorie sind überall einheitlich weg
 * [x] das Styling entspricht den üblichen Kurzfassungen auf den Themenseiten, also bis zum more darstellen und den Weiterlesen-Button anzeigen

![grafik](https://user-images.githubusercontent.com/6114076/53585023-47096d00-3b85-11e9-9fdf-62ba0a7d791f.png)

**Comment by joergsteinhauer** [comment]
Sollte erledigt sein oder fehlt was?

**Comment by springers54** [comment]
sehe erst einmal nichts.

**Comment by springers54** [comment]
Eine der Aufgaben war: die Metazeilen für Datum und Kategorie sind einheitlich weg, diese sind leider noch da, wie wir eben gesehen haben. 

 * [x] Datum, Autor und die beiden Striche weg
![grafik](https://user-images.githubusercontent.com/6114076/55133881-70d39680-5127-11e9-93e6-1e36bba28f01.png)

**Comment by joergsteinhauer** [comment]
Erledigt. Schließen?
