### ISSUE TITLE
Forum hat 2x H1

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#177]
... kannst du das weg bekommen?
![grafik](https://user-images.githubusercontent.com/6114076/50737378-c2275600-11c8-11e9-845f-95ccd121e983.png)

https://reiki-lernen.de/forum/

**Comment by springers54** [comment]
Geht hier weiter:
https://reiki-lernen.de/forum-3/
![grafik](https://user-images.githubusercontent.com/6114076/50737402-116d8680-11c9-11e9-9dde-4d64835d7772.png)
 Hier ist 2x H1 und eine H4

Und hier:
https://reiki-lernen.de/alle-foren/
auch 2 H1

**Comment by joergsteinhauer** [comment]
Ja, heir ist die Lösung auch darin, ein neues Template ohne die H1 zu erstellen. Somit wird dann die H1 aus dem Forum-Plugin genommen, was ja korrekt ist. 
Die H4 darf dann dort auch nicht sein, muss dann ein DIV werden oder so.

Schade nur, dass das Forum keine weiteren H-Titel hat.

**Comment by joergsteinhauer** [comment]
Habe hierfür ebenfalls ein Neues Template erstellt, welches keine H1 liefert.

Template Name - `Forum`

Die H4 auf https://reiki-lernen.de/forum-3/ habe ich entfernt, falls die Schrift größer sein muss, kann ich es noch extra anpassen.

**Comment by springers54** [comment]
super, danke, Schrift muss nicht größer sein.
