### ISSUE TITLE
Login-Seite neu stylen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#178]
Kannst du das Login anpassen? Im Moment ist das normale Wordpress login. Der untere Textbereich mit keine Schülerverwaltung mehr kann dann weg.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/51801454-5c197600-223e-11e9-9b57-e9683e589066.png)

Das Layout kann vom alten System übernommen werden, der komplette gelbe Bereich unten kann weg.

**Comment by springers54** [comment]
Ich habe  auf die Schnelle erst mal ein Plugin genommen, damit die Login-Seite nicht zu grottig ist.
Ich denke aber, dass wir darauf verzichten können, wenn du den alten Stand wieder eingebaut hast.

**Comment by joergsteinhauer** [comment]
Sollte erledigt sein. Plugin müsste noch entfernt werden, habe ich nicht gemacht, weil ich nicht weiß, ob du den noch irgendwie brauchst.

**Comment by springers54** [comment]
Plugin ist weg
