### ISSUE TITLE
Registrieren Seite stylen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#179]
da man sich jetzt auch als neuer Benutzer jetzt auch auf der Seite registrieren kann, wäre eine Anpassung an unser Layout auch sehr schön.

https://zen-reiki.de/wp-login.php?action=register

**Comment by joergsteinhauer** [comment]
Sollte nun automatisch durch das Stylen der Anmeldeseite erledigt sein. Bitte prüfen

**Comment by springers54** [comment]
danke, wir überlegen, hier ein Plugin zu nutzen für die Zukunft, um weitere Angaben, wie Adresse, mit erfassen zu können. Darum werden wir das wohl nochmal anfassen.
