### ISSUE TITLE
Styling Umfrage

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#180]
![grafik](https://user-images.githubusercontent.com/6114076/51746177-83890b00-20a5-11e9-8130-fe02aa737f2e.png)

Wir nutzen ein Plugin für eine Umfrage https://zen-reiki.de/internetschule/umfrage/

- [x] Texte der Überschriften linksbündig und nicht so fett
- [x] Button rechtsbündig
- [x] Umbrüche bei langen Antworten korrigieren

![grafik](https://user-images.githubusercontent.com/6114076/51746283-e11d5780-20a5-11e9-8d56-75039445507b.png)

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/53506681-cc721c00-3ab6-11e9-9983-df5aa1412a80.png)

Kannst du bitte noch die Ergebnisse stylen?
Um die Ergebnisse zu sehen, musst du dich in meinem Schüleraccount einloggen
Springer1
jane

 * [x] Ich würde es schöner finden, wenn die Balken nicht so hoch wäre und die Prozente in Klammern dahinter stehen würden. 
 * [ ] Anstelle von Votes was deutsches, wie Ergebnisse?
 * [x] Die Texte nicht fett bei den Antworten? Es wirkt im Verhältnis zur zarten Überschrift aufdringlich.

**Comment by joergsteinhauer** [comment]
Habe bis auf das Wording "voting" alles angepasst. 

Die Prozentzahl musste aber nach rechts, weil die sonst am "voting" Wording kleben bzw. dieses überdecken würde, wenn zu wenig abgestimmt wurde (<8%)

**Comment by joergsteinhauer** [comment]
Das Wort "voting" ist fest verdrahtet, es gibt auch keine Anpassung dafür in Einstellungen. Da kann ich nix machen, ggf. mal beim Support nachfragen.

**Comment by springers54** [comment]
Das ist gut so. Das Wording Voting ist nicht so dramatisch, dann bleibt es so.
