### ISSUE TITLE
Auswahlfarbe im Kontaktformular ändern

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#182]
![grafik](https://user-images.githubusercontent.com/6114076/52123629-06badb80-2627-11e9-90cc-1144ebdbe5c8.png)
https://zen-reiki.de/kontaktformular/

Wenn man das Menü aufkappt, entsteht ein blauer Rahmen und die Hinterlegung der Auswahl ist auch blau. Sollte unser Goldton sein

**Comment by joergsteinhauer** [comment]
Blauer Rahmen (Schatten) ist nun weg.

Die Hintergrundfarbe des aktiven Dropdowns kann man nicht stylen. Oder hast du irgendwo ein Beispiel? Ich fand jetzt keine Möglichkeit dazu.

**Comment by springers54** [comment]
ich leider auch nicht, hat auch nichts mit dem Browser zu tun oder der Farben, die man im Admin-Interface einstellen kann.
Ich denke, das kommt vom Contactform 7
https://www.seohit.de/css-code-contact-form-7/
`02 | Code Dropdown/ Select

.wpcf7 select {
color: black;
width: 25% ;
font-size:17px !important;
}

Code  für Euer Dropdown-Menu im Formular (=Select als Code im Formular). !important  bei der Schriftgröße bedeutet übrigens, dass der Befehl auf jeden Fall befolgt werden soll, egal ob es andere Befehle für denselben Wert innerhalb Eurer WordPress-Seite gibt.`

**Comment by joergsteinhauer** [comment]
Vorab: alle Design-bezogene Sachen, welche man irgendwie im Admin oder sonst wo einstellen kann, kann ich auch normal im CSS definieren. 

Dein Bsp-Code ist heir belanglos, das hat keine Auswirkung auf das, was du erreichen möchtest.

Die **blaue Hinterlegung** im Auswahl-Dropdown kann man nicht ändern. 

Man kann mit CSS aber durchaus die derzeit weiße Hinterlegung der inaktiven Felder stylen, aber das ist sicherlich nicht zielführend und nicht nutzerfreundlich. 

Man kann lediglich über JS ein Dropdown nachbauen, welches dann aus DIV's usw besteht und wo man quasi die Funktionsweise eines nativen Dropdowns nachbildet - und dann alle Elemente nach belieben stylen kann. Aber das ist völliger Humbug und unnötig.

**Comment by springers54** [comment]
Ok. Dann bleibt es so und ich schließe. Kein Aufwand, das ist die Sache nicht wert.
