### ISSUE TITLE
Themenseite zerschossen, bitte dringend klären!!!

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#184]
Leider fehlen auf der Themenseite jetzt komplett die kleinen Bilder und die Verlinkungen. Was ist damit passiert?
Es muss irgendwie am Styling liegen.
`<div class="box-image-preview has-3-items is-centered"><a title="Themen: Zen Reiki Internetschule" href="../themen/internetschule/"><img src="../wp-content/uploads/2019/01/Reiki-Internetschule256.jpg" alt="Themen: Internetschule" width="256" height="136" /></a><a title="Topics: Healing" href="../themen/heilen/"><img src="../wp-content/uploads/2019/01/Heilen256.jpg" alt="Themen: Healing" width="256" height="136" /></a><a title="Topics: Coaching" href="../themen/coaching/"><img src="../wp-content/uploads/2019/01/Coaching256.jpg" alt="Themen: Coaching" width="256" height="136" /></a><a title="Themen: Termine" href="../themen/termine/"><img src="../wp-content/uploads/2019/01/Termine256.jpg" alt="Themen: Termine" width="256" height="136" /></a><a title="Themen: Bücher" href="../themen/buecher/"><img src="../wp-content/uploads/2019/01/Buch256.jpg" alt="Themen: Bücher" width="256" height="136" /></a><a title="Themen: Symbols" href="../themen/symbole/"><img src="../wp-content/uploads/2019/01/symbol256.jpg" alt="Themen: Symbole" width="256" height="136" /></a><a title="Themen: Meinungen" href="../themen/meinung/"><img src="../wp-content/uploads/2019/01/Meinung256.jpg" alt="Themen: Meinungen" width="256" height="136" /></a></div>
[spacer]`

**Comment by joergsteinhauer** [comment]
Was, wo, warum? Ich sehe wieder weder einen Testlink noch einen Screenshot... Vorher/Nachher ist auch immer gut (als Screenshots bzw. kurzer Text)

**Comment by springers54** [comment]
Warum, weiß ich leider auch nicht. 
Alte Seite: https://zen-reiki-alt.zen-reiki.de/themen/
![grafik](https://user-images.githubusercontent.com/6114076/52353788-8386f480-2a2f-11e9-9815-e37bcb06be68.png)
Erstes Bild fehlt hier, nicht wundern

Neue Seite: https://zen-reiki.de/themen/
Der Block, der oben kodiert ist, fehlt komplett, es beginnt mit den Themen als Liste

Der Priview geht gar nicht mehr
![grafik](https://user-images.githubusercontent.com/6114076/52353925-cb0d8080-2a2f-11e9-9291-b9cad0b43026.png)

**Comment by joergsteinhauer** [comment]
Ich muss es wohl zuhause machen, da ich mich anmelden muss.

Gerade eben (nicht eingeloggt) sehe ich folgende Seiten:

https://zen-reiki.de/themen/
![grafik](https://user-images.githubusercontent.com/1843754/52354552-f0e75500-2a30-11e9-8c12-26d2b3432ce0.png)

https://zen-reiki-alt.zen-reiki.de/themen/
![grafik](https://user-images.githubusercontent.com/1843754/52354575-fcd31700-2a30-11e9-8a65-43001a4c0f1d.png)

**Comment by springers54** [comment]
ja, die Seite wird nach außen so angezeigt, die Bilder oben fehlen.
In der Vorschau kommt gar nichst. Auf der alten Seite musst du dich einloggen über den Admin-Link, sonst ist die offline wegen doppeltem Content

**Comment by joergsteinhauer** [comment]
Puh... also hier ist irgendwie komplett was falsch.
Ich habe gerade ewig gesucht, aber nichts gefunden.

Das Problem: Ich verstehe nicht, wie man diese Themen-Seite anpasst. Ich denke doch, das ist diese Seite hier:
https://zen-reiki.de/wp-admin/post.php?post=3210&action=edit

Aber egal wie ich den Quellcode anpasse, die Seite im Frontend (also https://zen-reiki.de/themen/) zeigt immer nur die Liste der Beiträge an. Auch wenn ich den Shortcode im Admin entferne. Ich kann die Seite im Admin sonst noch wie ändern, es passiert nichts! 

Bevor ich hieer weiter nachforsche, Gegenfrage: was habt ihr in der Zwischenzeit alles gemacht? Irgendwas komisches? Vlt. spielen Plugins verrückt? Oder hängt das mit dem Domain-Umzug zusammen? 
Ich kann noch nicht nachvollziehen, was hier abläuft.

Die Startseite z.b. kann ich ändern, die Änderungen sehe ich dann auch im Frontend.

**Comment by springers54** [comment]
Ich bin jetzt auf folgende Idee gekommen: Neue Seite erstellt und den Bildbereich kopiert, der wurde angezeigt.
Darunter dann deinen Link mit den Posts, wurden angezeigt
Alte Seite in den Papierkorb und neue Seite umbenannt. Hat auch funktioniert.
Warum es passiert ist, weiß ich nicht. Auf jeden Fall vermute ich, dass sich etwas in der Datenbank verhakt hat, was wir nicht durchblicken.

**Comment by joergsteinhauer** [comment]
Na sowas. Also ich dachte auch tatsächlich kurz daran, die Seite neu anzulegen... Denn da war definitiv irgendwas komisch nicht korrekt, kann ja wirklich Datenbank gewesen sein.
