### ISSUE TITLE
Seite für mobile Geräte optimieren

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#185]
Ich würde dir gern Zugriffsrechte geben, aber dazu brauche ich eine Google-Adresse von dir, sonst geht das nicht.

**Comment by joergsteinhauer** [comment]
qubicspace@gmail.com

**Comment by joergsteinhauer** [comment]
Anscheinend gibt oder gab es Probleme mit Forum-Seiten, explizit mit https://zen-reiki.de/forum/topic/vorstellung-3/

![image](https://user-images.githubusercontent.com/1843754/52500742-039f8c80-2bdf-11e9-821b-bd1a5c8ef697.png)

Ich habe in der Google Search Console etwas rumgespielt, getestet und die neu crawlen lassen. Ein manueller Test gab grünes Licht, also ich nehme an, dass das Problem bald erledigt ist. Google muss die Seite neu crawlen, das könnte dauern. 

-----------------------------

Mir scheint, als würde der Google Bot eine teils ungestylte Seite sehen. Evtl. werden die CSS Dateien nicht schnell genug geladen, sodass Google meckert. Wenn ich die Seite aber manuell aufrufe, sehe ich alles gestylt.

![image](https://user-images.githubusercontent.com/1843754/52501014-9b04df80-2bdf-11e9-9af8-79156946d677.png)

----------------------

Google meckert ja zwei Sachen an:

![image](https://user-images.githubusercontent.com/1843754/52501079-c7b8f700-2bdf-11e9-9b3d-0beebeb38c3d.png)

Wenn ich die Seite manuell teste, is alles ok.

Wir warten erstmal etwas ab, evtl. gibt es nach dem neuen crawlen Entwarnung.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/52517545-15178180-2c3d-11e9-8bd6-62851be4b920.png)
 * [x] Kannst du es bitte einstellen, dass die Bilder auf dem Handy bei class=alignleft_lehrer nicht in 300 Breite gezeigt werden? Hier reichen die 150 px als Breite aus. Oder sag, wie wir die Bilder anders einbinden können, dass der Text umfließt und die Bildgröße responsiv ist.

**Comment by joergsteinhauer** [comment]
Das initiale Problem ist gelöst:
https://search.google.com/search-console/mobile-usability?resource_id=https%3A%2F%2Fzen-reiki.de%2F&hl=de

![image](https://user-images.githubusercontent.com/1843754/52590245-1fa26880-2e41-11e9-9493-79ad42dfc4c5.png)

**Comment by springers54** [comment]
Ja, wir haben im Forum die Brotkrumen weggenommen. Das sollte eines der Probleme gewesen sein.
Die Breite der Bilder geht jetzt über die Hälfte des Handybildschirmes, schon besser. Könnte vielleicht etwas kleiner werden?

**Comment by joergsteinhauer** [comment]
Ist hier noch was zu tun? Die Vorschaubilder sind ja nun max. 150px breit.

**Comment by springers54** [comment]
Siehe #201. die Bildgrößen gehen immer noch nicht.

### Handy Hochformat Bildgrößenfestlegung:
 * [ ] Bilderbreite 1/3 auf den Übersichtsseiten, ist im Moment 1/2
 * [ ] Bilderbreite auf den Detailseiten 1/2

Hier ein Beispiel, wo es nicht funktioniert:
https://zen-reiki.de/bereich/meinung/warum-ich-reiki-lehrer-bin/

![grafik](https://user-images.githubusercontent.com/6114076/54880798-61afc880-4e49-11e9-82fe-179dd9267bc4.png)

Hier hatte ich einen spacer eingefügt, um einen Abstand zu erzwingen, was auf dem Handy offensichtlich gar nicht funktioniert.

Die Probleme aus #198 ziehen sich also überall durch
![grafik](https://user-images.githubusercontent.com/6114076/54880786-4e046200-4e49-11e9-880f-040395b0f453.png)

**Comment by joergsteinhauer** [comment]
Dei eBsp-Seite https://zen-reiki.de/bereich/meinung/warum-ich-reiki-lehrer-bin/ ist keine Übersichtsseite. Auch kein Archiv. Sondern ein "post".
Im #198 haben wir festgelegt, das die Vorschaubilder eben nur Übersichtsseiten 150px breit werden. Erinnerst du dich? Lese bitte dort die Kommentare durch.

Im #198 hatte ich übrigens den Versuch gemacht, die Vorschau-Bilder überall auf 150px zu reduzieren - Ergebnis war eine Aufregung deinerseits, dass es so nicht geht.

Was also tun? Ich kann durchaus eine neue Klasse anlegen, die das Bild auf 150px begrenzt. Ihr müsst die Klassen dann immer manuell einfügen. Was aber ziemlich blöd ist. Viel mehr sollte man auf die unterschiedlichen Seitentypen angehen (Übersichtsseite, Detailseite etc) und somit die Bildgrößen steuern. Entscheidung liegt bei euch.

-------------

> Die Probleme aus #198 ziehen sich also überall durch

Na ist doch logisch. Das Problem besteht ja weiterhin! Wie in #198 tausend mal erklärt, hängt das mit dem gefloateten Bild zusammen. Dein spaces bringt gar nichts, zumindest nicht im responsiven Verhalten. Bei Desktop UND dieser spezifischen Textlänge mag es gehen, aber nicht wenn die Seite dann andere Dimensionen hat. Ich hoffe du kannst es nachvollziehen?

**Comment by joergsteinhauer** [comment]
Fehlt heir noch was? Das Problem haben wir m.m.n. schon gelöst.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/56112135-6d7b4000-5f5a-11e9-9e5f-a6019d8f30bd.png)

Die Dinge sind leider nicht bearbeitet und auch oben nicht abgehakt.

Im Moment ist es genau falsch rum umgesetzt. **Die Bilder auf der Detailseite sind klein, die auf der Übersichtsseite groß.**

### Bild der Übersichtseite ist aktuell 50% der Breite
![grafik](https://user-images.githubusercontent.com/6114076/56112341-145fdc00-5f5b-11e9-91b5-7cbd0c6c788d.png)

### Bild der Detailseite ist aktuell 30% der Seite
![grafik](https://user-images.githubusercontent.com/6114076/56112382-3d806c80-5f5b-11e9-9a85-1cb551c3cd5d.png)

### Tabelle mit Bilder mobil zerschossen
![grafik](https://user-images.githubusercontent.com/6114076/56112437-66a0fd00-5f5b-11e9-82b9-91615b640785.png)

**Comment by joergsteinhauer** [comment]
Und immer wieder fehlen die URLs.... 

https://zen-reiki.de/bereich/symbole/shamballa-reiki-palm-meister-symbol/

**Comment by joergsteinhauer** [comment]
Mist, das Problem kam durch das JS aus dem #222... habe es dort erstmal deaktiviert, muss noch mal überdenken. 

Im Schlimmsten Fall müsst ihr händisch bei jedem Buch-Bild eine CSS-Klasse setzen, wäre das ok?

**Comment by springers54** [comment]
Ja, was soll es. wenn es nicht anders geht,  die Klasse heißt dann bitte wieder **rand** und nicht image preview

**Comment by joergsteinhauer** [comment]
Gut, damit durch mein JS es nicht woanders knallt, machen wir das über eine extra Klasse.
Die muss aber anders heißen - `rand` ist für andere Sachen reserviert.
Habe es erstmal `forceDefaultWidth` genannt. Die Funktion erschließt sich aus dem Namen, wir können es auch anders nennen - ihr müsst ja damit klar kommen.

Zu sehen hier beim ersten Bild zu "Chakras Tore zur Seele" 
https://zen-reiki.de/themen/bereich/heilen/

**Comment by springers54** [comment]
Also uns erschließt sich da nichts. Nenne es dann bitte **randb**. Bedeutet Rand für Buch.

**Comment by springers54** [comment]
Leider hat es wieder neue Fehler produziert, die Bilder auf der Übersichtsseite stimmen nicht von der Größe her.
https://zen-reiki.de/themen/bereich/heilen/

![grafik](https://user-images.githubusercontent.com/6114076/56784016-d2eaee80-67ee-11e9-9f08-d6e99b6b2f37.png)

**Comment by joergsteinhauer** [comment]
Dann eben `randb`.

**Comment by springers54** [comment]
Das randb geht leider auch nur in der Kombination mit left, sonst haut der Umbruch nicht hin.

Kann man die Stylingregel nicht so schreiben, dass randb die Funktionalität von left automatisch hat?

**Comment by joergsteinhauer** [comment]
Ja, klar. Habs angepasst
