### ISSUE TITLE
Wie breit ist der Inhaltsbereich nun wirklich?

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#186]
Ich kann mich erinnernt, dass wir mal gesprochen haben, dass ich die Bilder alle neu machen sollte auf den Themenseiten und auf 845 pix bringen. Das hatte ich auch gemacht, aber noch nicht alle hochgeladen.
https://zen-reiki.de/themen/buecher/

Aber nun ist der sogar kleiner als 800 px.
![grafik](https://user-images.githubusercontent.com/6114076/52461030-7ec85a80-2b6d-11e9-8e58-625474790ae1.png)

Können wir uns auf verbindliche Breiten einigen? Spricht etwas gegen die 800 px? denn das Skalieren kostet nur unnötig Ressourcen und macht die Bilder ja nicht besser. Wir sollten die schon in der Breite laden, wie wir sie auch brauchen.

**Comment by joergsteinhauer** [comment]
Ich weiß auch nicht mehr, wann und welche Größen wir definiert haben. Derzeitiger Stand ist 780px. So bleibt es auch.

**Comment by springers54** [comment]
Spricht etwas gegen 800 pix? Sonst müssen wir Bilder ändern.

**Comment by joergsteinhauer** [comment]
Hm, dann würden sich die Bilder kleiner skalieren und etwas unscharf werden.
Aber wenn es bereits so viele Bilder in 800px gibt, dann passe ich lieber die Breite der Content-Seite an (also linke Spalte). Die 20px machen nichts kaputt

**Comment by springers54** [comment]
Gut, dann bleiben wir bei einer Breite des mittleren Bereiches von 800 Px, wenn es keinen besonderen Hintergrund für die 780 px gab.

**Comment by joergsteinhauer** [comment]
Naja, eben nicht. Mein Vorschlag ist, den mittleren Bereich auf 780px zu kürzen.

**Comment by springers54** [comment]
Warum? Den Sinn durchblicke ich leider immer noch nicht.

**Comment by joergsteinhauer** [comment]
Sorry, habe mich total verguckt.

Also: die Bilder sind 800px, mittlerer Bereich war bei 780px. Ich habe diesen nun auf 800px erhöht, nun passt alles.

**Comment by joergsteinhauer** [comment]
Erledigt? Dann bitte schließen
