### ISSUE TITLE
Größenverhältnisse Handy Startseite

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#187]
![grafik](https://user-images.githubusercontent.com/6114076/52531782-115a2c80-2d1b-11e9-939e-c634fb271a47.png)
 * [x] könnten wir den oberen Bildbereich auf dem Handy kleiner gestalten, so dass man mehr von der Seite sieht? 
 * [x] Die Schrift im gelben Kasten von der Größe so einstellen, dass die Texte einzeilig bleiben, den gelben Bereich auch etwas kleiner in der Höhe.

Siehe: 
https://zen-reiki.de/

**Comment by joergsteinhauer** [comment]
Schrift im gelben Kasten ist bei mir bereits einzeilig.

**Comment by joergsteinhauer** [comment]
Bitte überprüfen. Reicht das so aus?

**Comment by springers54** [comment]
Ja, bis au,f dass bei mir immer noch die gelbe Zeile umbricht bei bestimmten Bildern könnte ich mit den Größen leben
Da du auch ein HTC hast, solltest du das wie ich sehen.
![grafik](https://user-images.githubusercontent.com/6114076/53069854-a8727180-34dd-11e9-81e8-ac63accf1493.png)

**Comment by joergsteinhauer** [comment]
Und, schlimm? Immer wieder die Sache, dass sich das Layout an Inhalt anpassen muss und nicht andersrum. Daher heißt es auch "responsiv"... aber egal, ich habe es nun so gemacht, sodass die Texte in eine Zeile reinpassen:
![image](https://user-images.githubusercontent.com/1843754/54866421-b7b23c80-4d73-11e9-88e6-eea509ab9a5d.png)

Im Falle dass die Texte länger werden, wirds wieder umbrechen.
