### ISSUE TITLE
Ebenfalls Schriften auf dem Handy

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#189]
![grafik](https://user-images.githubusercontent.com/6114076/52531884-b0cbef00-2d1c-11e9-94b7-196011570cda.png)
 * [x] Überschrift zu groß
 * [ ] Text darunter zu groß
 * [x] Bild damit zu hoch
 * [x] Abstand zum davorstehenden Text zu groß
 * [x] Button zu groß
Siehe:
https://zen-reiki.de/system/

**Comment by joergsteinhauer** [comment]
Text ist schon bei 16px, kleiner ist nicht gut. Das Thema hatten wir schon.

**Grundsätzliche Anmerkung:** 

ich merke gerade bei diversen kleinen Tickets, dass ich einfach an vielen Stellen kleine minimale Anpassungen vornehmen muss, was den Code wachsen lässt. Zum einen hat man dann eben mehr Code zum verarbeiten, aber was viel schlimmer ist: der Code wird unübersichtlich, schwer nachzuvollziehen und schwerer zu warten. 

Ich habe das Theme ja nicht ohne Grund von neu aufgebaut und darauf geachtet, dass der Code einfach und unkompliziert bleibt, das Design dabei aber doch recht gut aussieht.

Ich persönlich habe kein Problem damit, mich in em CSS zurecht zu finden. Aber perspektivisch, falls jemand anders daran arbeiten sollte, wird es lustig. Ich sage das jetzt gleich und habe das eigentlich schon mehrmals gesagt. 

Diese vielen kleinen Anpassungen, die m.M.n. nur eine Geschmackssache sind und nur wenig zur Usability beitragen,  werden sich noch negativ ausspielen. Das sage ich aus meiner Erfahrung.

**Comment by springers54** [comment]
Ja, ist ok so.
Zu den Änderungen im Styling:
Ich denke, der normale Arbeitsstil ist so, dass man je nach Bildschirmauflösung verschiedene css-Files erstellt und nur die lädt, die zutreffen. Einerseites weiß man dann, wo man suchen und anpassen muss, andererseits minimiert es den Code. Machst du das nicht so?

**Comment by joergsteinhauer** [comment]
Hm, nein, normalerweise ist es nicht so wie du sagst.

Würde man CSS erst dann nachladen, wenn sich die Seitenbreite ändert, würde man ggf. für einen kurzen Moment eine ungestylte Seite sehen. Das macht man so nicht.

Wichtig sind 2 Sachen:
1. der Code, der letztendlich geladen wird. Hier muss man den Code klein halten (modulares CSS, nachladen von Elementen, die nicht sofort sichtbar sind etc.). Modulares CSS schreibe ich immer, wo es geht. Nachladen des CSS ist eine Optimierung udn diese ist sehr schwer, vor allem auf solchen großen und komplexen Seiten wie ZR.
2. der Codeaufbau (Architektur) des unkomprimierten CSS (bei uns: sass). Dieser muss klar sein, gut strukturiert und leicht zum bearbeiten/erweitern. Es kommt schnell dazu, dass man (u.a. auch durch modulares CSS) an einer Stelle was ändert und an der anderen was kaputt geht. Daher: je kleiner und weniger Code man hat, desto besser.
