### ISSUE TITLE
Umbruch falsch bei ältere Beiträge

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#193]
![grafik](https://user-images.githubusercontent.com/6114076/52533774-280f7c00-2d39-11e9-928b-d6a6919a57a8.png)
https://zen-reiki.de/themen/neues/
 * [x] sollte immer linksbündig sein

**Comment by joergsteinhauer** [comment]
Erledigt? Dann bitte schließen.

Übrigens frage ich mich, ob du es mitbekommst, wenn ich ein Häkchen abhake?

**Comment by springers54** [comment]
Nein, eine Nachricht gibt es nicht. Aber ich sehe es, wenn du in der Issue kommentierst, dann hat diese einen blauen Strich. 
Also sowas wie Kontrolle und Schließen als Kommentar ist hilfreich.
