### ISSUE TITLE
Bitte keine Dateien überschreiben!!! hier .htacess

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#194]
Wir haben gerade gesehen, dass du unsere .htaccess überschrieben hast. Da wir hier Umleitungen eintragen, wenn wir Seiten löschen, bitte diese Datei nicht überschreiben und beim Überschreiben von anderen Dateien einen Blick auf dem Datum behalten.

**Comment by joergsteinhauer** [comment]
Hm, kann an sich gar nicht sein, die Datei habe ich nicht angefasst.... Ich arbeite nur mit CSS. Höchstens wurde das aus Versehen und ohne meinen Willen irgendwie automatisch überschrieben, kann ich mir aber nicht vorstellen...

**Comment by springers54** [comment]
es kann auch sein, dass ein Plugin bei der Installation solche Dinge macht, das ist mir jetzt auch klar geworden. Leider machen die nichts rückgängig, wenn man die wieder deinstalliert. Darum ist auch die Spielwiese zum Testen extrem wichtig. Also sollte keine Unterstellung sein, nur als Hinweis.
