### ISSUE TITLE
Forum auf dem Handy

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#195]
![grafik](https://user-images.githubusercontent.com/6114076/52534185-999df900-2d3e-11e9-9f2e-0c6858e40e94.png)
Man sieht auf dem Handy vom Forum leider so gut wie nichts, weil die Felder oben zu dominant sind.
 * [x] Bitte Höhe verringern und Schriften kleiner machen, die untere Höhe des goldenen Bereiches reicht aus.
 * [x] könnte man das gelbe Hinweisfeld auf dem Handy vielleicht komplett weglassen

**Comment by joergsteinhauer** [comment]
Wie wäre es zusätzlich damit, das Bild weg zulassen? Zumindest dann mobil.

**Comment by joergsteinhauer** [comment]
Den Rest habe ich angepasst

**Comment by springers54** [comment]
So sieht es jetzt aus:
![grafik](https://user-images.githubusercontent.com/6114076/52995278-6f24fd80-341a-11e9-9535-24c1218718dd.png)
 * [x] Die Menüleiste ist kleiner, das Suchfeld darunter sollte in der Höhe nicht unterschiedlich zu Leiste sein, also bitte auch in der Höhe verkleinern
 * [x] Das gelbe Feld auf dem Handy komplett weg
 * [x] Die Themenbalken in der Größe dem neben dem Menü anpassen, diese Balken haben ja ohnehin keine Funktion und nehmen nur viel Platz in der Breite weg,

**Comment by springers54** [comment]
> 
> 
> Wie wäre es zusätzlich damit, das Bild weg zulassen? Zumindest dann mobil.

Bild ist schön und sollte bleiben

**Comment by joergsteinhauer** [comment]
> Bild ist schön und sollte bleiben

Das wird eine Logik sein, die ich wieder nicht nachvollziehen kann.
Am Ende muss die Seite funktionell, da geht Funktionalität vor Schönheit. Aber bei diesem Element haben wir wohl eine Ausnahme...

**Comment by springers54** [comment]
Super, Frauen müssen ja anders ticken, ist normal.
Aber eine Kleinigkeit haben wir noch. 
 * [x] Kannst du die Abstände in der Statistik verkleinern? Die ist sehr auseinander gezogen.
 * [ ] Die Icons sollten bündig sein, das in der 2. Zeile ist durch die Zahl zu weit links
![grafik](https://user-images.githubusercontent.com/6114076/53070345-21be9400-34df-11e9-8d07-ce82bc276669.png)

**Comment by joergsteinhauer** [comment]
> Die Icons sollten bündig sein, das in der 2. Zeile ist durch die Zahl zu weit links

Das geht nicht ohne Weiteres. Hier müsste man das Markup ändern und das geht nicht. Wäre ein eingriff in das Plugin und beim nächsten Update weg. 

Außerdem ist es doch gar nicht schlimm - der Inhalt ist eben flexibel und richtet sich nach dem Inhalt aus, so wie es sein soll.

Das ist wieder so ein typisches Bsp für ein nicht vorhandenes Problem ;)
