### ISSUE TITLE
Themenseite Ergänzung Größen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#196]
Hier noch einmal ein Screen
![grafik](https://user-images.githubusercontent.com/6114076/52534324-82600b00-2d40-11e9-8b6b-219aa1422f0a.png)
https://zen-reiki.de/themen/

Die H1 sollte kleiner sein, vielleicht auch die Abstände insgesamt reduzieren. Die untere Überschrift müsste deutlich kleiner sein.

**Comment by joergsteinhauer** [comment]
Ist das noch aktuell? Ich habe die Titel bereits angepasst, glaube ich. Für mich sehen die jetzt gut aus.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/52994712-c0cc8880-3418-11e9-8f2d-9a764b9d7ecd.png)
Alles viel zu groß, ich sehe zwar, dass du es verkleinert hast, aber das ist noch lange nicht das, was wir uns darunter vorstellen

Mobile Darstellung muss wirklich mehr an den zur Verfügung stehenden Platz angepasst sein, hier ein Beispiel
![grafik](https://user-images.githubusercontent.com/6114076/52994881-45b7a200-3419-11e9-9ae2-1c18790dd148.png)

Ich weiß zwar, dass du immer für luftig bist, aber auf dem Handy ist das leider Platzverschwendung.

**Comment by joergsteinhauer** [comment]
Nochmal angepasst, bitte überprüfen.

Titel kleiner machen geht nicht mehr, dann hätte er gleiche Größe wie Fließtext

**Comment by springers54** [comment]
Also die Größen wären ok so, aber:
 * [ ] Block mit diesen Daten komplett weg, ist auf den anderen Themenseiten auch nicht da.
 * [ ] Beim Bild ist zwar jetzt das Icon für das fehlende Bild weg, leider das Bild auch. Auch das hätten wir gerne, wie auf den anderen Themenseiten auch. Dieses Bild sollte eine Größe haben, wie die Bilder auf der Themenseite, also 1/3 der Seitenbreite einnehmen.
![grafik](https://user-images.githubusercontent.com/6114076/53070974-0c4a6980-34e1-11e9-807d-3351c89a5d7e.png)

Andere Themenseiten:
Hier haut die Einbindung der Bilder wieder gar nicht mehr hin, schlimmer als vorher.
 * [ ] gleiche Festlegung: Bilder 1/3 der Seitenbreite
 * [ ] Abstand der Linie nach dem Weiterlesen-Button sowie vor dem nächsten Titel bitte verrringern.
![grafik](https://user-images.githubusercontent.com/6114076/53071031-4f0c4180-34e1-11e9-9263-db51ecc6aa08.png)

**Comment by springers54** [comment]
Wir haben für die Übersichtsseite der Themen eine andere Lösung gefunden. Damit wird diese Seite wie die anderen Kategorieseiten erzeugt und jede Art von Sonderbehandlung dieser Übersichtsseite hat sich damit erledigt.
Kannst es dir auf dem Testserver unter: 
https://zen-reiki-energieshop.de/themen/_/
ansehen
