### ISSUE TITLE
Startseite auf dem PC

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#197]
Wenn man unsere PC-Version kritisch anschaut, dann wird dort auch durch die Bilder und Schriften und Abstände extrem viel Informationsfläche verschenkt. Ich denke mal, viel größer haben die wenigsten Nutzer ihr Fenster und dann kommt die Seite so rüber:
![grafik](https://user-images.githubusercontent.com/6114076/52909080-20dcf680-3282-11e9-85bb-c3cd16253086.png)

Diese Bildhöhe im Banner würde für uns ausreichen
### Bild2
![grafik](https://user-images.githubusercontent.com/6114076/52909061-d9ef0100-3281-11e9-883f-af9e1eccac60.png)
Weiterhin sollte der Abstand vor der H1 kleiner sein und die H1 selbst auch

**Comment by joergsteinhauer** [comment]
Angepasst, passt so?

**Comment by springers54** [comment]
Ist zwar schon besser, aber bitte weiter verringern
 * [x] Bild in der Höhe weiter reduzieren
 * [x] damit den Abstand auch noch etwas kleiner machen
 * [x] H1 und die darunter befindliche Überschrift verkleinern
![grafik](https://user-images.githubusercontent.com/6114076/52994511-15bbcf00-3418-11e9-8a18-9fcf8b3aacda.png)

**Comment by joergsteinhauer** [comment]
Angepasst.

Ich verstehe aber nicht die Angst, zu viel Platz "zu verschenken". Ist ja nicht so, dass der User es nicht gewohnt ist zu scrollen. 
Ja, es muss ausgewogen sein. Nicht zu viel Leerraum, aber auch nicht zu angeklatscht. 
Am Ende sind diese Unterschiede jetzt alles Geschmackssache. Nach meinem Geschmack war alles ok. Übrigens basiert ja das ganze Layout/Design auf bestimmten Abständen - und wenn man jetzt anfängt an einer Stelle zu verkleinern, muss man ggf. auch andere Elemente verkleinern - das wollen wir sicherlich nicht.

Ich empfehle ganz stark, nicht noch weiter Sachen zu verkleinern. Vor allem auf Desktop. 
Mobil muss noch einiges gemacht werden, da gibts Tickets dazu - alles ok. Hier war ja auch nicht wirklich was optimiert bisher.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/53037757-526ce200-347b-11e9-9b43-1a2fbe3a87a6.png)
Unklar ist, warum nun ein vollkommen anderer Ausschnitt gezeigt wird, oder du hast es noch drastischer verändert, um uns zu zeigen, dass es kacke aussieht. Also es sollte schon die Höhe haben, wie es oben im Bild 2 gezeigt.

**Comment by joergsteinhauer** [comment]
So, natürlich habe ich es mit Absicht "kacke" gemacht. *Ironie off*

In deinem Bild 2 hast du runter gescrollt und somit einen beliebigen Abschnitt gewählt, ohne zu zeigen wo das Bild eigentlich anfängt. Das bringt mir nix. Zudem weiß ich nicht, wie die anderen Bilder aussehen sollen. So wie ich es vermute, muss ich die Bilder neu zuschneiden, Anpassung über CSS wird wohl nicht reichen. 

Bevor ich hier weiter pixel schubse, bitte von allen 3 Bildern einen Screenshot machen bzw. Ausschnitt auswählen. Dabei drauf achten, dass sich der Ausschnitt wie gehabt verändert, sobald man die Seitenbreite ändert:
https://gyazo.com/c67a3ba1a9a09702ca417774aa22945a

**Comment by springers54** [comment]
# 1. Problem
 
* [x] Möglichkeit zur Änderung der Slider schaffen, zur Not im css, habe gesehen, wo ich die Bilder austauschen kann, aber keine Möglichkeit, die Höhen zu beeinflussen

![grafik](https://user-images.githubusercontent.com/6114076/53072514-98f72680-34e5-11e9-998c-3423cd848ed1.png)
Ich habe jetzt hier eine Höhe von 400px ausprobiert. Kann aber leider nicht testen, wie das eingebaut aussehen würde.
Die Bilder können wir selbst aufbereiten, wenn du die Koordinaten vorgibst. Leider müssten sie wohl breiter sein, was würde passieren, wenn jemand einen sehr großen Monitor hat und das Bild die Breite nicht bringt? Wiederholt es sich dann oder setzen wir es in die Mitte auf einen Untergrund, der immer breit genug ist?

# 2. Problem

 * [ ] zu den Größen: Ich sehe jetzt im Slider eine Höhe von 316 px, das ist definitiv zu wenig. Wir haben es jetzt auf 440Px gebracht, was sogar den Vorteil hat, dass nichts mehr skaliert werden muss
![grafik](https://user-images.githubusercontent.com/6114076/53188806-6729b100-3606-11e9-832a-b475a86ecf98.png)

Sorry, ich habe mal in deiner css gespielt
![grafik](https://user-images.githubusercontent.com/6114076/53188866-84f71600-3606-11e9-8c4f-66edf07d4469.png)

# 3. Problem

 * [x] Der Abstand zwischen den 3 Punkten und der ersten Überschrift könnte etwas größer sein, sagen wir 30% der jetzigen Höhe mehr. Dann wird es luftiger.

**Comment by joergsteinhauer** [comment]
# 1. Problem

Die Höhe kann man nun in der `custom.css` anpassen.

**Achtung:** bitte im entsprechenden Ticket (in diesem Fall also hier) immer Bescheid geben, wenn du in der `custom.css` geschrieben hast. Dann muss ich die vorher runterladen, sonst wird sie von meinem stand überschrieben!

Das Slider-Bild geht über die gesamte Bildschirmbreite. Du kannst gern dein Browser Fenster über 2 Monitore ziehen (falls du die hast), dann sieht man das gut. Die Höhe beibt jedoch fest, also wird das Bild oben und unten gleich abgeschnitten und bleibt vertikal mittig. Das Bild wiederholt sich nicht.

Jedoch haben die meisten Bildschirme ähnliche Seitenverhältnisse: 16:9 oder 4:3, d.h. in meisten Fällen bleibt das Layout genau so wie du es siehst. Die meist benutzen Bildschirmgrößen sind HD (1920x1080). Du kannst auch gern über Analytics schauen (falls wir das schon haben oder hatten), welche Bildschirmgrößen eure User haben.

Wenn man nun aber das ganze im Hochformat auf Smartphone anschaut, ist es genau umgekehrt. Bild wird rechts/links abgeschnitten. 

# 2. Problem

Soll ich hier noch was machen?

Hast du in der style.css geschrieben? Die wird von mir halt immer überschrieben (so auch gerade eben), wir haben uns ja drauf geeinigt, dass nur ich daran arbeite. Aber deine Anpassung (50vh) ist jetzt in der custom.css --> hier müssen wir aufpassen und ich darf deine Änderungen nicht überschreiben.

# 3. Problem

Ich habe 50% gemacht.

**Comment by springers54** [comment]
Die Zu 2,
Ja, hatten wir, weil ich nicht verstanden habe, wie das mit der costume.css gemacht wird, es dir deshalb aber auch geschrieben.

**Comment by joergsteinhauer** [comment]
Alles ok, ich wollte nur wissen lassen, dass deine Änderungen in der style.css weg sind.

Ist hier noch was zu machen?

**Comment by springers54** [comment]
Wir haben noch Kleinigkeiten angepasst, unter anderem die Farbe der Überschrift im unteren Block, die nun dunkel ist. Da die Größen durch die Verringerung der Überschriften mit dem darunter stehenden Text gleich waren, hat es sich zu wenig abgehoben.
![grafik](https://user-images.githubusercontent.com/6114076/53409661-c9493400-39c1-11e9-95bc-0c0e35d8b156.png)
