### ISSUE TITLE
Bezeichner für Stylingreglen verständlicher machen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#202]
Die Klassen kamen vor dir, die Bezeichner verstehe ich leider nur teilweise. Dazu mache ich eine neue Issue auf:
 class="alignleft lehrer image-preview  diese Klasse stand für ein Bild mit Rahmen, das linksbündig ist und vom Text umflossen wird.

_Originally posted by @springers54 in https://github.com/springers54/reiki/issues/198#issuecomment-465872106_

**Comment by joergsteinhauer** [comment]
Sollte nun gelöst worden sein, es gibt ja die neuen Klassen `left rand`
