### ISSUE TITLE
Abstände Themen-Übersichtsseite

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#203]
![grafik](https://user-images.githubusercontent.com/6114076/53148088-df15be00-35a9-11e9-8c89-fbca3910390f.png)
 * [x] Abstand Überschrift viel zu groß auf 1/3 reduzieren
 * [x] Abstand Linie Button oben und unten ca halbieren

**Comment by springers54** [comment]
durch unsere Lösung hat sich zwar das erste Abstandsproblem gelöst, nicht das vor und nach der Linie.

 * [ ] Bitte die kopierten Inhalte für die Themenseite aus dem alten Cherry-Framework wieder entfernen, das brauchen wir nun nicht mehr.

**Comment by joergsteinhauer** [comment]
Darf ich frage, wie eure Lösung war?

-----------------------

> * Bitte die kopierten Inhalte für die Themenseite aus dem alten Cherry-Framework wieder entfernen, das brauchen wir nun nicht mehr.

Hm ja, ich glaube zu wissen, was du meinst. Das war ein Shortcode aus dem alten Cherry-FM... nur finde ich es nirgendwo mehr auf den Seiten. Wo haben wir denn das eingefügt gehabt? Ich bilde mir ein, das war auf der Themen-Seite... Ich sehe es dort nicht. Ich vermute, die Struktur der Seiten habt ihr geändert, ich finde mich nicht mehr zurecht. Ich lösche erstmal keinen Shortcode, nicht dass da was anderes kaputt geht.

**Comment by springers54** [comment]
Die alte Themenseite, die den Shortcode enthalten hat, habe ich gelöscht, da sie ja nun als Kategorie weiter existiert und ich Verwirrungen  vermeiden wollte.
Sie wäre noch im Papierkorb, falls du nochmal schauen möchtest.

Die Abstände sind ok so

> Darf ich frage, wie eure Lösung war?

Ich hatte die Veränderung im Styling-Editor vornehmen können, war aber noch nicht soweit gekommen, die Regel zu schreiben. Aber hat sich ja inzwischen erledigt.
