### ISSUE TITLE
Bilder auf der Hauptseite Themen fehlen auf allen Geräten

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#204]
Also die Größen wären ok so, aber:
 * [ ] Block mit diesen Daten komplett weg, ist auf den anderen Themenseiten auch nicht da.
 * [ ] Beim Bild ist zwar jetzt das Icon für das fehlende Bild weg, leider das Bild auch. Auch das hätten wir gerne, wie auf den anderen Themenseiten auch. Dieses Bild sollte eine Größe haben, wie die Bilder auf der Themenseite, also 1/3 der Seitenbreite einnehmen.
![grafik](https://user-images.githubusercontent.com/6114076/53070974-0c4a6980-34e1-11e9-807d-3351c89a5d7e.png)

Andere Themenseiten:
Hier haut die Einbindung der Bilder wieder gar nicht mehr hin, schlimmer als vorher.
 * [ ] gleiche Festlegung: Bilder 1/3 der Seitenbreite
 * [x] Abstand der Linie nach dem Weiterlesen-Button sowie vor dem nächsten Titel bitte verrringern.
![grafik](https://user-images.githubusercontent.com/6114076/53071031-4f0c4180-34e1-11e9-9263-db51ecc6aa08.png)

_Originally posted by @springers54 in https://github.com/springers54/reiki/issues/196#issuecomment-465443373_

**Comment by springers54** [comment]
Aus meiner Sicht sind vor allem die Abstände oberhalb und unterhalb der Trennlinien offen

**Comment by joergsteinhauer** [comment]
URL?

Also wenn ich über das Menü auf die Themen Seite gehe, komme ich auf https://zen-reiki.de/themen/_/

Was ist das für Unterstrich nach dem Slash? Habt ihr was am Menü umgebaut? Bevor ich an irgendwelchen Sachen arbeite, wäre gut, wenn ich erfahre, welche grundlegenden Änderungen vorgenommen wurden.

Die https://zen-reiki.de/themen/ lässt sich nicht aufrufen, kommt eine Fehlerseite.

------------------

Zudem sehe ich, dass die Bilder (Kacheln) auf die "normalen" Unterseiten verlinken (also z.b. https://zen-reiki.de/themen/themen/neues/), die eigentlich gleichen Verlinkungen in der Sidebar (und auch die Links aus angeteaserten Beiträgen selbst) aber auf die **Unterstrich** Unterseiten (z.b. https://zen-reiki.de/themen/_/neues/):
![image](https://user-images.githubusercontent.com/1843754/53441229-a12ff400-3a06-11e9-88f3-b611d9224cee.png)

Ist es Absicht oder alles noch eine Baustelle?

**Comment by springers54** [comment]
Es ist Absicht.
Das Problem kam daher, das diese Themenseite aus dem alten Framework kam, das du kopiert hast. Damit haben wir viele neue Probleme eingeschleppt, Bilder fehlten, Metadaten der Seite da, Abstände waren anders als in allen anderen Kategorieseiten.

Da diese Probleme seit längerer Zeit bestanden und nicht gelöst wurden, haben wir nach einer eigenen Lösung gesucht.

Das ist diese neue Kategorie, die nun leider als übergeordnete Kategorie überall erscheint.
Inzwischen nicht mehr themen/_/ sondern themen/1/

Leider habe ich noch nicht hinbekommen, wie man die alte Seite https://zen-reiki.de/themen/ auf die Seite
https://zen-reiki.de/themen/ 1/ umleitet, meine Versuche dazu sind fehlgeschlagen.

Der Vorteil, den wir nun haben, ist, dass alle Seiten wirklich gleich gebaut sind, das erspart uns allen Ärger und Zeit.
