### ISSUE TITLE
Dein mobiles Menü erst einmal ausblenden?

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#205]
Da es sich gegenwärtig verhakt, wäre es gut, wenn du dein mobiles Menü bis zur Umgestaltung erst einmal ausblendest.

**Comment by springers54** [comment]
Nicht ausblenden, aber vielleicht mal ein oder zwei kleine Anpassungen:
![grafik](https://user-images.githubusercontent.com/6114076/53240775-eae3ac00-369f-11e9-93a6-89b2bd994258.png)

Dann sähe es schon eine Ecke besser aus. Such noch den Mouse-Over-Effekt, der passt durch die Änderung der Farbe noch nicht. Kannst du vielleicht schneller machen.

 * [x] Hintergrundfarbe des Menüs ändern
 * [x] Mouseover auf Orange setzen
 * [x] Abdunklung reduzieren wie im Bild

Danach kann das Plugin für das mobile Menü wieder weg und du kannst dich in Ruhe mit dem Problem des Einklappens beschäftigen. Die Menülänge haben wir reduziert, so das es eigentlich erst mal gehen würde.

**Comment by joergsteinhauer** [comment]
Das waren alle 3 Sachen, die du im Live-Editor gemacht hast. Habe diese in das globale CSS übertragen. 
Meintest du beim "Mouseover auf Orange" die Textfarbe oder Hintergrund?

**Comment by springers54** [comment]
Ich habe das gestern im costum.css-Editor gemacht und es hat so funktioniert, wie es sein soll. Meine Jungs haben mir geholfen.
Mobiles Menü-Plugin hatte ich auch bereits ausgeblendet

> Meintest du beim "Mouseover auf Orange" die Textfarbe oder Hintergrund?

Die Textfarbe, das habe ich auch hinbekommen.

Sehe noch ein paar andere Baustellen, da frage ich meine Jungs heute nochmal nach einem Tipp.

**Comment by springers54** [comment]
ist jetzt auch in der Costum.css verankert. Vielleicht nicht ganz perfekt, aber ok so.
Zumindest verschwinden die ausgewählten Menüpunkte nicht mehr.
