### ISSUE TITLE
Unterschiedliche Bildgröße auf der Themenseite Meinungen und Umbruchfehler

### ISSUE THREAD

**Issue by Dani2909** [springers54/reiki#206]
![grafik](https://user-images.githubusercontent.com/39252760/53148730-eb9b1600-35ab-11e9-8f3e-54c82956a486.png)

* [x] die Bilder sind auf der Themenseite Meinungen alle unterschiedlich groß, sollten aber einheitlich sein.
* [x] der Umbruch passt nicht mehr, der Text beginnt nun unter dem Bild

**Comment by springers54** [comment]
Habe eine Stylingregel gemacht, die den Umbruch einstellt bei den Meinungsbildern und auch die Ausrichtung Text und Bild anpasst:
`figure.featured-thumbnail.thumbnail {
    margin: 0.5em 1em 0 0;
    float: left

}`

Die Größe aller Bilder hatte @Dani2909  angepasst, die sollten passen

**Comment by springers54** [comment]
### Problem: Umbau macht Stylingregeländerung erforderlich
Wir hatten hier mit dieser Regel es geschafft, dass die Texte um die Bilder beim Posttyp testi richtig ausgerichtet waren. 


Habe nun eine neue Regel gemacht:
figure.featured-thumbnail.thumbnail {
    margin: 0.5em 1em 0 0;
    float: left

}

Die obige ist wirkungslos geworden: Neu funktioniert
.post-thumbnail img, .entry-content p img {
   
    float: left;
    margin: 0.4em 1.1em 0 0;
}

Damit könnte die obere dann weg, wenn sie keine Wirkung mehr hat.
 * [ ] Veränderungen in Styling vornehmen siehe  auch #214
