### ISSUE TITLE
Überschriftenstruktur Startseite

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#207]
Ich habe nun alle versteckten H1 wieder eingeblendet. Sieht erstmal alles gut aus, musste hier und da etwas am CSS anpassen... aber es scheint erstmal zu funktionieren.

Die H1 hat jetzt die gleiche Größe wie die H2. 
D.h. ihr müsst jetzt eben auf jeder Seite die H-titel anpassen.

Zudem sehe ich, dass derzeit die H1 über dem Seiten-Thumb-Bild geladen wird:
https://reiki-lernen.de/faqs/
![image](https://user-images.githubusercontent.com/1843754/48896918-1361cd00-ee49-11e8-9b5c-3d3aff241585.png)

Ist es ein Problem? Rein syntaktisch macht es schon so Sinn, dass der Titel oberhalb des Inhalts steht. Und das Thumb-Bild ist eben Teil des Inhalts.

_Originally posted by @joergsteinhauer in https://github.com/springers54/reiki/issues/160#issuecomment-440983879_

Irgendwas ist jetzt hier ziemlich schief.
Es gibt keine H1 mehr, auf die H2 folgt die H5
![grafik](https://user-images.githubusercontent.com/6114076/53190368-b7564280-3609-11e9-83fd-3a508f093ca0.png)

**Comment by joergsteinhauer** [comment]
Lag daran, dass sich in der H1 ein SVG Code befand, das war nicht valide. Die H5 habe ich gegen H3 getauscht.

**Comment by springers54** [comment]
prima, jetzt sieht das wieder sauber aus.
