### ISSUE TITLE
HTML-Check

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#209]
Ich habe gerade mal unsere Seite durchlaufen lassen, da kommen eine Reihe von Fehlern.
Vielleicht kannst du damit etwas anfangen:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fzen-reiki.de%2F

**Comment by joergsteinhauer** [comment]
Ist das wirklich so wichtig? also grobe Fehler sind kritisch, diese heir sind unkritisch und machen nichts kaputt. Google sieht das zwar nicht gern, aber die Seite ist dadurch nicht kaputt und wird nicht so schnell "abgestraft". Das ist jetzt so meine Erfahrung.

Ich fange aber schon mal an. 

Einige Fehler kommen von Plugins. Einige aber auch aus meinen shortcodes.

**Comment by joergsteinhauer** [comment]
1. Doppelte meta name="description"

Es gab anfangs nur einen meta tag, der war fest im Template verbaut. Dann habt ihr Yoast Plugin eingebunden und dadurch kam der zweite meta tag. Plugin ist nicht durchdacht... Hab den festverbauten meta tag entfernt.

**Comment by joergsteinhauer** [comment]
2-8 Warnings: das kommt aus dem WP Core und ich kann hier nichts machen. Sind auch keine Fehler und vollkommen ok.

**Comment by joergsteinhauer** [comment]
9. Fehler:

Der kommt dadurch, dass irgendjemand diese Überschrift im Editor mittig ausgerichtet hat. So geht das nicht. Die Überschrift hatte eigentlich die Klasse `zr-title-tertiary`, diese wurde dann wohl irgendwann durch `title-h2` ersetzt. Warum?

![image](https://user-images.githubusercontent.com/1843754/53765908-9fb46f00-3ed1-11e9-948e-8858321d3f13.png)

Das gleiche gilt weiter für Fehler 14.
![image](https://user-images.githubusercontent.com/1843754/53766163-66c8ca00-3ed2-11e9-9e7d-dafe168dc8a6.png)

**Comment by springers54** [comment]
Zu Fehler 9 und 14
der Text ist uns zu groß gewesen und darum ist das keine Überschrift, sondern ein Absatz geworden
![grafik](https://user-images.githubusercontent.com/6114076/53802409-0e311580-3f42-11e9-9135-91b09da72aa5.png)

**Comment by joergsteinhauer** [comment]
Zu Fehler 9 und 14

Ok, ber dann sagt es doch mir. Denn jetzt sieht man, was rauskommt, wenn man Sachen nicht korrekt implementiert.

**Comment by springers54** [comment]
wir hatten an diesem Punkt gemeckert, weil es uns nicht gefallen hat. Du hast von manchen Dingen eine andere Styling-Auffassung. Dann haben wir selbst eine Lösung gesucht. Wenn du es nun besser machen kannst, soll es uns recht sein.

**Comment by joergsteinhauer** [comment]
Habe die Probleme 9 und 14 nun gelöst.

**Comment by joergsteinhauer** [comment]
Es bleibt nur noch das Problem mit meinen Shortcodes offen, da war ich schon mehrmals dran, fand aber bis jetzt keine Lösung. Das nervt mich selber ziemlich arg.

**Comment by joergsteinhauer** [comment]
@springers54 können deine Jungs evtl. das Problem mit dem invaliden Markup bei Shortcodes anschauen? Wie gesagt, ich habe mich damit schon stundenlang rumgeschlagen. Auch wenn ich die Shortcodes selber entwickelt habe, ist mir dieses Problem erst im Nachhinein aufgefallen.

### Problem mit dem "auto p-tag"

Wordpress fügt immer automatisch p-tags um die Blöcke, sobald man ein Neuzeile einfüg u.ä. 
Nennt sich **wpautop filter**.
An sich ist es ein hilfreiches Feature. Jedoch fügt genau dieser Filter auch in meinen Shortcodes unnötige schließende p-tags, obwohl ich das dort nicht brauche.

Ich habe schon einiges Probiert - Leerzeilen/Umbrüche vermieden, weitere Filter zum Deaktivieren des wpautop Filters eingesetzt - hilft alles nicht. Manche Filter haben dann auf allen anderen Seiten die automatischen p-tags komplett entfernt, sodass das ganze Layout kaputt ging. 

Ich schätze, es müssten meine Shortcodes Funktionen angepasst werden.

Z.b. die Service-Box auf der Startseite. 
![image](https://user-images.githubusercontent.com/1843754/53912749-e3d27b80-4059-11e9-8be7-da452ae8ee28.png)

Die entsprechenden Funktionen sind in der `wp-content/themes/zen-reiki/includes/functions/custom-post-type-short-codes.php` zu finden:

Die Funktionen heißen:
**function service_box_func
function service_box_wrapper_func**

Hier ist der störende schließende p-tag zu sehen:
![image](https://user-images.githubusercontent.com/1843754/53912182-a8837d00-4058-11e9-8930-81965e2e90cd.png)

**Comment by joergsteinhauer** [comment]
Habe Maik per Mail angeschrieben, gabs  noch kein Feedback.

Da ich hier nicht voran komme, mache ich erstmal wo anders weiter.
