### ISSUE TITLE
Systeme fehlen auf der Systemseite, weil die Zahl der Blogbeiträge reduziert ist

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#211]
Wir scheinen sehr ungünstigen Verkopplungen zu haben.
![grafik](https://user-images.githubusercontent.com/6114076/53585693-ccd9e800-3b86-11e9-81be-4fe3e1129a8e.png)

Hier wird festgelegt, wieviele Beiträge auf einer Seite gezeigt werden. Diese Zahl sollte nicht zu groß sein, damit die Leser auf dem Übersichtssteiten nicht erschlagen werden.

Leider hat diese Einstellung auch auf andere Bereiche Einfluss. So werden auf der Systemseite auch nur 6 Systeme angezeigt, obwohl wir mehr haben, bei dem Lehrern wurden auch nur 6 Lehrer gezeigt. Das reicht zwar im Moment, aber vielleicht auch langfristig wieder nicht.

**Problem 1: Auf Seite Systeme https://zen-reiki.de/system/ bitte alle anzeigen**
![grafik](https://user-images.githubusercontent.com/6114076/53586023-92247f80-3b87-11e9-88f9-4fc3ba804baf.png)

 * [ ] Bitte die Zahl der Beiträge, die auf Übersichtsseiten gezeigt wird von der Einstellung auf den Seiten Systeme und Team abkoppeln.

Habe eben nochmal nachgeschaut, auf den Übersichtsseiten kommen 7 Beiträge, wobei hier für mich sogar 5 ausreichen würden.

**Comment by joergsteinhauer** [comment]
Ich habe damit gerade eine halbe Std. verbracht und keine Lösung gefunden. Wird tricky sein. Weiß nicht, ob ich das hin kriege... das ist was globales und erfordert fundierte WP Kenntnisse. 

Ich habe schon mal gefragt, ob es nicht Sinn macht, bei solchen Themen einen entsprechenden WP Entwickler ranzuholen?

**Comment by springers54** [comment]
hab ich auch was gefunden und mit Hilfe meiner Jungs hinbekommen. Ist in function.php integriert und ziemlich cool

**Comment by joergsteinhauer** [comment]
Das ist wirklich cool, sehr schön! Konnte ich auch gleich was lernen.

Habe es nur noch aufgeräumt und ähnlich wie alle anderen Custom-Functions in den Verzeichnis `wp-content/themes/zen-reiki/includes/functions/` gepackt.
