### ISSUE TITLE
SVG sind zu groß

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#213]
Wir haben auf dem Testserver ein Plugin installiert, was automatisch mobile Seiten generiert.
Dieses Plugin zeigt auch Fehler, die im System sind, an, insbesondere falsche Bilder.

Deine SVG sind zu groß erstellt oder gespeichert.
![grafik](https://user-images.githubusercontent.com/6114076/53804291-6d455900-3f47-11e9-90a2-b0b351419890.png)

Damit musst du schon auf dem Desktop runterscalieren.
![grafik](https://user-images.githubusercontent.com/6114076/53804431-c7461e80-3f47-11e9-82a8-42786f3402ef.png)

**Comment by joergsteinhauer** [comment]
Was macht das Plugin? "Mobile Seiten generieren"? Darf ich erfahren, was das für ein Plugin ist? Mir bleibt der Sinn des Plugings gerade verborgen...
Ich sehe nur, dass er die Grafik anmeckert, weil diese u.u. "unscharf" werden kann -was bei SVG meist nicht der Fall ist (nur bei ganz kleinen Grafiken). 

In unserem Fall haben diese Icons unterschiedliche Größen, je nach Größe des Bildschirms. Also gibt es nicht "die eine Größe", an die man angleichen könnte. 

Und zudem: auch wenn man die SVG pixelgenau ausrichten würde, wäre das Unmenge an Arbeit, was ich nicht machen werde. Den Unterscheid wird man hier auch gar nicht sehen.

Oder siehst du irgendwo unscharfe Icons?

--------------------

SVG sind, wie der Name schon sagt - Scalable Vektor Graphic - SKALIERBAR.

Damit ist an sich alles gesagt, die SVG können sonst wie groß sein und dann ohne Verlust skaliert werden. 

Vektorgrafiken bestehen nicht aus einzelnen Pixlen, sondern aus Linien, die an bestimmten Stellen dann verbogen werden, aus Pfaden etc.

Die Dateigröße hängt davon ab, wieviele Pfadpunkte die Grafik hat. Wenn ich die Grafik skaliere, bleibt die Anzahl der Pfade gleich. 

Also ist es vollkommen egal, wie groß die Vektor Grafik ist. Wichtig ist, dass diese sauber ist.

Ich habe testweise zwei neue SVGs erstellt, mit komplett gleichen Inhalt. Und oh Wunder, die kleine Grafik (64px) hat sogar mehr KB als große Grafik (100px):

![grafik](https://user-images.githubusercontent.com/1843754/53806822-535b4480-3f4e-11e9-9888-73140ebbc0eb.png)

Man sieht das schon an der länge des Codes.

Die SVGs kann man mit diversen Tools optimieren, z.b. https://jakearchibald.github.io/svgomg/

Ich habe das auch schon gemacht (vlt. nicht für alle Grafiken, aber für viele).

**Comment by joergsteinhauer** [comment]
Ist es noch relevant? Wie heißt denn das Plugin?
