### ISSUE TITLE
Posttyp testi (Meinungen) ablösen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#214]
Im Moment haben wir unter Meinungen die Beiträge der Schüler. Parallel als Kategorie Meinungen.
Im Sinne der Vereinfachung würde ich diese Meinungen, also Posttyp testi komplett rausnehmen.

![grafik](https://user-images.githubusercontent.com/6114076/53934859-90394f80-40a4-11e9-8ca6-02970d326f60.png)

Dazu wäre durch dich aber folgende Umgestaltung nötig. Auf der Startseite müsste unten nicht der letzte Posttyp testi, sondern der letzte Beitrag aus der Kategorie Meinungen angezeigt werden.
Ich hoffe, du bekommt das hin und es ist nur eine Kleinigkeit.

**Comment by joergsteinhauer** [comment]
Leider ist es keine Kleinigkeit, werde ich also noch angehen müssen, wenn ich mehr als eine Std. am Stück Zeit haben.

Ich verstehe die Problematik. Finde es schon ziemlich Schade, in Anbetracht dessen, wie viel Aufwand ich da reingesteckt habe. Evtl. hätte man das gleich am Anfang sehen können und den Posttype gar nicht erst entwickeln... na egal. Ich denke, ich werde das Layout ja weiterhin verwenden können.

**Comment by springers54** [comment]
So viel Arbeit? Das ist doch der kopierte Teil aus dem Cherry in der Datei custom-post-type-short-codes.php
Wir haben das nicht zum Spaß entfernt, sondern weil es leider an anderen Stellen nicht ordenlich funtktioniert hat. Der Posttyp ist doch nicht entwickelt worden, sondern war Teil des alten Systems.

/* ########################### */
/* KOPIERT vom CherryFramework */
/* ########################### */

/* Testimonial (Meinung) */

//Recent Testimonials
if (!function_exists('display_custom_post_type_testimonial')) {

    function display_custom_post_type_testimonial( $atts, $content = null, $shortcodename = '' ) {
        extract(shortcode_atts(array(
            'num'           => '5',
            'thumb'         => 'true',
            'excerpt_count' => '30',
            'custom_class'  => '',
        ), $atts));

        // WPML filter
        $suppress_filters = get_option('suppress_filters');

        $args = array(
            'post_type'        => 'testi',
            'numberposts'      => $num,
            'orderby'          => 'post_date',
            'suppress_filters' => $suppress_filters
        );
        $testi = get_posts($args);

        $itemcounter = 0;

        $output = '<div class="zr-wrapper-box-testimonial">';

**Comment by joergsteinhauer** [comment]
Das Entfernen vom Posttype Testi ist nicht das Problem, sondern das hier:

> Auf der Startseite müsste unten nicht der letzte Posttyp testi, sondern der letzte Beitrag aus der Kategorie Meinungen angezeigt werden

**Comment by springers54** [comment]
### Alternative Lösung:
Wir nehmen das komplett von der Startseite weg. den ganzen gelben Bereich mit dem Posttyp testi.
Ich habe ein Plugin gesucht: List category post, was wir vielleicht nutzen könnten, um die Seite nicht komplett statisch zu machen.
![grafik](https://user-images.githubusercontent.com/6114076/54471656-bce41a00-47bc-11e9-8988-236d079a873c.png)

sieht im Moment noch schrottig aus, aber vielleicht eine Idee, mit der du weitermachen könntest?
Ich blende es jetzt wieder aus.
Der code ist: 
[catlist name="*neues"]

**Comment by joergsteinhauer** [comment]
Was genau soll da nun angezeigt werden? Nur der Titel des Beitrags? Oder, wie bei "Testi", der Inhalt, Bild etrc... ?

Ich versuche es erstmal ohne Plugin, habe initial schon was hingekriegt.

**Comment by springers54** [comment]
Optimal, wenn es keine neuen Probleme macht, wäre
 * [ ] Bild des Beitrages
 * [ ] Titel des Beitrages
 * [ ] Anteasertext

Es würde reichen, wenn es der letzte Beitrag ist und nicht noch mehrere. Das Plugin sollte eher eine für dich einfache Alternative sein.

**Comment by joergsteinhauer** [comment]
Alles Mist mit eigenen PHP-Lösungen... da bin ich halt kein Entwickler für... daher bleibt hier leider nur ein Plugin als Lösung. Ich habe mal ein [anderes Plugin](https://wordpress.org/plugins/display-posts-shortcode/) ausprobiert, weil dieser noch nicht "tot" ist wie [das andere](https://de.wordpress.org/plugins/list-category-posts/). Im Grunde sind die Plugins gleich, haben die gleichen Funktionalitäten.

Ich könnte sowas hier ausgeben:
https://zen-reiki.de/testseite-joerg/

![image](https://user-images.githubusercontent.com/1843754/54497287-249f7f80-48f9-11e9-9a6c-e28854e3657b.png)

Also: **Überschrift, Text und Button.** Natürlich ordentlich gestylt. 

Leider ohne Bild, da die Bilder in den Beiträgen direkt im Content stecken und nicht als "Beitragsbild" definiert wurden.
![image](https://user-images.githubusercontent.com/1843754/54497482-67625700-48fb-11e9-8c3f-7bee6cb33046.png)

Und es würden immer 4 Beiträge angezeigt, weil wir doch mal für einige Kategorien die default-Anzahl der anzuzeigenden Beiträgen auf 4 gesetzt haben:
`wp-content/themes/zen-reiki/includes/functions/categories-query.php`

Wäre das eine Lösung?

**Comment by joergsteinhauer** [comment]
Im Übrigen, wäre es korrekt, die eingebauten Bild-Funktionalitäten von WP zu nutzen - und zwar das **Beitragsbild**.

Wenn man dieses Beitragsbild festlegt, dient es u.a. als Vorschau-Bild für viele Verarbeitungen an unterschiedlichsten Stellen (wie z.b. in Plugins, als erstes Bild im Content etc).

Nun ist es bei ZR einfach historisch so gewachsen (noch im alten System), dass die Bilder manuell im Content eingefügt wurden. Somit haben wir das nun auch im neuen System. Macht an sich nichts kaputt, stört aber wie man sieht beim Implementieren von neuen Features.

Ich möchte das mal gesagt haben - damit ihr wisst, warum einiges nicht so funzt wie man möchte.
Entweder wir leben damit oder es müsste jeder Beitrag UND dann noch das globale Layout bezüglich des Beitragsbildes angepasst werden (welches dann ja immer oben erscheinen würde).

**Comment by springers54** [comment]
### Bitte keine Plugins ohne vorherigen Test auf dem Testserver installieren
Vielleicht ist es dir schon aufgefallen, dass sich viele Plugins nicht rückstandslos deinstallieren lassen, viele Einträge in der Datenbank erzeugen, die nicht verschwinden oder auch Tabellen anlegen, die bleiben. Dazu gibt es den Testserver, den du zwar als überflüssig ansiehst, aber der genau das verhindert, dass wir uns das Live-System kaputt machen. 
Falls du also meinst, ein von uns vorgeschlagenes Plugin wäre ungünstig, dann schreib das bitte, wenn du es nicht testen kannst, dann werden wir das uns ansehen. Aber bitte nicht eigenmächtig.

### Beitragsbilder oder eingebaute Bilder
Prinzipiell ist es uns egal, ob das eine oder andere verwendet wird. Es ist jetzt so gewachsen, aber da sind wir anpassungsfähig.

### Dein Vorschlag oder nur eine Liste
Uns reicht eine Liste der letzten Themen, so wie wir es vorgeschlagen haben. Es müsste daraus nur ein gestalteter Block einstehen, der eine Überschrift hat (Neu bei Zen-Reiki), dann reicht eine Liste der Themen, die auf die Beiträge verlinkt.

**Comment by joergsteinhauer** [comment]
Ok, das mit Plugins geht klar, mein Fehler. 
Liegt an der Natur der allen möglichen Erweiterungen, dass diese diverse Spuren hinterlassen. Hier gibt es Ablösung, welche ich euch auch empfehlen würde - natürlich in Form eines Plugins (was für Ironie...) 
https://www.maketecheasier.com/delete-unused-database-wordpress/

Ich sehe gerade, dass von mir ausgewählte Plugin leider invalides Markup erzeugt - das können wir nicht gebrauchen, ich werde also den von dir vorgeschlagenen Plugin einsetzen.

Aber, wenn ich lese:
> es müsste daraus nur ein gestalteter Block einstehen

Wie solls denn aussehen? Ich fange hier nichts auf eigene Faust an.

Damit es nach "etwas" aussieht, schlage ich vor, das ganze wie bei "Testi" zu gestalten:
![image](https://user-images.githubusercontent.com/1843754/54782153-7d835680-4c1e-11e9-90d0-6ae168f1bc62.png)

Also Blöcke untereinander. Oder wenns zu viel wird, könnte man alle Einträge in einem Block unterbringen. Evtl. dann auch ohne Anführungszeichen.

**Comment by springers54** [comment]
also von der Idee passt es schon

### Weitere Gestaltung
 * [x] Gelber Block soll bleiben
 * [x] Überschrift im gelben Block: Neues bei Zen-Reiki
 * [x] nur ein weißer Kasten, in dem die 4 letzten Beiträge sind mit einer Überschriftszeile der H1 und einen Kurztext aus max. 2 Zeilen mit ...

Das wäre das Optimale, wenn es nicht zuviel Aufwand macht, ansonsten bitte nur die Titel der Beiträge als Liste und verlinkt.

**Comment by joergsteinhauer** [comment]
Bitte checken.

Kurztext ist bei 25 Zeichen, man kann keine Zeilen definieren, nur Zeichen.
Button kann ich hier nicht so richtig rechts ausrichten... zur Not entfernen wir diesen wieder, wenns so nicht gut genug aussieht.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/54862299-d7783f00-4d38-11e9-9e0c-f2fbe5e52333.png)


Gefällt uns nicht wirklich. Nimmt viel zuviel Platz weg, ist zu groß und aufdringlich.

* [x] Überschrift sollte im gelben Block stehen und nicht im weißen Kasten
* [x] Alle Buttons sind bei uns rechtsbündig.

Wenn es keine Möglichkeiten gibt, das zu verkleinern, dann bitte nur die letzten 2 Beiträge darstellen.

**Comment by springers54** [comment]
Warum kann ich als Nutzer nicht mehr die Zahl der Beiträge im Plugin regeln???

**Comment by joergsteinhauer** [comment]
Weil wir doch die Anzahl der Beiträge im custom PHP-Code angepasst haben (war eine Anpassung von deinen Jungs):

**wp-content/themes/zen-reiki/includes/functions/categories-query.php**

```php
<?php
/**
 * Zen Reiki function: change query for chosen categories
 */

function modify_query_for_categories($query) {
    if ($query->is_category('2536') ||($query->is_category('2531')||$query->is_category('40')||$query->is_category('41')||$query->is_category('73')||$query->is_category('75')||$query->is_category('76')||$query->is_category('83')||$query->is_category('91'))){

        $query->set( 'posts_per_page','4' ); // show 4 posts
    }
}
add_action('pre_get_posts', 'modify_query_for_categories');
```

Ich habe bis jetzt nicht hingekriegt, dass die Startseite davon nicht betroffen ist. Frag doch bitte deine Jungs

**Comment by springers54** [comment]
Ich kann mich damit nicht vor dem 2.4. beschäftigen. Ich habe eine Idee, wie man das lösen kann. Schieben wir es also auf.  Ich ändere als Zwischenlösung erst mal die Funktion so, dass dort nur 3 Beiträge gezeigt werden.

Das haben wir erst mal gemacht. Man muss sicher einfach nur in die Funktion eine Ausnahme reinbringen, dass sie nicht für den post 230 gilt, das ist unsere Startseite. Ist ja kein Hexenwerk, sondern ziemlich einfach.

 * [x] Bitte die anderen offenen Dinge erledigen, Überschrift, Button

**Comment by joergsteinhauer** [comment]
>  Ich ändere als Zwischenlösung erst mal die Funktion so, dass dort nur 3 Beiträge gezeigt werden.
wie und wo hast du das geändert?

Ja, sollte theoretisch kein Hexenwerk sein. Ich habe einiges probiert - `is_single`, `is_singlular`, `is_page`, `is_home`, `is_front_page` - hilft alles nicht.

**Comment by joergsteinhauer** [comment]
Was soll man da noch verkleinern? 
- Es ist ein titel da - der muss so bleiben.
- Text ist bei Desktop auf ca. 2 Zeilen, wie gewünscht. Textgröße ist die minimale hier. Geht nicht kleiner.
- Button ist da, mit einem passenden Abstand nach oben. Buttongröße wie immer. Geht nicht kleiner. Entweder so lassen oder komplett weg (wie schon oben erwähnt).
- Alle Abstand (innen/außen) sind genormt und wie überall und passen gut. Geht also nix mehr kleiner.

**Comment by springers54** [comment]
![grafik](https://user-images.githubusercontent.com/6114076/54901487-e5fc5d00-4ed6-11e9-8607-3b525eacdd20.png)
 * [x] **Überschrift in schwarz**
 * [x] Button können weg

Der Rest ist gelöst, wir hatten eine Idee, die funktioniert

**Comment by joergsteinhauer** [comment]
Wunderbar. Habt ihr dabei zufällig in PHP Dateien oder so rumgeschrieben? Wenn ja, müsste ich wissen wo, damit ich das nicht überschreibe.

**Comment by springers54** [comment]
wp-content/themes/zen-reiki/includes/functions/categories-query.php ist wieder auf 4 gestellt, sonst nichts.
Aber du solltest auch keine PHP-Dateien einfach von dir aus ersetzen, das könnte immer schief gehen. Ansonsten dachte ich, dass dein Ressort die Stylings sind?

**Comment by joergsteinhauer** [comment]
Größtenteils mache ich ja Stylings, aber auch PHP seitig... ohne gehts ja nicht ;-). Daher frage ich bei PHP lieber nach, bevor was schief geht
