### ISSUE TITLE
Schon wieder neue Probleme auf der Homesite

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#215]
![grafik](https://user-images.githubusercontent.com/6114076/54103322-5336cb00-43cc-11e9-9bef-64e6b55e1312.png)
 Änderungen sind mal wieder gründlich daneben gegangen. Sei bitte so gut, wenn du Stylings veränderst, dir das, was du getan hast, auch mal anzusehen.

**Comment by Dani2909** [comment]
![grafik](https://user-images.githubusercontent.com/39252760/54103375-81b4a600-43cc-11e9-817f-d1080dfc6f20.png)

und so sieht es bei mir aus

**Comment by springers54** [comment]
ich habe im Quelltext erst einmal das class=title-h2 weggenommen und die Zeile zentriert. Leider bleibt die Sitation bei Dani so, wie hier im Bild, die Überschriften unten sind leider zentriert. Auf meinem Rechner ist es aber nicht.

**Comment by joergsteinhauer** [comment]
Asche über mein Haupt, habs gefixt.

**Comment by springers54** [comment]
aber so richtig wohl nicht. Siehe Ipad im Hochformat.
![grafik](https://user-images.githubusercontent.com/6114076/54368072-c6ae3600-4673-11e9-9df3-fd427f452165.png)

**Comment by joergsteinhauer** [comment]
Hm, was ist denn da jetzt falsch? Obere zwei Überschriften sind mittig, sit ja korrekt.
In der Liste sind die Orange-Titel linksbündig, das ist auch korrekt.

**Comment by springers54** [comment]
Bisher war das IPAD wie PC, also die oben gezeigten Texte nebeneinander. Sowohl im Hoch- als auch im Querformat.  Nur auf dem Handy war es untereinander.

**Comment by joergsteinhauer** [comment]
Komisch. Die Anordnung hängt von Media Queries ab, also von den definierten Breakpoints. Das sind 4 oder 5 und die haben sich nicht geändert. 

Bist du sicher, dass auf deinem Ipad diese Liste mal anders aussah? Ist es vlt ein neues Ipad? Welches genau ist es, welche Breite hat es? Was sagt https://www.mydevice.io/? 

Das Layout der Liste ändert sich bei 800px.

An sich ist es ja kein Fehler, wenn das Layout anders ausgerichtet ist. Ich möchte jetzt nicht unbedingt den Breakpoint für diesen einen Fall ändern - ich füge auf keinem Fall einen neuen Breakpoint, der nur wenige px Unterschied hat. Und den 800px Breakpoint würde ich auch nicht ändern, denn dann würden sich so ziemlich viele andere Layouts ändern.

Wir finden schon eine Lösung, ich brauche erstmal Antworten auf alle meine Fragen.

**Comment by springers54** [comment]
Hier ein Screen aus alten Zeiten:
![grafik](https://user-images.githubusercontent.com/6114076/54492174-7bd72d00-48c4-11e9-945f-8198a78efbb9.png)
 So ähnlich hätte ich es auch gerne wieder.
768 px hat das IPAD im Hochformat, also ändere bitte unterhalb von 768px

**Comment by joergsteinhauer** [comment]
Das hier ist ein Screenshot aus dem alten System, ich sehe das an den Icons. Dort hatten wir entsprechend anderen Breakpoints.

Ich ändere den 800px Breakpoint gern mal auf 768 oder so, aber dann muss ich nochmal darauf verweisen, dass alle anderen Seiten und viele Module davon betroffen sind. Ich will jetzt nicht unbedingt einen Breakpoint ändern und dann tausend mal diverse Baustellen glatt ziehen, nur weil dir das Aussehen nicht ganz zusagt. Am ende ist doch nichts kaputt.

Also ich warte erstmal auf finales grünes Licht mit Kenntnisnahme aller Konsequenzen. Sorry, aber ich gehe auf Nummer sicher.

**Comment by springers54** [comment]
Ändere den Bralepoint von 800 auf 768 oder 767, so dass auf dem IPAD noch die PC-Ansicht zu sehen ist.

**Comment by joergsteinhauer** [comment]
Na dann. Habe ich gemacht,es gab natürlich Verschiebungen (Header, Menü), diese habe ich angeglichen. Falls noch woanders was auftauch, bitte Bescheid geben. Ich habe die meisten Seiten angeschaut.

**Comment by springers54** [comment]
leider hat das wohl nicht geklappt, es ist auf dem IPAD im Hochformat weiterhin nicht so, wie es sein soll,
Ich sehe keinerlei Verbesserung, eher neue Dinge, die nun nicht mehr passen.

### Neue Fehler:
 * [ ] die Startseite im Hochformat ist weiterhin nur einspaltig
 * [x] dafür sind die Texte in der gelben Leiste im Banner im Querformat auf einmal zweizeilig an einer Stelle, im Hochformat witziger Weise nicht
 * [ ] das Bannerbild im Hochformat ist jetzt viel zu hoch, nimmt fast den halben Bildschirm ein
 * [x] wenn du eingeloggt bist, ist die obere Adminleiste zerschossen, Icons hängen tiefer und Beschriftung fehlt im Hochformat.

.... vielleicht deine Änderungen wieder rückgängig machen? Das war es nicht

**Comment by joergsteinhauer** [comment]
Sorry, ich kann mit deiner Fehlerbeschreibung an sich nix anfangen - Screenshots fehlen. Und weitere Infos fehlen auch: betrifft das alles nur IPad? Was sagt https://www.mydevice.io/ wenn du mit deinem Testgerät drauf gehst - welche Breite/Höhe hat dein Gerät in PX?

**Bei Fehlermeldungen immer Screenshots und ausführliche Angaben zum Testgerät angeben! Sonst kann ich nix fixen.**

-----------------------

Zum Breakpoint: der ist bei 768px, wie angefordert:
https://gyazo.com/42b505365b78264bf8f4836900c33017

Kann sein, dass dein Testgerät eben nicht 768px Breit ist... oder ich es um einen px verschieben muss.

-----------------------

Die anderen Fehler sind wohl diese hier?
![image](https://user-images.githubusercontent.com/1843754/54848473-a3256400-4ce1-11e9-9c90-80d84f3905a0.png)

- Admin-Leiste hat nix mit meinem CSS zu tun, das ist schon immer so. Die vielen Plugins fügen eben weitere Menüpunkte ein... da kann ich nix für.

**Comment by joergsteinhauer** [comment]
Habe den Breakpoint nun von 768 auf 720px geändert, sollte nun endlich funzen. 

für alle noch offenen Probleme bitte Screenshots angeben und Gerät-Info.

**Comment by springers54** [comment]
**Hat leider nichts gebracht, alle Probleme sind noch da.**

> Ändere den Bralepoint von 800 auf 768 oder 767, so dass auf dem IPAD noch die PC-Ansicht zu sehen ist.
Steht oben in der Issue

Ich habe dir mehrfach geschrieben, welche Geräte ich habe, und auch nach deinen Anweisungen die Pixel notiert. Also frag bitte nicht immer das Gleiche. Wir haben beide das gleiche Handy, ich habe ein IPAD mini 2, Dani ein IPAD, beide haben die gleichen Pixel 768 im Hochformat..

**Comment by joergsteinhauer** [comment]
Ist hier noch was zu tun? Wenn ja, bitte bestehende Kommentare so mit Screenshot ergänzen, dass es verständlich ist
