### ISSUE TITLE
Button auf der Homesite bitte kleiner machen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#216]
uns sind diese Kreise einfach im Vergleich zum Rest zu groß
![grafik](https://user-images.githubusercontent.com/6114076/54103856-3b604680-43ce-11e9-9865-4ada5f5459cb.png)

Wir haben hier abgestimmt, wie wir uns die Größe vorstellen. Anstelle von 6em, die du verwendest, bitte 5 em machen.
Hier die Regel, die du nutzen kannst:
}
.zr-box-service .zr-link-service {

    height: 5em;
    width: 5em;

}

**Comment by joergsteinhauer** [comment]
Erledigt

**Comment by springers54** [comment]
kannst  du vielleicht die Bilder unten auch noch reduzieren von 4em auf 3 em?
zr-wrapper-box-featured img {
    width: 3em;
    transition: transform 0.2s;
![grafik](https://user-images.githubusercontent.com/6114076/54366659-54d4ed00-4671-11e9-8be5-c0af760a9e5d.png)

**Comment by joergsteinhauer** [comment]
Jep, erledigt.
