### ISSUE TITLE
Forum Styling muss leider wieder angepasst werden, auch auf Desktop

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#217]
https://zen-reiki.de/forum/
Für das Handy hattest du es angepasst, leider sieht es auch auf dem Desktop nicht wirklich gut aus.
![grafik](https://user-images.githubusercontent.com/6114076/54412557-7971a900-46f3-11e9-9bd5-8588d217a580.png)
Die linken Symbole sind viel zu groß, die rechten Texte ebenfalls. Es sollte sich auch kein Umbruch unter dem Bild ergeben

### Syling anpassen Desktop, bitte ebenso Kontrolle für Handy und IPAD
 * [x] Symbole kleiner machen
 * [x] Schriften techts kleiner machen.

**Comment by joergsteinhauer** [comment]
Erledigt.

Übrigens, ein sehr schön geschriebenes Ticket :)

**Comment by springers54** [comment]
Die Erledigung kommt bei mir nicht an:
![grafik](https://user-images.githubusercontent.com/6114076/54477067-68648d00-4804-11e9-8315-288c93614448.png)
