### ISSUE TITLE
Testsystem benutzen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#218]
Die aktuellen Probleme, dass die Änderungen uns immer wieder das Livesystem zerschießen, und wir nur noch am Suchen und Vergleichen sind, lassen uns noch einmal die Frage aufwerfen, ob es nicht sinnvoller ist, auf einem Testsystem die Sylings anzupassen und erst nach dem Absengnen auf das Livesystem zu übertragen?

**Comment by joergsteinhauer** [comment]
Das ist wieder ein Aufwand! Also wirklich großer Aufwand für mich. Und ich weiß nicht ob das am ende dann alles glatt läuft. Zudem sollten dort die Inhalte in etwa gleich sein.... lieber nicht.

**Comment by springers54** [comment]
Im Moment erscheint es wohl der einzige Weg, um voran zu kommen. Wir gehen rückwärts und nicht vorwärts.

**Comment by springers54** [comment]
Ich schließe das hier mal, da du ohnehin damit nicht arbeitest
