### ISSUE TITLE
Bildgröße auf der Detailseite Desktop

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#223]
### Buchbilder 128 px

Alle Bilder sind von uns bereits in der richtigen Größe eingebunden. Das bedeutet, dass du diese Bilder nicht skalieren musst. Sie bleiben einfach so, wie sie sind.

Warum du hier skalieren musst, ist mir unklar:
![grafik](https://user-images.githubusercontent.com/6114076/55701531-cb94aa00-59d3-11e9-94d0-4a34b9f02121.png)

**Comment by joergsteinhauer** [comment]
Jetzt hab ichs... dir gings wirklich um die 2px Unterschied. Den feinen Unterschied habe ich visuell gar nicht gemerkt und hatte tatsächlich einen Fehler im CSS. 

Ich ging davon aus, dass es dir um die Skalierung auf kleineren Bildschirmen ging.

Ist gefixt.

**Comment by springers54** [comment]
Mir geht es nicht nur um die 2 px, sondern um alle Bildgrößen, stimmen die jetzt durchgängig?

**Comment by joergsteinhauer** [comment]
Ok. Na laut deinem Screenshot gab es die Abweichung von 2px, daher frage ich... 
Ja, es stimmt, zumindest auf Desktop. Wenn das Fenster kleiner ist, werden die Bilder kleiner skaliert, sodass der text nebenan noch genug Platz hat und lesbar bleibt. 
Testet mal lieber durch.

**Comment by springers54** [comment]
### Warum scalierst du die Bilder, auch wenn es nur 2 px sind?

![grafik](https://user-images.githubusercontent.com/6114076/56112732-37d75680-5f5c-11e9-8b30-a5701cafe4c1.png)

https://zen-reiki.de/bereich/symbole/shamballa-atlantisches-meistersymbol/

**Comment by joergsteinhauer** [comment]
Nö, alles ok. Cache?

Hier in meinem FF:
![image](https://user-images.githubusercontent.com/1843754/56693082-d9407400-66e3-11e9-8068-f6d9ff6f84a9.png)
