### ISSUE TITLE
Google Lighthouse: Accessibility

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#224]
> Der Test muss jedesmal und auf jeder Unterseite mit dem Chrome DevTool ausgeführt werden. ACHTUNG: man darf nicht eingeloggt sein!

**Stand 14.04.2019:**
![image](https://user-images.githubusercontent.com/1843754/56098736-bb188e00-5f03-11e9-964c-a1b8e49d9d1c.png)

@springers54 Am besten wir arbeiten mit folgendem Workflow: Jeder Kommentar von mir bildet ein Problem ab. Das Problem wird geschildert und es wird eine Lösung angeboten.Dazu gibt es eine Aufgabe zum Abhaken: **FREIGABE**. Sobald diese Aufgabe durch dich angehakt wird, beginne ich mit der Umsetzung der Lösung.

Falls du Fragen hast, bitte diese im jeweiligen Kommentar unterbringen (einfach unterlab meines Textes, getrennt durch eine horizontale Linie)

**Comment by joergsteinhauer** [comment]
# Background and foreground colors do not have a sufficient contrast ratio.

**Probleme:** 

Dunkelgraue Schrift ist nicht lesbar. 
![image](https://user-images.githubusercontent.com/1843754/56098607-4a24a680-5f02-11e9-925c-dae3a6a42988.png)
Die war ja schon mal weiß, aber ihr wart der Meinung, dass Grau besser passt... wie man sieht eben nicht.
![image](https://user-images.githubusercontent.com/1843754/56098677-f9fa1400-5f02-11e9-8cc9-b20c92389fe8.png)

**Lösung:**

Weiße Schrift

**Freigabe:**

- [x] Lösung darf umgesetzt werden

**Comment by springers54** [comment]
* [x] Dann nimm bitte eine schwarze Schrift, wenn der Kontrast zu gering ist.

Ansonsten sollten wir uns im Moment auf die Behebung von Fehlern konzentrieren

**Comment by joergsteinhauer** [comment]
Du meinst sicherlich WEIßE und nicht SCHWARZE Schrift

**Comment by springers54** [comment]
> 
> 
> Du meinst sicherlich WEIßE und nicht SCHWARZE Schrift

Da die dunkelgraue vom Kontrast zu gering ist, dachten wir SCHWARZ und nicht grau. Denn weiß auf Gelb hat wohl noch weniger Kontrast und gefällt uns nicht.

**Comment by joergsteinhauer** [comment]
Erledigt. Schwarze Schrift auf Orange und Weiß auf Dunkelgrau (Footer).
