### ISSUE TITLE
Bildgrößen auf mobilen Geräten stimmen nicht

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#225]
![grafik](https://user-images.githubusercontent.com/6114076/56112135-6d7b4000-5f5a-11e9-9e5f-a6019d8f30bd.png)

Die Dinge sind leider nicht bearbeitet und auch oben nicht abgehakt.

Im Moment ist es genau falsch rum umgesetzt. **Die Bilder auf der Detailseite sind klein, die auf der Übersichtsseite groß.**

### Bild der Übersichtseite ist aktuell 50% der Breite
![grafik](https://user-images.githubusercontent.com/6114076/56112341-145fdc00-5f5b-11e9-91b5-7cbd0c6c788d.png)

### Bild der Detailseite ist aktuell 30% der Seite
![grafik](https://user-images.githubusercontent.com/6114076/56112382-3d806c80-5f5b-11e9-9a85-1cb551c3cd5d.png)

### Tabelle mit Bilder mobil zerschossen
![grafik](https://user-images.githubusercontent.com/6114076/56112437-66a0fd00-5f5b-11e9-82b9-91615b640785.png)

_Originally posted by @springers54 in https://github.com/springers54/reiki/issues/185#issuecomment-483128625_

**Comment by springers54** [comment]
Ich habe hier diesen Teil aus Issue #185 noch einmal rausgezogen. Du hattest zwar den letzten Fehler mit den Tabellen behoben, aber nicht die Bildgröße von Übersichtsseite und Detailseite.

 * [ ] Bilder auf der Übersichtsseite max 30% der Breite
 * [x] Bilder auf der Detailseite max. 50% der Breite
 * [x] Kleinere Bilder in einen Rahmen setzen, der der Bildbreite entspricht

**Comment by joergsteinhauer** [comment]
Zu "Kleinere Bilder in einen Rahmen setzen, der der Bildbreite entspricht" s. meinen Kommentar hier https://github.com/springers54/reiki/issues/185#issuecomment-486420319

**Comment by springers54** [comment]
Funktioniert leider auf dem Handy nicht. Siehe Übersichtseite Heilen, wo ein Buch und ein normaler Beitrag auf einer Seite sind. Man sieht, dass die Texte nicht floaten, also das Buchbild viel zu breit ist.
![grafik](https://user-images.githubusercontent.com/6114076/56784464-e7c88180-67f0-11e9-927a-ac729c54fae0.png)

**Comment by joergsteinhauer** [comment]
Korrekt, war mein Fehler. Wurde gefixt.

Übrigens, die Aussagen "Man sieht, dass die Texte nicht floaten" ist nicht korrekt. Die Texte in deine, Screenshot floaten (d.h. übrigens "fließen um etwas um"), nur die Bildgröße ist anders.

**Comment by springers54** [comment]
Leider ist die Funktionalität nicht konsistent. Auf dieser Seite funktioniert es, auf anderen wieder nicht. Leider dadurch noch schwieriger, dass es mal auf dem Handy nicht stimmt und mal auf dem PC.
So befürchte ich, dass die Änderungen für dich wieder problematisch werden und andere Dinge wieder zerschießen, die im Moment passen.

**Comment by springers54** [comment]
Folgender Fehler ist aufgefallen:
 * [x] Bildergrößen bei Meinungen falsch, wenn es sich um Personenbilder handelt, diese sind auf der Übersichtsseite zu groß. Ich habe probiert, sie nicht als Beitragsbild zu verwenden, sondern direkt einzufügen, was selbst mit class= randb left keine Verbesserung bringt.
Siehe:
![grafik](https://user-images.githubusercontent.com/6114076/57296545-84323400-70cd-11e9-91e8-8b4cc8652e6e.png)
https://zen-reiki.de/themen/bereich/meinung/page/2/

**Comment by joergsteinhauer** [comment]
Ja, ist ein Sonderfall, der noch nicht bedacht wurde (konnte ich auch so nicht erahnen). Sollte nun gehen, sobald diese Bilder die Klasse `left` bekommen.

Das Ausschlaggebende ist dabei, dass die Bilder als als Beitragsbilder ausgegeben werden. Was an sich ja gut ist.

**Comment by springers54** [comment]
Du meinst nicht als Beitragsbild, denn genau da funktioniert es nicht. So ist ja die klassische Einbindung bisher bei den Meinungen gewesen.
Wir müssen die Bilder direkt als Link im Beitrag vorne einfügen und dann die class=randb oder class=left verwenden, da wir die Bilder auf 150 gebracht haben, ist es egal. Hätten wir mal kleinere, wäre randb besser. Das war bei der Meinung von Peter gemacht und da funktioniert es.

**Comment by joergsteinhauer** [comment]
Jetzt bin ich baff.... ich könnte schwören, dass ich bei dem "Peter" Beitrag gesehen habe (zumindest im Quellcode), dass das Bild in der Beitragsbild-Box ausgegeben wurde... komisch. 
Na egal, scheint ja zu funktionieren.
