### ISSUE TITLE
Bildgröße bei Übersichtsseiten sind nicht stimmig: 150px auf Desktop

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#226]
### Bildergröße Übersichtseiten Desktop 150px
Die Bildergrößen auf den Übersichtsseiten waren einheitlich auf 150px auf Desktop und 1/3 der Breite auf Handy festgelegt. Kleinere Breiten werden in den Rahmen gesetzt, der die 150px Breite hat.

https://zen-reiki.de/themen/bereich/heilen/
![grafik](https://user-images.githubusercontent.com/6114076/56784986-8e158680-67f3-11e9-993e-134afbde9c18.png)

Leider stimmt das überhaupt nicht mehr, wo man auch guckt, außer bei Symbolen, weil die genau in dieser Breite eingebunden sind.

### Bildgröße Detailseite:
Lehrerseiten: 400 px
Symbolseiten : 150 px
Beitragsseiten: 300 px
Buchbilder 128 px

**Comment by joergsteinhauer** [comment]
Angepasst auf den Übersichtsseiten

Mobile (bis 720px) sind die Bilder max. 30% breit, ansonsten genau so breit wie sie angelegt sind.
Desktop (ab 720px) sind die Bilder max. 150px breit, ansonsten genau so breit wie sie angelegt sind. Bilder, die kleiner als 150px breit sind und die Klasse "forceDefaultWidth" haben, bekommen einen Rand und einen Abstand zum Rand, sodass die Gesamtgröße 150px beträgt.

**Comment by springers54** [comment]
https://zen-reiki.de/themen/bereich/coaching/
![grafik](https://user-images.githubusercontent.com/6114076/57296046-3ec13700-70cc-11e9-8393-8abb2a884a7e.png)

Hier funktioniert es nicht. Es hilft auch nicht, das Bild in einen Rahmen zu setzen

**Comment by joergsteinhauer** [comment]
Wiedermal Missverständnisse und unklare Anforderungen... 

Bevor ich was umsetzen, bitte klar definieren, wie es auf Mobile und Desktop sein soll. In beiden Fällen:  was passiert, wenn ein Bild zu groß und zu klein ist.

**Comment by springers54** [comment]
Der Wunsch war, dass die Übersichtsseiten bei allen Bildergrößen identisch sind. Was ist daran eine unklare Anforderung?

Und du hattest bereits den Weg gefunden, was in welchem Fall passiert.
Nur eben nicht einheitlich umgesetzt.

Also nochmal:
 * [ ] Bild ist zu groß, es wird verkleinert auf 150 ox
 * [ ] Bild ist zu klein, es kommt in einem Rahmen, der 150 px breit ist, siehe Bücher

**Comment by joergsteinhauer** [comment]
Ich zeige hier einfach mal, wie die korrekte Anforderung wäre. Ich denke mal, so ist es korrekt:

# Mobil

Alle Bilder sollen generell 30% breit sein. Achtung: nicht maximal 30% breit (so wie es noch der Fall ist), sondern IMMER 30% breit. 
- Wenn das Bild dabei größer als 30% ist, soll es eben auf 30% verkleinert werden.
- Wenn das Bild kleiner als 30% ist, soll es einen Rahmen und einen inneren Abstand bekommen, sodass es insgesamt auf 30% kommt.

# Desktop

Alle Bilder sollen generell 150px breit sein .Achtung: nicht maximal 150px breit (so wie es noch der Fall ist), sondern IMMER 150px breit. 
- Wenn das Bild dabei größer als 150px ist, soll es eben auf 150px verkleinert werden.
- Wenn das Bild kleiner als 150px ist, soll es einen Rahmen und einen inneren Abstand bekommen, sodass es insgesamt auf 150px kommt.

-------------

Wie du siehst, ist die Logik an sich die gleiche, nur haben wir Mobile %-Angaben, auf Desktop feste px Größen. Und wie du siehst, wurde in deiner Anforderung nicht alles bedacht. Ich sehe in deiner initialen Anforderung hier im Ticket nirgendwo die Sache mit 30%. Ich sehe feste px Angaben. Du schreibst zwar was von 1/3, aber das ist sowas von nicht nachvollziehbar, dass ich das eben missverstehe, Sowas sehe in vielen Tickets und genau das hindert mich daran, eure Wünsche zielgenau umzusetzen. Und das wird weiterhin so laufen, so lange ihr nicht klare und verständliche Anforderungen aufstellt.

**Comment by joergsteinhauer** [comment]
Bitte also erst meinen Anforderung-Vorschlag freigeben, danach beginne ich mit der Umsetzung.

**Comment by springers54** [comment]
Diese Issue hieß nicht ohne Grund im Titel DESKTOP und bezog sich genau darauf.
Gelernt hatten wir, dass die Vermischung von Desktop und Mobil zu mehr Verwirrung geführt hat und deshalb gab es für jede Geräteklasse eigene Issues.

**Comment by springers54** [comment]
Brauchst nichts mehr zu machen, wir sind den Weg des geringsten Widerstandes gegangen und haben die Icons auf 150 px gebracht. Das sollte damit die Probleme gelöst haben.
