### ISSUE TITLE
Seiten Credo zerschossen

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#228]
https://zen-reiki.de/credo/reiki-lehren/
Trifft aber auf alle Credo-Punkte in gleicher Weise zu, die man von der Startseite aus erreichen kann.

 * [x] Oben erscheint eine Fehlermeldung.
![grafik](https://user-images.githubusercontent.com/6114076/57296968-9d87b000-70ce-11e9-8aaf-5aad92556684.png)
 * [x] Es fehlt das Icon auf gelbem Grund
 * [x] Die Fehler treten auch auf mobilen Geräten auf
![grafik](https://user-images.githubusercontent.com/6114076/57297021-cb6cf480-70ce-11e9-9cc4-57d17377322f.png)

**Comment by joergsteinhauer** [comment]
Hm, kann den Fehler nicht nachstellen. Immer noch da?

Und was für "Icon auf gelbem Grund"? Screenshot?

**Comment by springers54** [comment]
https://www.dropbox.com/sh/tn0dcmc3d7l6okj/AAAPMXW4HBEiLmWeDBqyhR5ta?dl=0
Ich habe hier en Kleines Video aufgezeichnet, das das Problem beschreibt.

Es wäre schön, wenn die Detailseite das gleiche Icon hätte und das auch in einer gelben Fläche zu sehen wäre.

**Comment by joergsteinhauer** [comment]
Ok, jetzt ist es klar.

Wie du erkannt hast, hat ein Credo zwar ein Beitragsbild, dieses wird jedoch auf der Detailseite ausgeblendet - dieses Ausblenden gilt übrigens für alle News-Seiten, das war mal so gewollt und sollte auch so bleiben. Denn würde ich das Ausblenden deaktivieren, würden auf allen News-Seiten (die Beitragsbilder haben) überall die Bilder am Anfang der Detailseite erscheinen. Das wollen wir ja nicht. Also kann ich bei Credo Detailseiten nicht mit dem Beitragsbild arbeiten. 

Wir müssen hier direkt im Content, ähnlich wie auf "Internetschule" Beiträgen, die Icons einfügen. 
An sich könnt ihr das auch selber machen, die Icons sind ja da (obgleich diese super hässlich verpixelt sind - warum auch immer). 

Ich habe es mal auf Credo-Seiten eingefügt.
