### ISSUE TITLE
Icons optimieren

### ISSUE THREAD

**Issue by joergsteinhauer** [springers54/reiki#229]
Alle PNG Icons, die teilweise ja noch verwendet werden, kommen wohl noch vom alten System, sind verpixelt und zudem unterscheiden sich hier und da von den neu eingesetzten Icons.

![image](https://user-images.githubusercontent.com/1843754/57480598-7b458c00-72a0-11e9-9b36-a80120070aa9.png)

Es gibt zwei Lösungen:

1. SVG Icons verwenden. Hier muss man aber ein Plugin installieren, welches SVG erlaubt. Wordpress erlaubt nämlich (leider ziemlich grundlos) von Hause aus keine SVG Bilder im Content (also Mediathek). Es gibt dazu in der WP Gemeinde zahlreiche Diskussionen und viele Experten sehen keinen Grund für den fehlenden SVG Support. Fazit: man kann also SVG's ohne Bedenken verwenden, man braucht eben ein Plugin dazu.
Vorteil: verlustfreie und skalierbare SVG Grafiken
Nachteil: alle SVG Icons müssten in die Mediathek geladen werden und auf jeweiligen Seiten manuell eingebunden werden.

2. Bestehende PNG Icons neu anlegen.
Nachteile: 
Pixelgrafiken, heißt: auf hochauflössenden Displays sind die Bilder unscharf.
Großer Aufwand beim Erstellen der Icons.

----------

Meine klare Empfehlung: SVG verwenden, das ist auch die weltweit klare Empfehlung für Grafiken/Icons, vor allem im Bezug auf unterschiedlichste Display-Auflösungen.

---------------------

@springers54 bitte entscheiden, welcher Weg für euch in Frage kommt und das Ticket entsprechend priorisieren.

**Comment by springers54** [comment]
Wir haben 4 Icons, über die wir sprechen. Dafür möchten wir kein Plugin installieren. 
Wir werden danach auch keine weiteren Icons verwenden.
Es ist im Moment eingebunden und das genügt unseren Ansprüchen.

Wir haben die Icons angepasst, sie sollten jetzt auch nicht mehr verpixelt aussehen
