### ISSUE TITLE
Musterseite Symbole 

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#33]
Da ich für einige Systeme die Symbole beschreibe, sollte dies auch eine Art Musterseite sein.
Ich habe hierzu eine Standard-Beitragsseite als Vorlage verwendet.
Im Moment sieht es noch seltsam aus. Die H2, die ich oben verwendet habe, hat 1,75em, die H3 hat 2 em?

Kannst du da noch nachjustieren?
URL http://zen-reiki.de/symbole/seichem-lightening-bolt/

![a](https://cloud.githubusercontent.com/assets/6114076/22285578/7fe64c72-e2ec-11e6-9ec4-b32b1e38aafa.jpg)

Hast du eine Idee, wie man das Symbol besser halten kann? Dünner Rahmen, farbige Fläche?

**Comment by springers54** [comment]
Kannst du bitte bei den Symbolen in deinem Theme wieder den kleinen grauen Rahmen erlauben, den wir vorher hatten?, Wenn immer etwas mit `<symbol>` eingeklammert ist, hat es einen grauen Rahmen?
![grafik](https://user-images.githubusercontent.com/6114076/52179313-327dc300-27d9-11e9-92cb-af54e259714b.png)
https://zen-reiki.de/symbole/usui-reiki-dai-ko-mio

**Comment by joergsteinhauer** [comment]
Jep, hab das CSS ergänz. Die Klasse ist die selbe: `.image-preview`

**Comment by springers54** [comment]
Kannst du die Farbe des Rahmens heller machen, ein leichtes grau reicht aus, so wie es war im alten.

**Comment by joergsteinhauer** [comment]
Habe es angepasst, reicht so?

**Comment by springers54** [comment]
Ja. Farbe ist ok. Kann es sein, dass das Bild noch ein paar Pixel weiter runter sollte?
![grafik](https://user-images.githubusercontent.com/6114076/52341202-47916680-2a12-11e9-911a-51b9d1f9ede0.png)

**Comment by joergsteinhauer** [comment]
Wenn, dann nur aus reiner visuellen Sicht. Aber... das ist an sich korrekt so.

Das kommt von der Zeilenhöhe (line-height). Die Schrift hat oben und unten etwas Abstand, das ist Standard und sollte auch so bleiben.
![image](https://user-images.githubusercontent.com/1843754/52974378-91d6f800-33c1-11e9-9b5f-3660ec459839.png)


Man könnte dagegen steuern, in dem man künstlich das Bild runter schiebt oder Textblock hoch schiebt, aber das ist Humbug.

**Comment by springers54** [comment]
* [x] dann schieb das Bild runter, lieber Humbug als unschön

**Comment by joergsteinhauer** [comment]
Das `symbol` HTML Tag ist hier nicht valide, dieser ist nur innerhalb von SVG zulässig. Solltet ihr also mal überall entfernen.
![image](https://user-images.githubusercontent.com/1843754/53365822-70868680-3942-11e9-93c2-6ab59bd2b677.png)

![image](https://user-images.githubusercontent.com/1843754/53365867-8f851880-3942-11e9-949e-ddb9d56d33f2.png)

**Comment by springers54** [comment]
Wo sehe ich das? Bei mir kommt nur ein Java-Fehler
![grafik](https://user-images.githubusercontent.com/6114076/53470598-6bb8f400-3a62-11e9-94d0-c0a76b7036d6.png)

Das <symbol> Tag muss noch aus dem alten System kommen, denn die Seiten wurden übernommen.
Damals sollte es wohl ein Bild in Symbolgröße mit Rahmen darstellen.

Sollten wir es überall entfernen? @Dani2909 , das wäre dann dein Job.

**Comment by springers54** [comment]
> Das `symbol` HTML Tag ist hier nicht valide, dieser ist nur innerhalb von SVG zulässig. Solltet ihr also mal überall entfernen.

Das war im alten System auch schon drin.
Wir haben das mit Suchen und Ersetzen rausgenommen

**Comment by joergsteinhauer** [comment]
Ja, das kann durchaus sein. War also auch dort falsch. 
Super.

Nebenbei gesagt: die meisten Fehler und Warnungen kommen auch meist durch Plugins...
