### ISSUE TITLE
Forumstyling erneut, setzt #51 fort

### ISSUE THREAD

**Issue by springers54** [springers54/reiki#99]
Deine Stylingregeln scheinen Standardregeln außer Kraft zu setzen. Das hat die Folge, dass nun das Forum nach dem letzten Update sehr eigenartig eingerückt ist bei den Themen und auch die Ausrichtung des Icons, das die neuen Beiträge zeigen soll, nicht mehr passt.
https://zen-reiki.de/forum/

![grafik](https://user-images.githubusercontent.com/6114076/38778527-212e50ca-40bb-11e8-8176-4b241afd43f2.png)
Die richtige Darstellung ist in #51 Bild 2, dort sind die Ausrichtungen der Themen in Ordnung.

**Comment by springers54** [comment]
Der Fehler ist wieder da, hattest du etwas angepasst oder muss Less nochmal kompiliert werden?
![grafik](https://user-images.githubusercontent.com/6114076/44505938-5f637100-a6a4-11e8-933f-9c0e1783220f.png)

**Comment by joergsteinhauer** [comment]
Das Problem habe ich geöst. Es lag wieder an:

1. nicht aktuellem CSS - hier war wieder irgendeine ältere main-style.css vom 22 Juni oder so. Einige Sachen betreffend des Forums waren da überflüssig. Ich frage mich, wer die da hochgeladen hat. Habe also mein lokales LESS neu kompiliert und die main-style.css hochgeladen. Sicherheitshalber habe ich alle alten CSS in einen Backup-Verzeichnis unter "/zen-reiki.de/wp-content/themes/theme54991/_backups/" kopiert.
2. Cache Plugin - nach Cache löschen war auch der Kontakformular dann wieder ok.

Frage: wer arbeitet denn noch an der Website, also am Template? Mir scheint es, als ob jemand da Sachen überschreibt...

**Comment by springers54** [comment]
Ich danke dir. Wie bekommt man die Nutzer dazu, den Browsercache zu löschen? Denn ich konnte die Änderungen erst danach sehen. Das Löschen des Wordpress-Cache hatte leider keine Wirkung.

Erklären kann ich mir das nicht, denn es arbeitet niemand an der Seite. Das einzige, was ich gemacht habe, war die Einbindung von neuen Widgets im rechten Seitenbereich der Themen. Ob das aber die Ursache war, weiß ich nicht.

**Comment by joergsteinhauer** [comment]
Naja, Nutzer löschen an sich nie den Browsercache. Es sei denn man kennt das und löscht das manuell. Zudem löscht der Browser nach einer bestimmten Zeit automatisch den Cache bzw. Teile davon.

Viel mehr sollte man nach Änderungen am Theme den WP-Cache manuell löschen, dabei wird eine aktuelle CSS erstellt und im WP-Cache abgelegt. Auf diese wird dann auch zugegriffen. Dann sollte auch alles ok sein. 

Also ab und zu den WP-Cache im Admin-Bereich löschen.

Kann durchaus sein, dass die Anpassung der Widgets irgendwas getriggert und der WP-Sache verrückt gespielt hat.
